<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="eigth columns">
<?php

?>
<br><br><?php  foreach ($this->datos as $d) {?>
			<div class="circledate">
				<div class="textcircle">
					<?php echo $d["fecha_inicio"]; ?>
				</div>
			</div>
<div class="eigth columns">
			<h4><?php echo $d["titulo"]; ?></span></h4>

				<?php echo $d["fecha_inicio"]; ?> - <?php echo $d["fecha_fin"]; ?> 
			</p>
			<p>
				<?php echo $d["evento"]; ?> 
			</p>
			<p>
			<?php $ur='http://'.$d["url"];  ?>
			<a href="<?php echo $ur ?>"  target="_blank">
				<?php echo $d["url"]; ?> 
			</a>
			</p>
			<p>
			
<?php

$pos = strpos( trim($d["archivo"],' '), '.png');
$pos2 = strpos( trim($d["archivo"],' '), '.jpg');

if ($pos!='' || $pos2!=''){
?>
<IMG SRC="/public/images/uploads/<?php echo  trim($d["archivo"],' ');?>" width="550" height="550">
<br>
<a href="<?php echo $this->basePath()?>/application/eventos/bajar/<?php echo $d["id_evento"];?>">Bajar archivo : </a><?php echo $d["archivo"]; ?> 
<?php
}else
{
?>
<?php if($d["archivo"]==''){}else{ ?> 
<a href="<?php echo $this->basePath()?>/application/eventos/bajar/<?php echo $d["id_evento"];?>">Bajar archivo : </a><?php echo $d["archivo"]; ?> 
<?php }} ?>
</div>
			</p>
			<div class="hr">
			</div>
<?php }?>
</div></div></div>