<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="four columns">

	<?php
$form = $this->form;
$form->prepare();

echo $this->flashMessenger()->render();
?>
<a
						href="<?php echo $this->basePath() ?>/application/usuario/index">
						<i class="icon-arrow-left"></i> Regresar
					</a>
<?php
echo '<br>';
echo '<br>';
echo $this->form()->openTag($form);
echo '<p>';
echo $this->formlabel($form->get('ContrasenaNueva'));
echo $this->formelement($form->get('ContrasenaNueva'));
echo '<br>';

echo $this->formelement($form->get('submit'));
echo '                      ';
?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>
<?php
echo $this->form()->closeTag($form);
	
?>

</div>
			</div>
		</div>
	</div>
</div>