<?php include("public/menu.php"); ?>
<script type="text/javascript">
    $(function () {
        var opts = $('#id_autor option').map(function () {
            return [[this.value, $(this).text()]];
        });
        $('#filtro_autor').keyup(function () {
            console.log(2);
            var rxp = new RegExp($('#filtro_autor').val(), 'i');
            var optlist = $('#id_autor').empty();
            opts.each(function () {
                if (rxp.test(this[1])) {
                    optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
                }
            });

        });
    });
</script>
<div id="wrapper_1">
    <div id="container_1">
<div class="row2">
    <div class="nine3 columns">
        <div id="centersectiontitle">
            <div class="twelve columns">
                <div class="sidebartitle"><h3>
                <?php
                    echo $this->titulo;
                ?>
                </h3>
            </div>
        </div>
    </div>
<div class="twelve columns">
<a href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id; ?>">
    <i class="icon-arrow-left"></i>
     Regresar</a>

    <?php
echo '<br>';echo '<br>';
                $form = $this->form;
                $form->prepare();

                $form->setAttributes(array('action'=> $this->url.'/application/libroshv/index/'.$this->id."/".$this->id2,
                                        'method'=>'post'));
                echo $this->form()->openTag($form);
                echo '<p>';
                echo $this->formlabel($form->get('titulo_libro'));
                echo $this->formelement($form->get('titulo_libro'));
                
                echo "</div>";
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('tipo_libro'));
                echo $this->formelement($form->get('tipo_libro'));

                echo '<p>';
                echo $this->formlabel($form->get('ano'));
                echo $this->formelement($form->get('ano'));
                echo '<p>';
                echo $this->formlabel($form->get('pais'));
                echo $this->formelement($form->get('pais'));
                echo '<p>';
                echo $this->formlabel($form->get('editorial'));
                echo $this->formelement($form->get('editorial'));
                echo '<p>';
                echo $this->formlabel($form->get('isbn'));
                echo $this->formelement($form->get('isbn'));
                echo '<p>';
                echo $this->formlabel($form->get('filtro_autor'));
                echo $this->formelement($form->get('filtro_autor'));
                echo '<p>';
                echo $this->formlabel($form->get('id_autor'));
                echo $this->formelement($form->get('id_autor'));
                echo '<p>';
                echo $this->formelement($form->get('submit'));
                echo "</div>";
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('num_paginas'));
                echo $this->formelement($form->get('num_paginas'));

                echo '<p>';
                echo $this->formlabel($form->get('mes'));
                echo $this->formelement($form->get('mes'));
                echo '<p>';
                echo $this->formlabel($form->get('ciudad'));
                echo $this->formelement($form->get('ciudad'));
                echo '<p>';
                echo $this->formlabel($form->get('edicion'));
                echo $this->formelement($form->get('edicion'));
                echo '<p>';
                echo $this->formlabel($form->get('serie'));
                echo $this->formelement($form->get('serie'));
                echo '<p>';
                echo $this->formlabel($form->get('medio_divulgacion'));
                echo $this->formelement($form->get('medio_divulgacion'));    
                echo '<p>';
                echo $this->formlabel($form->get('image-file'));
                echo $this->formelement($form->get('image-file'));
                echo $this->form()->closeTag($form);
                ?>
                <br>


                <?php
                

                ?>

</div></div></div>