<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<center>
					<h6>Eliminar el registro?</h6>
					<a class="btn"
						href="<?php echo $this->basePath() ?>/application/editargrupoinv/eliminar/<?php echo $this->datos;?>">Eliminar
						Registro</a> <a class="btn"
						href="<?php echo $this->basePath() ?>/application/grupoinv/index">Cancelar</a>

					<br>
					<br>
			
			</div>
		</div>
	</div>
</div>



