<style>
	.filter-group input[type="text"],select{
		width: 100%;
	}
	.filter-group {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-group-left {float: left;}
	.filter-group-right {float:right;}
	.filter-group .btn {width: 275px;}
	.filter-group .dropdown {display: inline;}
	.filter-group .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-group">
		<div class="filter-group-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-group-right">
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/noticias/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php								
						$form = $this->form;
						$form->prepare ();
						$form->setAttributes(array(
							'action' => $this->url.'/application/noticias/index',
							'method' => 'post' 
						));
						echo $this->form ()->openTag ( $form );
						echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
						echo $this->formlabel($form->get('titulo'));
						echo $this->formelement($form->get('titulo'));
						echo $this->formlabel($form->get('noticia'));
						echo $this->formelement($form->get('noticia'));
						echo $this->formelement ( $form->get ( 'submit' ) );
 						echo $this->form ()->closeTag ( $form );
 						?>
					</div>						
				</div>
			</div>
			<?php if($this->id_user!="0"){?>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/crearnoticias/index">Crear Noticia</a>
			<?php } ?>
		</div>
	</div>
</div>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
		<?php				
echo '<table class="table" style="width: 100%; max-width: 100%;">';
echo '<thead>';
				echo '<th>Título</th>';
				echo '<th>Noticia</th>';
				echo '<th>Fecha</th>';
				echo '<th>Estado</th>';
				echo '<th>Imagen</th>';
				echo '<th>Editar</th>';

				if($this->menu!="2"){
					echo '<th>Eliminar</th>';
				}
				
echo '</thead>';
echo '<tbody>';
echo '</thead>';
echo '<tbody>';
				foreach ($this->datos as $dato){
				echo '<tr>';
				echo '<td>';
				echo $dato["titulo"];
				echo'</td>';
				echo '<td>';
				echo $dato["noticia"];
				echo'</td>';
				echo '<td>';
				echo $dato["fecha_inicio"];
				echo'</td>';
				echo '<td>';
				if ($dato["estado"]=='A' || $dato["estado"]=='a' ){
						echo 'Activo';
					};
				if ($dato["estado"]=='I' || $dato["estado"]=='i' ){
						echo 'Inactivo';
					};
				echo'</td>';
				if($this->id_user!="0"){
					echo '<td>';
					?>
						<a class="btn" href="<?php echo $this->basePath() ?>/application/cargarimagen/index/<?php echo $dato["id_noticia"];?>"><i class="fa fa-upload"></i></a>
					<?php
					echo'</td>';
					echo '<td>';
					?>
						<a class="btn" href="<?php echo $this->basePath() ?>/application/editarnoticias/index/<?php echo $dato["id_noticia"];?>"><i class="fa fa-pencil"></i></a>
					<?php
					echo'</td>';
					if($this->menu!="2"){
						echo '<td>';
						?>
							<a class="btn" href="<?php echo $this->basePath() ?>/application/noticias/eliminar/<?php echo $dato["id_noticia"];?>"><i class="fa fa-trash"></i></a>
						<?php
						echo'</td>';
					}
					
				}
				echo '</tr>';
				}
				
				echo '</tr>';
				echo '</table>';
					if(count($this->datos) == 0){
						if($this->data["titulo"]){
							echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos noticias con este título</h3></div>';
						}else if($this->data["noticia"]){
							echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos noticias con esta descripción</h3></div>';
						}
					}
				?>
	</div>
</div>
