<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<br> <a
					href="<?php echo $this->basePath() ?>/application/aprobacionm/index/<?php echo $this->id2; ?>">
					<i class="icon-arrow-left"></i> Regresar
				</a> <br> <br>
				<div class="seven columns">

				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/archivosinformem/index/' . $this->id.'/'. $this->id2,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo '<p>';
    echo $this->formlabel($form->get('image-file'));
    echo $this->formelement($form->get('image-file'));
    echo '<p>';
    echo '</br>';
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>
</div>
			</div>
		</div>
	</div>
</div>