<style>
    .filter-tipo input[type="text"],select{
        width: 100%;
    }
    .filter-tipo {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-tipo-left {float: left;}
    .filter-tipo-right {float:right;}
    .filter-tipo .btn {width: 275px;}
    .filter-tipo .dropdown {display: inline;}
    .filter-tipo .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
    .dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .content-form-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .content-form-inner { border: 0; border-radius: 8px; }
    .content-form-inner .btn {width: 275px;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100 noshadow">
    <div class="content-form-inner">
        <?php
        echo '<div class="twelve columns" style="padding-bottom: 10px;">';
        echo '<h3>'.$this->titulo.'</h3>';
        echo '</div>';
        
        $form = $this->form;
        $form->prepare();
    
        $form->setAttributes(array(
            'action' => $this->url . '/application/tipovalores/index',
            'method' => 'post'
        ));
        echo $this->form()->openTag($form);

        echo '<div class="four columns">';
        echo '<div class="form-group">';
        echo $this->formlabel($form->get('descripcion'));
        echo $this->formelement($form->get('descripcion'));
        echo '</div>';
        echo '</div>';

        echo '<div class="four columns">';
        echo '<div class="form-group">';
        echo $this->formlabel($form->get('activo'));
        echo $this->formelement($form->get('activo'));
        echo '</div>';
        echo '</div>';

        echo '<div class="four columns">';
        echo '<div class="form-group">';
        echo $this->formlabel($form->get('id_tipo_valor_padre'));
        echo $this->formelement($form->get('id_tipo_valor_padre'));
        echo '</div>';
        echo '</div>';
        
        echo '<div style="float: right; padding: 0 15px 5px 5px;">';
        echo $this->formelement($form->get('submit'));
        echo '<a class="btn" style="margin-left: 10px;" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>';
        echo '</div>';
        
        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>
<div class="col col100 noshadow">
    <div style='overflow-y:auto; max-height:4000px; width: 100%;'>
        <table class="table" style="width: 100%; max-width: 100%;">
            <thead>
                <tr>
                    <th style="width:5%">Descripción</th>
                    <th style="width:5%">Activo</th>
                    <th style="width:5%">Valor</th>
                    <th style="width:5%">Acciones</th>            
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->datos as $dato) { ?>
                <tr>
                    <td><?php echo $dato ["descripcion"] ?></td>
                    <td>
                        <?php
                        if ($dato["activo"] == 'S' || $dato["activo"] == 's') {
                            echo 'Si';
                        }
                        else if ($dato["activo"] == 'N' || $dato["activo"] == 'n') {
                            echo 'No';
                        } ?>
                    </td>
                    <td>
                        <?php
                        foreach ($this->datos as $d) {
                            if ($dato["id_tipo_valor_padre"] == $d["id_tipo_valor"]) {
                                echo $d["descripcion"];
                            }
                        } ?>
                    </td>
                    <td>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarvalflex/index/<?php echo $dato["id_tipo_valor"];?>"><i class="fa fa-plus"></i></a>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/editartipovalores/index/<?php echo $dato["id_tipo_valor"];?>"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
