<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('tipo_documento'));
echo $this->formelement($form->get('tipo_documento'));

echo '<p>';
echo $this->formlabel($form->get('apellidos'));
echo $this->formelement($form->get('apellidos'));

echo '<p>';
echo $this->formlabel($form->get('profesion'));
echo $this->formelement($form->get('profesion'));

echo '<p>';
echo $this->formlabel($form->get('telefono'));
echo $this->formelement($form->get('telefono'));

echo '<p>';
echo $this->formlabel($form->get('horas'));
echo $this->formelement($form->get('horas'));


echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('documento'));
echo $this->formelement($form->get('documento'));

echo '<p>';
echo $this->formlabel($form->get('nombres'));
echo $this->formelement($form->get('nombres'));

echo '<p>';
echo $this->formlabel($form->get('intitucion'));
echo $this->formelement($form->get('intitucion'));

echo '<p>';
echo $this->formlabel($form->get('email'));
echo $this->formelement($form->get('email'));

echo '<p>';
echo $this->formelement($form->get('submit'));
echo '</div>';

echo '<div>';

echo '</div>';

echo $this->form()->closeTag($form);
?>				


</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>