<style>
	.filter-group input[type="text"],select{
		width: 100%;
	}
	.filter-group {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-group-left {float: left;}
	.filter-group-right {float:right;}
	.filter-group .btn {width: 275px;}
	.filter-group .dropdown {display: inline;}
	.filter-group .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-group">
		<div class="filter-group-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-group-right">
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/foro/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php								
						$form = $this->form;
						$form->prepare ();
						$form->setAttributes(array(
							'action' => $this->url.'/application/foro/index',
							'method' => 'post' 
						));
						echo $this->form ()->openTag ( $form );
						echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
						echo $this->formlabel($form->get('titulo'));
						echo $this->formelement($form->get('titulo'));
						echo $this->formlabel($form->get('mensaje'));
						echo $this->formelement($form->get('mensaje'));
						echo $this->formelement ( $form->get ( 'submit' ) );
 						echo $this->form ()->closeTag ( $form );
 						?>
					</div>						
				</div>
			</div>
			<?php if($this->id_user!="0"){?>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/crearforo/index">Crear Foro</a>
			<?php } ?>
		</div>
	</div>
</div>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
		<?php				
echo '<table class="table" style="width: 100%; max-width: 100%;">';
echo '<thead>';
				echo '<th>Tema</th>';
				echo '<th>Mensaje</th>';
				echo '<th>Última Respuesta</th>';
				echo '<th>Respuestas</th>';
				echo '<th>Editar</th>';
				echo '<th>Eliminar</th>';
echo '</thead>';
echo '<tbody>';
				foreach ($this->datos as $dato){
				echo '<tr>';
				echo '<td>';
				if($dato["estado"]=='D' || $this->menu==0){
					echo $dato["titulo"]; 
				}else{
				?>
					<a href="<?php echo $this->basePath() ?>/application/foro/ver/<?php echo $dato["id_foro"];?>">  <?php echo $dato["titulo"]; ?> </a>
				<?php
				}
				echo '<td>';
				echo $dato["mensaje"];
				echo'</td>';
				echo'</td>';
				echo '<td>';
				echo $dato["ult_respuesta"];
				echo'</td>';
				echo '<td>';
				echo $dato["respuestas"];
				echo'</td>';

				echo '<td>';
				?><?php if($this->menu==1){ ?>
					<a class="btn" href="<?php echo $this->basePath() ?>/application/editarforo/index/<?php echo $dato["id_foro"];?>"><i class="fa fa-pencil"></i></a>
				<?php }
				echo'</td>';
				echo '<td>';
				?><?php if($this->menu==1){ ?>
					<a class="btn" href="<?php echo $this->basePath() ?>/application/foro/eliminar/<?php echo $dato["id_foro"];?>"><i class="fa fa-trash"></i></a>
				<?php }
				echo'</td>';
				echo '</tr>';
				}
				
				echo '</tr>';
				echo '</table>';
				if(count($this->datos) == 0){
		            if($this->data["titulo"]){
		                echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos foros con este Título</h3></div>';
		            }else if($this->data["mensaje"]){
		                echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos foros con este Mensaje</h3></div>';
		            }
		        }

				?>
	</div>
</div>