<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center><br>
<h6>¿Desea aprobar la propuesta de investigación?</h6>

<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionrequi/aprobarproy/<?php echo $this->datos;?>/<?php echo $this->id2;?>/<?php echo $this->id3;?>">Aprobar propuesta</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionrequi/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


