<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>¿Desea aprobar el monitor?</h6>

<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionrequi/aprobarproym/<?php echo $this->datos;?>/<?php echo $this->id2;?>/1">Aprobar</a>
<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionrequi/aprobarproym/<?php echo $this->datos;?>/<?php echo $this->id2;?>/0">No aprobar</a>
<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionrequi/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


