<? include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<?php 
if($this->id3==1){
?>
<a href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $this->id; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>
<?php
}
?>
<div class="seven columns">
<br>
				<?php



	
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/gestionrequi/asignar/'.$this->id.'/'.$this->id2,
										'method'=>'post'));
				echo $this->form()->openTag($form);

				echo $this->formlabel($form->get('codigo'));
				echo $this->formelement($form->get('codigo'));

				echo '<p>';				
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


				<?php
				

				?>

</div></div></div>