<style>
	.filter-audi select,.filter-audi input[type="date"],.filter-audi #someinput {
		width: 100% !important;
	}
	.filter-audi {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-audi-left {float: left;}
	.filter-audi-right {float:right;}
	.filter-audi .btn {width: 275px;}
	.filter-audi .dropdown {display: inline;}
	.filter-audi .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.dropdown-menu-right {left:-140px !important;}
</style>
<script>
$(function () {
    var opts = $('#usuario option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput').keyup(function () {
        var rxp = new RegExp($('#someinput').val(), 'i');
        var optlist = $('#usuario').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });
    });

});
</script>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-audi">
		<div class="filter-audi-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-audi-right">
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/auditoria/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>		
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php
						$form = $this->form;
						$form->prepare();
						echo $this->form()->openTag($form);
						echo $this->formlabel($form->get('usuario'));
						echo '<input id="someinput">';				
						echo $this->formelement($form->get('usuario'));
						echo $this->formlabel($form->get('fecha_ingreso'));
						echo $this->formelement($form->get('fecha_ingreso'));
						echo $this->formlabel($form->get('fecha_salida'));
						echo $this->formelement($form->get('fecha_salida'));
						echo $this->formelement($form->get('submit'));
						echo $this->form()->closeTag($form);
						?>
					</div>
				</div>
			</div>
			<?php
			$c = '0';
			$a = 'none';
			foreach ($this->datos as $dato){
				$c = $c.",".$dato["id_auditoria"];
			}
			if ($this->traer == 1) {
				$c = str_replace('0,', '', $c);
				$a = 'cursor';
			}
			else {
				$c = 0;
				$a = 'none';
			}
			?>
			<a class="btn" style="pointer-events: <?php echo $a; ?>;" href="<?php echo $this->basePath() ?>/application/auditoria/report/<?php echo $c; ?>"><i class="fa fa-bar-chart"></i> Reporte</a>		
		</div>
	</div>
</div>
<?php if($this->traer==1){ ?>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
		<table class="table" style="width: 100%; max-width: 100%;">
			<thead>
				<tr>
					<th style="width:5%;">Usuario</th>
					<th style="width:5%;">Fecha Ingreso</th>
					<th style="width:5%;">Fecha Salida</th>
					<th style="width:5%;">Ip Terminal</th>
					<th style="width:5%;">Evento</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->datos as $dato){ ?>
				<tr>
					<td><?php echo $dato["nombre_completo"]; ?></td>
					<td><?php echo $dato["fecha_ingreso"]; ?></td>
					<td><?php echo $dato["fecha_salida"]; ?></td>
					<td><?php echo $dato["ip_terminal"]; ?></td>
					<td><a class="btn" href="<?php echo $this->basePath() ?>/application/auditoriadet/index/<?php echo $dato["id_auditoria"];?>"><i class="fa fa-eye"></i></a></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php } ?>

