<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }

    .btn {
        color: white !important;
    }

    .alineadoDerecha {
        float: right;
    }

    .nopadding {
        padding: 0;
        margin: 0;
    }  
    
    td,th {
        padding: 0;
        font-size: 10px;
    }
    .filter-redes {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-redes-left {float: left;}
    .filter-redes-right {float: right;}
    .filter-redes .btn {width: 275px;}
    .filter-redes-right div.btn {max-width: 230px !important;width: 230px;}
</style>
<div class="edit-slide transition">
    <div class="close-edit" id="titulo_top"><i class="fa fa-times" aria-hidden="true"></i></div>
    <div class="content-edit-slide">
        <div class="titulo_top"><h3><?php echo $this->titulo; ?></h3></div>
        <a href="<?php echo $this->basePath() ?>/application/redesinv/index"><i class="fa fa-arrow-left"></i> Regresar</a><br><br>
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttributes(array(
            'action' => $this->url . '/application/editarredinv/index/' . $this->id,
            'method' => 'post'
        ));
        echo $this->form()->openTag($form);
        echo '<h6>'.$this->flashMessenger()->render().'</h6>';
        echo $this->formlabel($form->get('nombre_red'));
        echo $this->formelement($form->get('nombre_red'));
        echo $this->formlabel($form->get('id_coordinador_1')); 
        echo $this->formelement($form->get('id_coordinador_1'));
        echo $this->formelement($form->get('coordinador_1'));
        echo $this->formlabel($form->get('id_coordinador_2'));
        echo $this->formelement($form->get('id_coordinador_2'));
        echo $this->formelement($form->get('coordinador_2'));
        echo $this->formlabel($form->get('estado_red'));
        echo $this->formelement($form->get('estado_red'));
        echo $this->formlabel($form->get('codigo'));
        echo $this->formelement($form->get('codigo'));
        echo '<h4>Datos generales de la red</h4>';
        echo $this->formlabel($form->get('vision'));
        echo $this->formelement($form->get('vision'));
        echo $this->formlabel($form->get('mision'));
        echo $this->formelement($form->get('mision'));
        echo $this->formlabel($form->get('objetivos'));
        echo $this->formelement($form->get('objetivos'));
        echo $this->formlabel($form->get('antecedentes'));
        echo $this->formelement($form->get('antecedentes'));
        echo $this->formlabel($form->get('justificacion'));
        echo $this->formelement($form->get('justificacion'));
        echo $this->formlabel($form->get('descripcion'));
        echo $this->formelement($form->get('descripcion'));
        echo $this->formlabel($form->get('lineas_investigacion'));
        echo $this->formelement($form->get('lineas_investigacion'));
        echo $this->formlabel($form->get('instituciones_aliadas'));
        echo $this->formelement($form->get('instituciones_aliadas'));
        echo $this->formlabel($form->get('socios'));
        echo $this->formelement($form->get('socios'));
        echo $this->formlabel($form->get('aliados'));
        echo $this->formelement($form->get('aliados'));
        echo '<div class="content-edit-slide-button">';            
        echo '<div class="col">';
        echo $this->formelement($form->get('submit'));
        echo '</div>';
        echo '<div class="col">';
        ?>        
        <a class="btn1 cancel-edit">Cancelar</a>
        <?php
        echo '</div>';
        echo '</div>';
        echo $this->form()->closeTag($form);        
        ?>
        <a href="#titulo_top">Ir arriba</a>
    </div>
</div>
<?php 
include("public/menu.php");
require_once("public/rutas.php");
?>
<link rel="stylesheet" href="<?php echo $GLOBALS["ruta_servidor"] . 'css/estilos_arriba/estilos_arriba.css'; ?>">
<link rel="stylesheet" href="<?php echo $GLOBALS["ruta_servidor"] . 'js/ui/jquery-ui.min.css'; ?>">
<link rel="stylesheet" href="<?php echo $GLOBALS["ruta_servidor"] . 'js/ui/jquery-ui.theme.min.css'; ?>">
<link rel="stylesheet" href="<?php echo $GLOBALS["ruta_servidor"] . 'js/ui/jquery-ui.structure.min.css'; ?>">
<div class="col col100">
    <div class="filter-redes">
        <div class="filter-redes-left">
            <a class="btn" href="<?php echo $this->basePath() ?>/application/redesinv/index"><i class="icon-arrow-left"></i> Regresar</a>
        </div>            
        <div class="filter-redes-right">
            <div class="btn transition pointer redes_edit"><i class="fa fa-pencil" style="margin-right: 5px;"></i>Editar datos básicos red</div>
        </div>
    </div>    
</div>
<div class="col col100 noshadow">
    <div class="col col100 nopadding">
        <div id="tabs">
            <ul>
                <li><a href="#Equipo">Equipo directivo o Estructura organizacional</a></li>
                <li><a href="#Contacto">Contacto</a></li>
                <li><a href="#Miembros">Miembros de la red de la UPN</a></li>
                <li><a href="#Participacion">Participación en eventos</a></li>
                <li><a href="#Grupos">Grupos de investigación asociados a la red de la UPN</a></li>
                <li><a href="#Servicios">Servicios</a></li>
                <li><a href="#Articulos">Artículos</a></li>
                <li><a href="#Libros">Libros</a></li>
                <li><a href="#Capitulos">Capítulos de libros</a></li>
                <li><a href="#Otras">Otras producciones de investigación</a></li>
                <li><a href="#Otros">Otros documentos bibliográficos</a></li>
                <li><a href="#Proyectos">Proyectos de investigación externos</a></li>
                <li><a href="#Proyectos_internos">Proyectos de investigación internos</a></li>
                <li><a href="#Material">Material colaborativo gratuito</a></li>
                <li><a href="#Identificadores">Identificadores de Investigación</a></li>
                <li><a href="#Divulgacion">Divulgación</a></li>
                <li><a href="#Formacion">Formación</a></li>
            </ul>
            <div id="Equipo">
                <legend>Equipo directivo o Estructura organizacional</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/equipodirectivo/index/<?php echo $id;?>">Agregar</a><br> <br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 20%;'>Nombre del cargo o rol</th>";
                echo "<th style='width: 20%;'>Nombre de la persona</th>";
                echo "<th style='width: 20%;'>Institución</th>";
                echo "<th style='width: 20%;'>País</th>";
                echo "<th style='width: 10%;'>Descargar</th>";
                echo '<th style="width: 10%;">Ver/Editar</th>';
                echo "<th style='width: 10%;'>Eliminar</th>";
                echo '</thead>';
                echo '<tbody>';
                foreach ($this->equipodirectivo as $int) {
                    echo '<tr>';
                    echo '<td>';
                    echo $int["cargo"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["nombre"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["institucion"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["pais"];
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                        if($int["archivo"]!=""){
                            ?>    
                                <a class="btn" href="<?php echo $this->basePath()?>/application/equipodirectivo/bajar/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-download"></i></a>
                            <?php
                        }
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                    ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/equipodirectivo/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                    <?php
                    echo '</td>';                    
                    echo '<td style="text-align:center;">';
                    ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/equipodirectivo/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                    <?php
                    echo '</td>';
                    echo '</tr>';
                }
                echo '</tbody>';
                echo '</table>';
                echo '</div>';
                ?>
            </div>
            <div id="Contacto">
                <legend>Contacto</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/contactored/index/<?php echo $id;?>">Agregar</a><br><br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 13%;'>Correo electrónico</th>";
                echo "<th style='width: 10%;'>Página Web</th>";
                echo "<th style='width: 8%;'>Teléfono 1</th>";
                echo "<th style='width: 8%;'>Teléfono 2</th>";
                echo "<th style='width: 10%;'>Red social 1</th>";
                echo "<th style='width: 10%;'>Red social 2</th>";
                echo "<th style='width: 10%;'>Red social 3</th>";
                echo "<th style='width: 15%;'>Otros tipos de contacto</th>";
                echo "<th style='width: 10%;'>Descargar</th>";
                echo '<th style="width: 8%;">Ver/Editar</th>';
                echo "<th style='width: 8%;'>Eliminar</th>";
                echo '<tr>';
                foreach ($this->contactored as $int) {
                    echo '<tr>';
                    echo '<td>';
                    echo $int["correo_electronico"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["pagina_web"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["telefono_2"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["telefono_2"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["redsocial_1"];
                    echo '</td>';                    
                    echo '<td>';
                    echo $int["redsocial_2"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["redsocial_3"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["otro_contacto"];
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                        if($int["archivo"]!=""){
                            ?>    
                                <a class="btn" href="<?php echo $this->basePath()?>/application/contactored/bajar/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-download"></i></a>
                            <?php
                        }
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/contactored/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                <?php
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/contactored/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                <?php
                    echo '</td>';
                    echo '</tr>';
                }
                echo '</tr>';
                echo '</table>';
                echo '</div>';
                ?>
            </div>
            <div id="Miembros">
                <legend>Miembros de la red de la UPN</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/integrantesred/index/<?php echo $id;?>">Agregar</a><br><br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 20%;'>Nombre del miembro</th>";
                echo "<th style='width: 29%;'>Tipo de vinculación</th>";
                echo "<th style='width: 29%;'>Fecha de vinculación</th>";
                echo "<th style='width: 20%;'>Fecha fin de vinculación</th>";
                echo '<th style="width: 10%;">Buscar productos</th>';
                echo "<th style='width: 10%;'>Descargar</th>";
                echo "<th style='width: 20%;'>Editar</th>";
                echo '<tr>';

                foreach ($this->integrantesred as $int) {
                    echo '<tr>';
                    echo '<td>';
                    foreach ($this->usuarios as $usuario) {
                        if($usuario["id_usuario"]==$int["id_integrantered"]){
                            echo $usuario["primer_nombre"]." ".$usuario["segundo_nombre"]." ".$usuario["primer_apellido"]." ".$usuario["segundo_apellido"];    
                        }
                            
                    }
                    echo '</td>';
                    echo '<td>';
                    foreach ($this->vf2 as $val) {
                        if($val["id_valor_flexible"]==$int["tipo_vinculacion"]){
                            echo $val["descripcion_valor"];
                        }
                    }
                    echo '</td>';
                    echo '<td>';
                    echo $int["fecha_vinculacion"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["fin_vinculacion"];                        
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                        ?>
                            <a class="btn"
                                            href="<?php echo $this->basePath() ?>/application/hvinvestigador/index/<?php echo  $int["id_integrantered"]; ?>/1/<?php echo $id;?>/2"><i class="fa fa-search"></i></a>
                        <?php
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                        if($int["archivo"]!=""){
                            ?>    
                                <a class="btn" href="<?php echo $this->basePath()?>/application/integrantesred/bajar/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-download"></i></a>
                            <?php
                        }
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                    ?>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/integrantesred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                    <?php
                    echo '</td>';
                    echo '</tr>';
                }
                echo '</tr>';
                echo '</table>';
                echo '</div>';
                ?>
            </div>
            <div id="Participacion">
                <legend>Participación en eventos</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/participacioneventosred/index/<?php echo $id;?>">Agregar</a>
                <br> <br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 20%;'>Nombre del evento</th>";
                echo "<th style='width: 15%;'>Lugar del evento</th>";
                echo "<th style='width: 15%;'>Tipo de participación</th>";
                echo "<th style='width: 15%;'>Fecha del evento</th>";
                echo "<th style='width: 15%;'>Descargar archivo</th>";
                echo '<th style="width: 10%;">Ver/Editar</th>';
                echo "<th style='width: 10%;'>Eliminar</th>";
                echo '<tr>';

                foreach ($this->participacioneventos as $int) {
                    echo '<tr>';
                    echo '<td>';
                    echo $int["nombre"];
                    echo '</td>';
                    echo '<td>';
                    echo $int["lugar"];
                    echo '</td>';
                    echo '<td>';
                    foreach ($this->vf2 as $val) {
                        if($val["id_valor_flexible"]==$int["tipo_participacion"]){
                            echo $val["descripcion_valor"];
                        }
                    }
                    echo '</td>';
                    echo '<td>';
                    echo $int["fecha"];
                    echo '</td>';
                    echo '<td>';
                    if($int["archivo"]!=""){
                    ?>    
                    <a class="btn" href="<?php echo $this->basePath()?>/application/participacioneventosred/bajar/<?php echo $int["id_archivo"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                    <?php
                    }else{
                        echo 'Sin archivo';
                    }
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                    ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/participacioneventosred/index/<?php echo $id;?>/<?php echo $int["id_archivo"];?>"><i class="fa fa-pencil"></i></a>
                    <?php
                    echo '</td>';         
                    echo '<td style="text-align:center;">';
                    ?>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/participacioneventosred/del/<?php echo $int["id_archivo"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                    <?php
                    echo '</td>';
                    echo '</tr>';
                }
                echo '</tr>';
                echo '</table>';
                echo '</div>';
                ?>
            </div>
            <div id="Grupos">
                <legend>Grupos de investigación asociados a la red de la UPN</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/gruposred/index/<?php echo $id;?>">Agregar</a><br><br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 30%;'>Nombre del grupo</th>";
                echo "<th style='width: 15%;'>Código</th>";
                echo "<th style='width: 15%;'>Líder</th>";
                echo "<th style='width: 30%;'>Descripción</th>";
                echo "<th style='width: 10%;'>Descargar</th>";
                echo '<th style="width: 5%;">Cargar documento</th>';
                echo "<th style='width: 5%;'>Ver/Editar</th>";
                echo "<th style='width: 5%;'>Eliminar</th>";
                echo '<tr>';
                foreach ($this->gruposred as $int) {
                    foreach ($this->grupostotal as $grupo) {
                        if($int["id_grupo"]==$grupo["id_grupo_inv"]){
                            echo '<tr>';
                            echo '<td>';
                            echo $grupo["nombre_grupo"];
                            echo '</td>';
                            echo '<td>';
                            echo $grupo["cod_grupo"];
                            echo '</td>';
                            echo '<td>';
                            foreach ($this->usuarios as $usuario) {
                                if($usuario["id_usuario"]==$grupo["id_lider"]){
                                    echo $usuario["primer_nombre"] ." ". $usuario["segundo_nombre"] ." ". $usuario["primer_apellido"] ." ". $usuario["segundo_apellido"];    
                                }                                    
                            }
                            echo '</td>';
                            echo '<td>';
                            echo $grupo["descripcion"];
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/gruposred/bajar/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/gruposred/index/<?php echo $id;?>/<?php echo $int["id"];?>/1"><i class="fa fa-plus"></i></a>
                            <?php
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                            <a class="btn" href="<?php echo $this->basePath() ?>/application/gruposred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                            <a class="btn" href="<?php echo $this->basePath() ?>/application/gruposred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                            <?php
                            echo '</td>';
                            echo '</tr>';
                        }
                    }
                }
                echo '</tr>';
                echo '</table>';
                echo '</div>';
            ?>
            </div>
            <div id="Servicios">
                <legend>Servicios</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/serviciosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 40%;'>Servicios que ofrece</th>";
                    echo "<th style='width: 40%;'>Noticias de la red</th>";
                    echo "<th style='width: 10%;'>Descargar</th>";
                    echo '<th style="width: 10%;">Ver/Editar</th>';
                    echo "<th style='width: 10%;'>Eliminar</th>";
                    echo '<tr>';

                    foreach ($this->serviciosred as $int) {
                        echo '<tr>';
                        echo '<td>';
                        echo $int["servicios"];
                        echo '</td>';                        
                        echo '<td>';
                        echo $int["noticias"];
                        echo '</td>';
                        echo '<td style="text-align:center;">';
                        if($int["archivo"]!=""){
                            ?>    
                                <a class="btn" href="<?php echo $this->basePath()?>/application/serviciosred/bajar/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-download"></i></a>
                            <?php
                        }
                        echo '</td>';
                        echo '<td style="text-align:center;">';
                        ?>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/serviciosred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                        <?php
                        echo '</td>';
                        echo '<td style="text-align:center;">';
                        ?>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/serviciosred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                        <?php
                        echo '</td>';
                        echo '</tr>';
                    }
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Articulos">
                <legend>Artículos</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/articulosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 5%;'>Nombre revista</th>";
                    echo "<th style='width: 5%;'>Nombre articulo</th>";
                    echo "<th style='width: 5%;'>Categorización</th>";
                    echo "<th style='width: 4%;'>Año</th>";
                    echo "<th style='width: 4%;'>Mes</th>";
                    echo "<th style='width: 5%;'>País</th>";
                    echo "<th style='width: 5%;'>Ciudad</th>";
                    echo "<th style='width: 5%;'>ISSN/e-ISSN</th>";
                    echo "<th style='width: 5%;'>No. de páginas</th>";
                    echo "<th style='width: 5%;'>Página inicio</th>";
                    echo "<th style='width: 5%;'>Página fin</th>";
                    echo "<th style='width: 5%;'>Fascículo</th>";
                    echo "<th style='width: 5%;'>Volúmen</th>";
                    echo "<th style='width: 5%;'>No. de serie</th>";
                    echo "<th style='width: 11%;'>Autor(es)</th>";
                    echo "<th style='width: 6%;'>Descargar archivo</th>";
                    echo "<th style='width: 5%;'>Agregar autor</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar</th>";
                    echo '<tr>';

                    foreach ($this->articulos as $int) {
                        echo '<tr>';
                            echo '<td>';
                            echo $int["nombre_revista"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["nombre_articulo"];
                            echo '</td>';

                            echo '<td>';
                            foreach ($this->vf2 as $val) {
                                if($val["id_valor_flexible"]==$int["categoria"]){
                                    echo $val["descripcion_valor"];
                                }
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["ano"];
                            echo '</td>';
                        
                            echo '<td>';
                            switch ($int["mes"]) {
                                case 1:
                                    echo "Enero";
                                    break;
                                case 2:
                                    echo "Febrero";
                                    break;
                                case 3:
                                    echo "Marzo";
                                    break;
                                case 4:
                                    echo "Abril";
                                    break;
                                case 5:
                                    echo "Mayo";
                                    break;
                                case 6:
                                    echo "Junio";
                                    break;
                                case 7:
                                    echo "Julio";
                                    break;
                                case 8:
                                    echo "Agosto";
                                    break;
                                case 9:
                                    echo "Septiembre";
                                    break;
                                case 10:
                                    echo "Octubre";
                                    break;
                                case 11:
                                    echo "Noviembre";
                                    break;
                                case 12:
                                    echo "Diciembre";
                                    break;
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["pais"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["ciudad"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["issn"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["paginas"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["pagina_inicio"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["pagina_fin"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["fasciculo"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["volumen"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["serie"];
                            echo '</td>';

                            echo '<td>';
                            $autores="";
                            foreach ($this->usuarios as $usa) {
                                if ($usa["id_usuario"] == $int["id_autor"]) {
                                    $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                }
                            }
                            foreach ($this->autoresred as $autor) {
                                if($autor["seccion"]=="1" && $autor["id_objeto"]==$int["id"]){
                                    foreach ($this->usuarios as $usuario) {
                                        if($usuario["id_usuario"]==$autor["id_usuario"]){
                                            $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
                                        }    
                                    }
                                }
                            }
                            echo $autores;
                            echo '</td>';
                            
                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/articulosred/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';

                            echo '<td>';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/1"><i class="fa fa-plus"></i></a>

                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/articulosred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/articulosred/del/<?php echo $int["id"];?>/<?php echo $id;?>/1"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                    //Articulos usuario
                    foreach($this->dataDocumentos as $documento){
                        if($documento["tipo_documento"]=="articulo"){
                            foreach ($this->Articuloshv as $art) {
                                if($art["id_gi_articulo"] == $documento["id_documento"]){
                                    echo '<tr>';
                                    echo '<td>';
                                    echo $art["nombre_revista"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["nombre_articulo"];
                                    echo '</td>';
                                    echo '<td>';
                                    foreach ($this->vf2 as $vl) {
                                        if ($vl["id_valor_flexible"] == $art["categoria"]) {
                                            echo $vl["descripcion_valor"];
                                        }
                                    }
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["ano"];
                                    echo '</td>';
                                    echo '<td>';
                                    switch ($art["mes"]) {
                                            case 1:
                                                echo "Enero";
                                                break;
                                            case 2:
                                                echo "Febrero";
                                                break;
                                            case 3:
                                                echo "Marzo";
                                                break;
                                            case 4:
                                                echo "Abril";
                                                break;
                                            case 5:
                                                echo "Mayo";
                                                break;
                                            case 6:
                                                echo "Junio";
                                                break;
                                            case 7:
                                                echo "Julio";
                                                break;
                                            case 8:
                                                echo "Agosto";
                                                break;
                                            case 9:
                                                echo "Septiembre";
                                                break;
                                            case 10:
                                                echo "Octubre";
                                                break;
                                            case 11:
                                                echo "Noviembre";
                                                break;
                                            case 12:
                                                echo "Diciembre";
                                                break;
                                        }
                                    echo '</td>';
                                    echo '<td>';
                                    foreach ($this->vf2 as $vl) {
                                        if ($vl["id_valor_flexible"] == $art["id_pais"]) {
                                            $art["id_pais"] = $vl["descripcion_valor"];
                                        }
                                    }
                                    echo $art["id_pais"];
                                    echo '</td>';
                                    echo '<td>';
                                    foreach ($this->vf2 as $vl) {
                                        if ($vl["id_valor_flexible"] == $art["id_ciudad"]) {
                                            $art["id_pais"] = $vl["descripcion_valor"];
                                        }
                                    }
                                    echo $art["id_ciudad"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["issn"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["num_paginas"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["pagina_inicio"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["pagina_fin"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["fasciculo"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["volumen"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $art["serie"];
                                    echo '</td>';
                                    $autorAux="";
                                    foreach ($this->usuarios as $usa) {
                                        if ($usa["id_usuario"] == $art["id_autor"]) {
                                            
                                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                        }
                                    }
                                    foreach ($this->autoresred as $aut) {
                                        if ($art["id_gi_articulo"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Articuloshv') {
                                            foreach ($this->usuarios as $ua) {
                                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                }
                                            }
                                        }
                                    }
                                    echo '<td>';
                                    echo $autorAux;
                                    echo '</td>';
                                    echo '<td>';
                                        if($art["archivo"]!=""){
                                            ?>    
                                                <a class="btn" href="<?php echo $this->basePath()?>/application/articuloshv/bajar/<?php echo $art["id_gi_articulo"];?>/<?php echo $art["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                    <?php    }
                                    echo '</td>';  
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                    }//Articulos usuario  
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Libros">
                <legend>Libros</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/librosred/index/<?php echo $id;?>">Agregar</a>
                    <br> <br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 8%;'>Título del libro</th>";
                    echo "<th style='width: 7%;'>Tipo de libro</th>";
                    echo "<th style='width: 4%;'>No. de Páginas</th>";
                    echo "<th style='width: 4%;'>Año</th>";
                    echo "<th style='width: 4%;'>Mes</th>";
                    echo "<th style='width: 5%;'>País de publicación</th>";
                    echo "<th style='width: 5%;'>Ciudad de publicación</th>";
                    echo "<th style='width: 5%;'>Serie</th>";
                    echo "<th style='width: 7%;'>Editorial</th>";
                    echo "<th style='width: 7%;'>No. de Edición</th>";
                    echo "<th style='width: 8%;'>ISBN ó e-ISBN</th>";
                    echo "<th style='width: 8%;'>Medio de divulgación</th>";
                    echo "<th style='width: 9%;'>Autor(es)</th>";
                    echo "<th style='width: 6%;'>Descargar archivo</th>";
                    echo "<th style='width: 5%;'>Agregar autor</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar</th>";
                    echo '<tr>';

                    foreach ($this->libros as $int) {
                        echo '<tr>';
                            echo '<td>';
                            echo $int["titulo"];
                            echo '</td>';

                            echo '<td>';
                                foreach ($this->vf2 as $vl) {
                                    if ($vl["id_valor_flexible"] == $int["tipo_libro"]) {
                                        echo $vl["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["paginas"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["ano"];
                            echo '</td>';
                        
                            echo '<td>';
                            switch ($int["mes"]) {
                                case 1:
                                    echo "Enero";
                                    break;
                                case 2:
                                    echo "Febrero";
                                    break;
                                case 3:
                                    echo "Marzo";
                                    break;
                                case 4:
                                    echo "Abril";
                                    break;
                                case 5:
                                    echo "Mayo";
                                    break;
                                case 6:
                                    echo "Junio";
                                    break;
                                case 7:
                                    echo "Julio";
                                    break;
                                case 8:
                                    echo "Agosto";
                                    break;
                                case 9:
                                    echo "Septiembre";
                                    break;
                                case 10:
                                    echo "Octubre";
                                    break;
                                case 11:
                                    echo "Noviembre";
                                    break;
                                case 12:
                                    echo "Diciembre";
                                    break;
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["pais"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["ciudad"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["serie"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["editorial"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["edicion"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["isbn"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["medio_divulgacion"];
                            echo '</td>';

                            echo '<td>';
                            $autores="";
                            foreach ($this->usuarios as $usa) {
                                if ($usa["id_usuario"] == $int["id_autor"]) {
                                    $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                }
                            }
                            foreach ($this->autoresred as $autor) {
                                if($autor["seccion"]=="2" && $autor["id_objeto"]==$int["id"]){
                                    foreach ($this->usuarios as $usuario) {
                                        if($usuario["id_usuario"]==$autor["id_usuario"]){
                                            $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
                                        }    
                                    }
                                }
                            }
                            echo $autores;
                            echo '</td>';

                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/librosred/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            
                            echo '<td>';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/2"><i class="fa fa-plus"></i></a>

                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/librosred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                    ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/librosred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                    <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                    //Libros usuario
                    foreach($this->dataDocumentos as $documento){
                        if($documento["tipo_documento"]=="libro"){
                            foreach ($this->libroshv as $lib) {
                                if($lib["id_gi_libro"] == $documento["id_documento"]){
                                    echo '<tr>';
                                    echo '<td>';
                                    echo $lib["titulo_libro"];
                                    echo '</td>';

                                    echo '<td>';
                                        foreach ($this->vf2 as $vl) {
                                            if ($vl["id_valor_flexible"] == $lib["tipo_libro"]) {
                                                echo $vl["descripcion_valor"];
                                            }
                                        }
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["num_paginas"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["ano"];
                                    echo '</td>';
                                    echo '<td>';
                                    switch ($lib["mes"]) {
                                            case 1:
                                                echo "Enero";
                                                break;
                                            case 2:
                                                echo "Febrero";
                                                break;
                                            case 3:
                                                echo "Marzo";
                                                break;
                                            case 4:
                                                echo "Abril";
                                                break;
                                            case 5:
                                                echo "Mayo";
                                                break;
                                            case 6:
                                                echo "Junio";
                                                break;
                                            case 7:
                                                echo "Julio";
                                                break;
                                            case 8:
                                                echo "Agosto";
                                                break;
                                            case 9:
                                                echo "Septiembre";
                                                break;
                                            case 10:
                                                echo "Octubre";
                                                break;
                                            case 11:
                                                echo "Noviembre";
                                                break;
                                            case 12:
                                                echo "Diciembre";
                                                break;
                                        }
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["pais"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["ciudad"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["serie"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["editorial"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["edicion"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["isbn"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $lib["medio_divulgacion"];
                                    echo '</td>';
                                    $autorAux="";
                                    foreach ($this->usuarios as $usa) {
                                        if ($usa["id_usuario"] == $lib["id_autor"]) {    
                                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                        }
                                    }
                                    foreach ($this->autoresred as $aut) {
                                        if ($lib["id_gi_libro"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Libroshv') {
                                            foreach ($this->usuarios as $ua) {
                                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                }
                                            }
                                        }
                                    }
                                    echo '<td>';
                                    echo $autorAux;
                                    echo '</td>';    
                                    echo '<td>';
                                        if($lib["archivo"]!=""){
                                            ?>    
                                                <a class="btn" href="<?php echo $this->basePath()?>/application/libroshv/bajar/<?php echo $lib["id_gi_libro"];?>/<?php echo $lib["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                            <?php
                                        }
                                    echo '</td>'; 
                                    echo '<td>';
                                    echo '</td>';    
                                    echo '<td>';
                                    echo '</td>';    
                                    echo '<td>';
                                    echo '</td>';    
                                    echo '</tr>';
                                }
                            }
                        }
                    }//Libros usuario  
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Capitulos">
                <legend>Capítulos de libros</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/capitulosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 6%;'>Título del libro</th>";
                    echo "<th style='width: 4%;'>Año</th>";
                    echo "<th style='width: 3%;'>Mes</th>";
                    echo "<th style='width: 4%;'>País de publicación</th>";
                    echo "<th style='width: 5%;'>Ciudad de publicación</th>";
                    echo "<th style='width: 4%;'>Serie</th>";
                    echo "<th style='width: 6%;'>Editorial</th>";
                    echo "<th style='width: 5%;'>No. de Edición</th>";
                    echo "<th style='width: 6%;'>ISBN ó e-ISBN</th>";
                    echo "<th style='width: 6%;'>Medio de divulgación</th>";
                    echo "<th style='width: 6%;'>Título del capítulo</th>";
                    echo "<th style='width: 3%;'>No. de capítulo</th>";
                    echo "<th style='width: 4%;'>Páginas del capítulo</th>";
                    echo "<th style='width: 3%;'>Página inicio</th>";
                    echo "<th style='width: 3%;'>Página fin</th>";
                    echo "<th style='width: 6%;'>Autor(es)</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo "<th style='width: 5%;'>Agregar autor</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar</th>";
                    echo "</thead>";
                    echo "<tbody>";
                    echo '<tr>';
                    foreach ($this->capitulos as $int) {
                        echo '<tr>';
                            echo '<td>';
                            echo $int["titulo"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["ano"];
                            echo '</td>';
                        
                            echo '<td>';
                            switch ($int["mes"]) {
                                case 1:
                                    echo "Enero";
                                    break;
                                case 2:
                                    echo "Febrero";
                                    break;
                                case 3:
                                    echo "Marzo";
                                    break;
                                case 4:
                                    echo "Abril";
                                    break;
                                case 5:
                                    echo "Mayo";
                                    break;
                                case 6:
                                    echo "Junio";
                                    break;
                                case 7:
                                    echo "Julio";
                                    break;
                                case 8:
                                    echo "Agosto";
                                    break;
                                case 9:
                                    echo "Septiembre";
                                    break;
                                case 10:
                                    echo "Octubre";
                                    break;
                                case 11:
                                    echo "Noviembre";
                                    break;
                                case 12:
                                    echo "Diciembre";
                                    break;
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["pais"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["ciudad"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["serie"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["editorial"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["edicion"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["isbn"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["medio_divulgacion"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["titulo_capitulo"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["numero_capitulo"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["paginas_capitulo"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["pagina_inicio"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["pagina_fin"];
                            echo '</td>';

                            echo '<td>';
                            $autores="";
                            foreach ($this->usuarios as $usa) {
                                if ($usa["id_usuario"] == $int["id_autor"]) {
                                    $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                }
                            }
                            foreach ($this->autoresred as $autor) {
                                if($autor["seccion"]=="3" && $autor["id_objeto"]==$int["id"]){
                                    foreach ($this->usuarios as $usuario) {
                                        if($usuario["id_usuario"]==$autor["id_usuario"]){
                                            $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
                                        }    
                                    }
                                }
                            }
                            echo $autores;
                            echo '</td>';

                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/capitulosred/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            
                            echo '<td>';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/3"><i class="fa fa-plus"></i></a>

                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/capitulosred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/capitulosred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                    //Capitulo de libros usuario
                    foreach($this->dataDocumentos as $documento){
                        if($documento["tipo_documento"]=="capitulo"){
                            foreach ($this->capituloshv as $int) {
                                if($int["id"] == $documento["id_documento"]){
                                    echo '<tr>';
                                        echo '<td>';
                                        echo $int["titulo"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["ano"];
                                        echo '</td>';
                                    
                                        echo '<td>';
                                        switch ($int["mes"]) {
                                            case 1:
                                                echo "Enero";
                                                break;
                                            case 2:
                                                echo "Febrero";
                                                break;
                                            case 3:
                                                echo "Marzo";
                                                break;
                                            case 4:
                                                echo "Abril";
                                                break;
                                            case 5:
                                                echo "Mayo";
                                                break;
                                            case 6:
                                                echo "Junio";
                                                break;
                                            case 7:
                                                echo "Julio";
                                                break;
                                            case 8:
                                                echo "Agosto";
                                                break;
                                            case 9:
                                                echo "Septiembre";
                                                break;
                                            case 10:
                                                echo "Octubre";
                                                break;
                                            case 11:
                                                echo "Noviembre";
                                                break;
                                            case 12:
                                                echo "Diciembre";
                                                break;
                                        }
                                        echo '</td>';
                                    
                                        echo '<td>';
                                        echo $int["pais"];
                                        echo '</td>';
                                    
                                        echo '<td>';
                                        echo $int["ciudad"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["serie"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["editorial"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["edicion"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["isbn"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["medio_divulgacion"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["titulo_capitulo"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["numero_capitulo"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["paginas_capitulo"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["pagina_inicio"];
                                        echo '</td>';

                                        echo '<td>';
                                        echo $int["pagina_fin"];
                                        echo '</td>';

                                        echo '<td>';
                                        $autores="";
                                        foreach ($this->usuarios as $usa) {
                                            if ($usa["id_usuario"] == $int["id_autor"]) {
                                                $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                            }
                                        }
                                        foreach ($this->autoresusuario as $autor) {
                                            if($autor["seccion"]=="3" && $autor["id_objeto"]==$int["id"]){
                                                foreach ($this->usuarios as $usuario) {
                                                    if($usuario["id_usuario"]==$autor["id_usuario"]){
                                                        $autores .= $usuario["primer_nombre"]." ".$usuario["segundo_nombre"]." ".$usuario["primer_apellido"]." ".$usuario["segundo_apellido"]." - ";    
                                                    }    
                                                }
                                            }
                                        }
                                        echo $autores;
                                        echo '</td>';
                                        echo '<td>';
                                            if($int["archivo"]!=""){
                                                ?>    
                                                    <a class="btn" href="<?php echo $this->basePath()?>/application/capitulosusuario/bajar/<?php echo $int["id"];?>/<?php echo $int["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                        <?php    }
                                        echo '</td>'; 
                                        echo '<td>';
                                        echo '</td>';
                                        echo '<td>';
                                        echo '</td>';
                                        echo '<td>';
                                        echo '</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                    }//Capitulo de libros usuario
                    echo '</tr>';
                    echo "</tbody>";
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Otras">
                <legend>Otras producciones de investigación</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/produccionesinvred/index/<?php echo $id;?>">Agregar</a><br><br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 10%;'>Nombre producto</th>";
                echo "<th style='width: 10%;'>Descripción producto</th>";
                echo "<th style='width: 10%;'>Tipo producto</th>";
                echo "<th style='width: 3%;'>Año</th>";
                echo "<th style='width: 3%;'>Mes</th>";
                echo "<th style='width: 4%;'>Pais</th>";
                echo "<th style='width: 5%;'>Ciudad</th>";
                echo "<th style='width: 10%;'>Instituciones participantes</th>";
                echo "<th style='width: 5%;'>Registro</th>";
                echo "<th style='width: 10%;'>Otra información</th>";
                echo "<th style='width: 10%;'>Autor(es)</th>";
                echo "<th style='width: 5%;'>Descargar archivo</th>";
                echo "<th style='width: 5%;'>Agregar autor</th>";
                echo '<th style="width: 5%;">Ver/Editar</th>';
                echo "<th style='width: 5%;'>Eliminar</th>";
                echo '<tr>';

                foreach ($this->produccionesinv as $int) {
                    echo '<tr>';
                        echo '<td>';
                        echo $int["nombre"];
                        echo '</td>';
                    
                        echo '<td>';
                        echo $int["descripcion"];
                        echo '</td>';

                        echo '<td>';
                        echo $int["tipo"];
                        echo '</td>';

                        echo '<td>';
                        echo $int["ano"];
                        echo '</td>';

                        echo '<td>';
                        switch ($int["mes"]) {
                            case 1:
                                echo "Enero";
                                break;
                            case 2:
                                echo "Febrero";
                                break;
                            case 3:
                                echo "Marzo";
                                break;
                            case 4:
                                echo "Abril";
                                break;
                            case 5:
                                echo "Mayo";
                                break;
                            case 6:
                                echo "Junio";
                                break;
                            case 7:
                                echo "Julio";
                                break;
                            case 8:
                                echo "Agosto";
                                break;
                            case 9:
                                echo "Septiembre";
                                break;
                            case 10:
                                echo "Octubre";
                                break;
                            case 11:
                                echo "Noviembre";
                                break;
                            case 12:
                                echo "Diciembre";
                                break;
                        }
                        echo '</td>';
                    
                        echo '<td>';
                        echo $int["pais"];
                        echo '</td>';

                        echo '<td>';
                        echo $int["ciudad"];
                        echo '</td>';

                        echo '<td>';
                        echo $int["instituciones"];
                        echo '</td>';

                        echo '<td>';
                        echo $int["registro"];
                        echo '</td>';
                    
                        echo '<td>';
                        echo $int["otra_informacion"];
                        echo '</td>';

                        echo '<td>';
                        $autores="";
                        foreach ($this->usuarios as $usa) {
                            if ($usa["id_usuario"] == $int["id_autor"]) {
                                $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                            }
                        }
                        foreach ($this->autoresred as $autor) {
                            if($autor["seccion"]=="4" && $autor["id_objeto"]==$int["id"]){
                                foreach ($this->usuarios as $usuario) {
                                    if($usuario["id_usuario"]==$autor["id_usuario"]){
                                        $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
                                    }    
                                }
                            }
                        }
                        echo $autores;
                        echo '</td>';

                        echo '<td>';
                        if($int["archivo"]!=""){
                            ?>    
                                <a class="btn" href="<?php echo $this->basePath()?>/application/produccionesinvred/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                            <?php
                        }
                        echo '</td>';
                        
                        echo '<td style="text-align:center;">';
                        ?>
                            <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/4"><i class="fa fa-plus"></i></a>

                        <?php
                        echo '</td>';

                        echo '<td style="text-align:center;">';
                        ?>
                            <a class="btn" href="<?php echo $this->basePath() ?>/application/produccionesinvred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                        <?php
                        echo '</td>';

                        echo '<td style="text-align:center;">';
                        ?>
                            <a class="btn" href="<?php echo $this->basePath() ?>/application/produccionesinvred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                        <?php
                        echo '</td>';
                    echo '</tr>';
                }
                //Otras producciones usuario
                foreach($this->dataDocumentos as $documento){
                    if($documento["tipo_documento"]=="producciones"){
                        foreach ($this->Otrasproduccioneshv as $ot) {
                            if($ot["id_otra_prod"] == $documento["id_documento"]){
                                echo '<tr>';
                                echo '<td>';
                                echo $ot["nombre_producto"];
                                echo '</td>';
                                echo '<td>';
                                echo $ot["descripcion_producto"];
                                echo '</td>';
                                echo '<td>';
                                echo $ot["tipo_producto"];
                                echo '</td>';
                                echo '<td>';
                                echo $ot["ano"];
                                echo '</td>';
                                echo '<td>';
                                switch ($ot["mes"]) {
                                    case 1:
                                        echo "Enero";
                                        break;
                                    case 2:
                                        echo "Febrero";
                                        break;
                                    case 3:
                                        echo "Marzo";
                                        break;
                                    case 4:
                                        echo "Abril";
                                        break;
                                    case 5:
                                        echo "Mayo";
                                        break;
                                    case 6:
                                        echo "Junio";
                                        break;
                                    case 7:
                                        echo "Julio";
                                        break;
                                    case 8:
                                        echo "Agosto";
                                        break;
                                    case 9:
                                        echo "Septiembre";
                                        break;
                                    case 10:
                                        echo "Octubre";
                                        break;
                                    case 11:
                                        echo "Noviembre";
                                        break;
                                    case 12:
                                        echo "Diciembre";
                                        break;
                                }
                                echo '</td>';
                                echo '</td>';
                                echo '<td>';
                                foreach ($this->vf2 as $vl) {
                                    if ($vl["id_valor_flexible"] == $ot["id_pais"]) {
                                        $ot["id_pais"] = $vl["descripcion_valor"];
                                    }
                                }
                                echo $ot["id_pais"];
                                echo '</td>';
                                echo '<td>';
                                foreach ($this->vf2 as $vl) {
                                    if ($vl["id_valor_flexible"] == $ot["id_ciudad"]) {
                                        $ot["id_pais"] = $vl["descripcion_valor"];
                                    }
                                }
                                echo $ot["id_ciudad"];
                                echo '</td>';
                                echo '</td>';
                                echo '<td>';
                                echo $ot["instituciones"];
                                echo '</td>';
                                echo '<td>';
                                echo $ot["registro"];
                                echo '</td>';
                                echo '<td>';
                                echo $ot["otra_info"];
                                echo '</td>';
                                $autorAux="";
                                foreach ($this->usuarios as $usa) {
                                    if ($usa["id_usuario"] == $ot["id_autor"]) {    
                                        $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                    }
                                }
                                foreach ($this->autoresred as $aut) {
                                    if ($ot["id_otra_prod"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'otra_prodhv') {
                                        foreach ($this->usuarios as $ua) {
                                            if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                            }
                                        }
                                    }
                                }
                                echo '<td>';
                                echo $autorAux;
                                echo '</td>';
                                echo '<td>';
                                    if($ot["archivo"]!=""){
                                        ?>    
                                            <a class="btn" href="<?php echo $this->basePath()?>/application/otrasproduccioneshv/bajar/<?php echo $ot["id_otra_prod"];?>/<?php echo $ot["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                <?php    }
                                echo '</td>';  
                                 echo '<td>';
                                echo '</td>';
                                 echo '<td>';
                                echo '</td>';
                                 echo '<td>';
                                echo '</td>';
                                echo '</tr>';
                            }
                        }  
                    }
                }//Otras producciones usuario
                echo '</tr>';
                echo '</table>';
                echo '</div>';
            ?>
            </div>
            <div id="Otros">
                <legend>Otros documentos bibliográficos</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/documentosbibliograficosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 6%;'>Nombre</th>";
                    echo "<th style='width: 3%;'>No. Páginas</th>";
                    echo "<th style='width: 3%;'>Año</th>";
                    echo "<th style='width: 3%;'>Mes</th>";
                    echo "<th style='width: 4%;'>Pais</th>";
                    echo "<th style='width: 4%;'>Ciudad</th>";
                    echo "<th style='width: 10%;'>Indexación</th>";
                    echo "<th style='width: 10%;'>Instituciones participantes</th>";
                    echo "<th style='width: 5%;'>URL</th>";
                    echo "<th style='width: 12%;'>Descripción</th>";
                    echo "<th style='width: 12%;'>Medio de divulgación</th>";
                    echo "<th style='width: 6%;'>Autor(es)</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo "<th style='width: 5%;'>Agregar autor</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar</th>";
                    echo '<tr>';

                    foreach ($this->documentosbliograficos as $int) {
                        echo '<tr>';
                            echo '<td>';
                            echo $int["nombre"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["numero_paginas"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["ano"];
                            echo '</td>';

                            echo '<td>';
                            switch ($int["mes"]) {
                                case 1:
                                    echo "Enero";
                                    break;
                                case 2:
                                    echo "Febrero";
                                    break;
                                case 3:
                                    echo "Marzo";
                                    break;
                                case 4:
                                    echo "Abril";
                                    break;
                                case 5:
                                    echo "Mayo";
                                    break;
                                case 6:
                                    echo "Junio";
                                    break;
                                case 7:
                                    echo "Julio";
                                    break;
                                case 8:
                                    echo "Agosto";
                                    break;
                                case 9:
                                    echo "Septiembre";
                                    break;
                                case 10:
                                    echo "Octubre";
                                    break;
                                case 11:
                                    echo "Noviembre";
                                    break;
                                case 12:
                                    echo "Diciembre";
                                    break;
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["pais"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["ciudad"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["numero_indexacion"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["instituciones"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["url"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["descripcion"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["medio_divulgacion"];
                            echo '</td>';

                            echo '<td>';
                            $autores="";
                            foreach ($this->usuarios as $usa) {
                                if ($usa["id_usuario"] == $int["id_autor"]) {
                                    $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                }
                            }
                            foreach ($this->autoresred as $autor) {
                                if($autor["seccion"]=="5" && $autor["id_objeto"]==$int["id"]){
                                    foreach ($this->usuarios as $usuario) {
                                        if($usuario["id_usuario"]==$autor["id_usuario"]){
                                            $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
                                        }    
                                    }
                                }
                            }
                            echo $autores;
                            echo '</td>';

                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/documentosbibliograficosred/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/5"><i class="fa fa-plus"></i></a>

                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/documentosbibliograficosred/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/documentosbibliograficosred/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                    //Otros documentos usuario
                    foreach($this->dataDocumentos as $documento){
                        if($documento["tipo_documento"]=="documentos"){
                            foreach ($this->Bibliograficoshv as $bli) {
                                if($bli["id_bibliografico"] == $documento["id_documento"]){
                                    echo '<tr>';
                                    echo '<td>';
                                    echo $bli["nombre_documento"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["numero_paginas"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["ano"];
                                    echo '</td>';
                                    echo '<td>';
                                    switch ($bli["mes"]) {
                                        case 1:
                                            echo "Enero";
                                            break;
                                        case 2:
                                            echo "Febrero";
                                            break;
                                        case 3:
                                            echo "Marzo";
                                            break;
                                        case 4:
                                            echo "Abril";
                                            break;
                                        case 5:
                                            echo "Mayo";
                                            break;
                                        case 6:
                                            echo "Junio";
                                            break;
                                        case 7:
                                            echo "Julio";
                                            break;
                                        case 8:
                                            echo "Agosto";
                                            break;
                                        case 9:
                                            echo "Septiembre";
                                            break;
                                        case 10:
                                            echo "Octubre";
                                            break;
                                        case 11:
                                            echo "Noviembre";
                                            break;
                                        case 12:
                                            echo "Diciembre";
                                            break;
                                    }
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["pais"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["ciudad"];
                                    echo '</td>';        
                                    echo '<td>';
                                    echo $bli["num_indexacion"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["instituciones"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["url"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["descripcion"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $bli["medio_divulgacion"];
                                    echo '</td>';
                                    $autorAux="";
                                    foreach ($this->usuarios as $usa) {
                                        if ($usa["id_usuario"] == $bli["id_autor"]) {    
                                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                        }
                                    }
                                    foreach ($this->autoresred as $aut) {
                                        if ($bli["id_bibliografico"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'bibliograficohv') {
                                            foreach ($this->usuarios as $ua) {
                                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                }
                                            }
                                        }
                                    }
                                    echo '<td>';
                                    echo $autorAux;
                                    echo '</td>';
                                    echo '<td>';
                                        if($bli["archivo"]!=""){
                                            ?>    
                                                <a href="<?php echo $this->basePath()?>/application/bibliograficoshv/bajar/<?php echo $bli["id_bibliografico"];?>/<?php echo $bli["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                    <?php    }
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                    }//Otros documentos usuario
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Proyectos">
                <legend>Proyectos de investigación externos</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectored/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 5%;'>Código del proyecto</th>";
                    echo "<th style='width: 5%;'>Nombre del proyecto</th>";
                    echo "<th style='width: 5%;'>Fecha inicio</th>";
                    echo "<th style='width: 5%;'>Fecha fin</th>";
                    echo "<th style='width: 17%;'>Resumen ejecutivo</th>";
                    echo "<th style='width: 12%;'>Objetivo general</th>";
                    echo "<th style='width: 15%;'>Equipo de trabajo</th>";
                    echo "<th style='width: 10%;'>Productos derivados</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo "<th style='width: 5%;'>Agregar equipo</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar proyecto</th>";
                    echo '<tr>';

                    foreach ($this->proyectored as $int) {
                        echo '<tr>';
                            echo '<td>';
                            echo $int["codigo"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["nombre"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["fecha_inicio"];
                            echo '</td>';
                        
                            echo '<td>';
                            echo $int["fecha_fin"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["resumen"];
                            echo '</td>';

                            echo '<td>';
                            echo $int["objetivo"];
                            echo '</td>';
                        
                            echo '<td style="text-align:center;">';
                            echo '<table style="border-style: hidden;">';
                            $autores="";
                            $rol = "";
                            foreach ($this->autoresred as $autor) {
                                if($autor["seccion"]=="6" && $autor["id_objeto"]==$int["id"]){
                                    foreach ($this->usuarios as $usuario) {
                                        if($usuario["id_usuario"]==$autor["id_usuario"]){

                                            foreach ($this->vf4 as $v) {
                                                if ($v["id_valor_flexible"] == $autor["id_rol"]) {
                                                    $rol = $v["descripcion_valor"];
                                                }
                                            }
                                            $autores .= '<tr><td>'.$usuario["primer_nombre"]." ".$usuario["segundo_nombre"]." ".$usuario["primer_apellido"]." ".$usuario["segundo_apellido"]. '</td><td>'.$rol.'</td></tr>';   
                                        }    
                                    }
                                }
                            }
                            echo $autores;
                            echo '</table>';
                            echo '</td>';

                            echo '<td>';
                            echo $int["productos"];
                            echo '</td>';

                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/proyectored/bajar/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorred/index/<?php echo $int["id"];?>/<?php echo $id;?>/6"><i class="fa fa-plus"></i></a>

                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectored/index/<?php echo $id;?>/<?php echo $int["id"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectored/del/<?php echo $int["id"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                    //Proyectos externos usuario
                    foreach($this->dataDocumentos as $documento){
                        if($documento["tipo_documento"]=="externos"){
                            foreach ($this->Proyectosexthv as $proyext) {
                                if($proyext["id_proyecto_ext"] == $documento["id_documento"]){
                                    echo '<tr>';
                                    echo '<td>';
                                    echo $proyext["codigo_proyecto"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $proyext["nombre_proyecto"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $proyext["fecha_inicio"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $proyext["fecha_fin"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $proyext["resumen_ejecutivo"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo $proyext["objetivo_general"];
                                    echo '</td>';
                                    echo '<td>';
                                    echo '<table style="border-style: hidden;">';
                                    foreach ($this->autoresred as $auts) {
                                        if ($proyext["id_proyecto_ext"] == $auts["id_padre"] && trim($auts["nombre_padre"]) == 'proy_exthv') {
                                            foreach ($this->vf2 as $v) {
                                                if ($v["id_valor_flexible"] == $auts["id_rol"]) {
                                                    $rol = $v["descripcion_valor"];
                                                }
                                            }
                                            foreach ($this->usuarios as $ua) {
                                                if ($ua["id_usuario"] == $auts["id_usuario"]) {
                                                    echo '<tr><td>'.trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"]).'</td><td>'.$rol.'</td>';
                                                    echo '</tr>';
                                                }
                                            }
                                        }
                                    }
                                    echo '</table></td>';
                                    echo '<td>';
                                    echo $proyext["productos_derivados"];
                                    echo '</td>';
                                    echo '<td>';
                                        if($proyext["archivo"]!=""){
                                            ?>    
                                                <a class="btn" href="<?php echo $this->basePath()?>/application/proyectosexthv/bajar/<?php echo $proyext["id_proyecto_ext"];?>/<?php echo $proyext["id_usuario"];?>"><i class="fa fa-download"></i></a>
                                            <?php
                                        }
                                    echo '</td>'; 
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '<td>';
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                    }//Proyectos externos usuario
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Proyectos_internos">
                <legend>Proyectos de investigación internos</legend>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectosintred/index/<?php echo $id;?>">Agregar</a><br><br>
                <?php
                echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                echo '<table class="table" style="width: 100%; max-width: 100%;">';
                echo '<thead>';
                echo "<th style='width: 5%;'>Código del proyecto</th>";
                echo "<th style='width: 5%;'>Nombre del proyecto</th>";
                echo "<th style='width: 5%;'>Investigador principal</th>";
                echo "<th style='width: 5%;'>Duración</th>";
                echo "<th style='width: 5%;'>Unidad académica</th>";
                echo "<th style='width: 20%;'>Dependencia académica</th>";
                echo "<th style='width: 15%;'>Resumen ejecutivo</th>";
                echo "<th style='width: 15%;'>Objetivo general</th>";
                echo "<th style='width: 10%;'>Equipo de trabajo</th>";
                echo "<th style='width: 10%;'>Descargar</th>";
                echo '<th style="width: 5%;">Cargar documento</th>';
                echo '<th style="width: 5%;">Ver/Editar</th>';
                echo "<th style='width: 5%;'>Eliminar proyecto</th>";
                echo '</tr>';
                foreach ($this->proyectosint as $proyint) {
                    foreach ($this->proyectos as $proyectosT) {
                        if($proyint["id_proyecto"]==$proyectosT["id_proyecto"]){
                               echo '<tr>';
                                echo '<td>';
                                echo $proyectosT["codigo_proy"];
                                echo '</td>';
                                echo '<td>';
                                echo $proyectosT["nombre_proy"];
                                echo '</td>';
                                echo '<td>';
                                foreach ($this->usuarios as $ua) {
                                    if ($ua["id_usuario"] == $proyectosT["id_investigador"]) {
                                        echo trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]);
                                    }
                                }
                                echo '</td>';
                                echo '<td>';
                                echo $proyectosT["duracion"];
                                echo '</td>';
                                echo '<td>';
                                foreach ($this->vf2 as $vl) {
                                    if ($vl["id_valor_flexible"] == $proyectosT["id_unidad_academica"]) {
                                        $proyectosT["id_unidad_academica"] = $vl["descripcion_valor"];
                                    }
                                }
                                echo $proyectosT["id_unidad_academica"];
                                echo '</td>';
                                echo '<td>';
                                foreach ($this->vf2 as $vl) {
                                    if ($vl["id_valor_flexible"] == $proyectosT["id_dependencia_academica"]) {
                                        $proyectosT["id_dependencia_academica"] = $vl["descripcion_valor"];
                                    }
                                }
                                echo $proyectosT["id_dependencia_academica"];
                                echo '</td>';
                                echo '<td>';
                                echo $proyectosT["resumen_ejecutivo"];
                                echo '</td>';
                                echo '<td>';
                                echo $proyectosT["objetivo_general"];
                                echo '</td>';
                                echo '<td>';
                                echo '<table style="border-style: hidden;">';
                                $rol="";
                                foreach ($this->tablaequipo as $auts) {
                                    if ($proyectosT["id_proyecto"] == $auts["id_proyecto"]) {
                                        foreach ($this->vf2 as $v) {
                                            if ($v["id_valor_flexible"] == $auts["id_rol"]) {
                                                $rol = $v["descripcion_valor"];
                                            }
                                        }
                                        foreach ($this->usuarios as $ua) {
                                            if ($ua["id_usuario"] == $auts["id_integrante"]) {
                                                echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]). '</td><td>'.$rol.'</td>';
                                                echo '</tr>';
                                            }
                                        }
                                    }
                                }
                                echo '</table></td>';
                                echo '</td>';
                                echo '<td style="text-align:center;">';
                                    if($proyint["archivo"]!=""){
                                        ?>    
                                            <a class="btn" href="<?php echo $this->basePath()?>/application/proyectosintred/bajar/<?php echo $id;?>/<?php echo $proyint["id"];?>"><i class="fa fa-download"></i></a>
                                        <?php
                                    }
                                echo '</td>';
                                echo '<td style="text-align:center;">';
                                ?>
                                    <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectosintred/index/<?php echo $id;?>/<?php echo $proyint["id"];?>/1"><i class="fa fa-plus"></i></a>
                                <?php
                                echo '</td>';
                                echo '<td style="text-align:center;">';
                                ?>
                                    <a class="btn" href="<?php echo $this->basePath() ?>/application/proyectosintred/index/<?php echo $id;?>/<?php echo $proyint["id"];?>"><i class="fa fa-pencil"></i></a>
                                <?php
                                echo '</td>';

                                echo '<td>';
                                 ?>
                                <a class="btn"
                                        href="<?php echo $this->basePath() ?>/application/proyectosintred/del/<?php echo $proyint["id"];?>/<?php echo $proyint["id_grupo_inv"];?>"><i class="fa fa-trash"></i></a>
                                <?php
                                echo '</td>';
                        }
                    }
                }
                //Proyectos internos usuario
                foreach($this->dataDocumentos as $documento){
                    if($documento["tipo_documento"]=="internos"){
                        foreach ($this->Proyectosintusua as $proyint) {
                            if($proyint["id"] == $documento["id_documento"]){
                                foreach ($this->proyectos as $proyectosT) {
                                    if($proyint["id_proyecto"]==$proyectosT["id_proyecto"]){
                                           echo '<tr>';
                                            echo '<td>';
                                            echo $proyectosT["codigo_proy"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyectosT["nombre_proy"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->usuarios as $ua) {
                                                if ($ua["id_usuario"] == $proyectosT["id_investigador"]) {
                                                    echo trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]);
                                                }
                                            }
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyectosT["duracion"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vf2 as $vl) {
                                                if ($vl["id_valor_flexible"] == $proyectosT["id_unidad_academica"]) {
                                                    $proyectosT["id_unidad_academica"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $proyectosT["id_unidad_academica"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vf2 as $vl) {
                                                if ($vl["id_valor_flexible"] == $proyectosT["id_dependencia_academica"]) {
                                                    $proyectosT["id_dependencia_academica"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $proyectosT["id_dependencia_academica"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyectosT["resumen_ejecutivo"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyectosT["objetivo_general"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo '<table style="border-style: hidden;">';
                                            $rol="";
                                            foreach ($this->tablaequipo as $auts) {
                                                if ($proyectosT["id_proyecto"] == $auts["id_proyecto"]) {
                                                    foreach ($this->valflex as $v) {
                                                        if ($v["id_valor_flexible"] == $auts["id_rol"]) {
                                                            $rol = $v["descripcion_valor"];
                                                        }
                                                    }
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $auts["id_integrante"]) {
                                                            echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]). '</td><td>'.$rol.'</td>';
                                                            echo '</tr>';
                                                        }
                                                    }
                                                }
                                            }
                                            echo '</table>';
                                            echo '<td>';
                                            echo '<td style="text-align:center;">';
                                                if($proyint["archivo"]!=""){
                                                    ?>    
                                                        <a class="btn" href="<?php echo $this->basePath()?>/application/proyectosintusua/bajar/<?php echo $documento["id_usuario"];?>/<?php echo $proyint["id"];?>"><i class="fa fa-download"></i></a>
                                                    <?php
                                                }
                                            echo '</td>';
                                            echo '<td>';
                                            echo '</td>';
                                            echo '<td>';
                                            echo '</td>';
                                            echo '<td>';
                                            echo '</td>';
                                    }
                                }
                            }
                        }
                    }
                }//Proyectos internos usuario
                echo '</tr>';
                echo '</table>';
                echo '</div>';
                ?>
            </div>
            <div id="Material">
                <legend>Material colaborativo gratuito</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/archivosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 40%;'>Tipo de archivo</th>";
                    echo "<th style='width: 40%;'>Descargar</th>";
                    echo '<th style="width: 10%;">Ver/Editar</th>';
                    echo "<th style='width: 10%;'>Eliminar</th>";
                    echo '<tr>';
                    foreach ($this->archivosred as $int) {
                        echo '<tr>';
                            echo '<td>';
                            foreach ($this->vf as $val) {
                                if($val["id_valor_flexible"]==$int["id_tipo_archivo"]){
                                    echo $val["descripcion_valor"];
                                }
                            }
                            echo '</td>';
                        
                            echo '<td>';
                            ?>    
                                <a href="<?php echo $this->basePath()?>/application/archivosred/bajar/<?php echo $int["id_archivo"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/archivosred/index/<?php echo $id;?>/<?php echo $int["id_archivo"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/archivosred/del/<?php echo $int["id_archivo"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>
                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }

                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Identificadores">
                <legend>Identificadores de Investigación</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/identificadoresred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 5%;'>ID</th>";
                    echo "<th style='width: 20%;'>Nombre registrado</th>";
                    echo '<th style="width: 5%;">Tipo de identificador</th>';
                    echo "<th style='width: 10%;'>Tipo de categoría</th>";
                    echo "<th style='width: 5%;'>Fecha de registro</th>";
                    echo "<th style='width: 15%;'>Dirección web</th>";
                    echo "<th style='width: 5%;'>Ciudad</th>";
                    echo "<th style='width: 20%;'>Descripción</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar proyecto</th>";
                    echo '<tr>';
                    foreach ($this->identificadores as $int) {
                        echo '<tr>';
                            echo '<td>';
                                echo $int["id_field"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["nombre"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipoidentificador"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipocategoria"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["fecha_registro"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["web"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["ciudad"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["descripcion"];
                            echo '</td>';                      
                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/identificadoresred/bajar/<?php echo $int["id_identificador"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/identificadoresred/index/<?php echo $id;?>/<?php echo $int["id_identificador"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/identificadoresred/del/<?php echo $int["id_identificador"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }

                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Divulgacion">
                <legend>Divulgación</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/eventosred/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 15%;'>Nombre de trabajo</th>";
                    echo "<th style='width: 15%;'>Tipo de evento</th>";
                    echo "<th style='width: 15%;'>Evento</th>";
                    echo '<th style="width: 15%;">Tipo de participación</th>';
                    echo "<th style='width: 15%;'>Nombre de trabajo</th>";
                    echo "<th style='width: 10%;'>Tipo de medio</th>";
                    echo "<th style='width: 15%;'>Medio de divulgación</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar proyecto</th>";
                    echo '<tr>';
                    foreach ($this->eventos as $int) {
                        echo '<tr>';
                            echo '<td>';
                                echo $int["nombre_trabajo"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipoevento"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["nombre_evento"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipoparticipacion"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["nombre_trabajo_medio"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipomedio"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["medio_divulgacion"];
                            echo '</td>';                   
                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/eventosred/bajar/<?php echo $int["id_evento"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/eventosred/index/<?php echo $id;?>/<?php echo $int["id_evento"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/eventosred/del/<?php echo $int["id_evento"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }

                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
            <div id="Formacion">
                <legend>Formación</legend>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/trabajogradored/index/<?php echo $id;?>">Agregar</a><br><br>
                    <?php
                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                    echo '<thead>';
                    echo "<th style='width: 15%;'>Trabajo de grado</th>";
                    echo "<th style='width: 10%;'>Tipo de trabajo</th>";
                    echo '<th style="width: 10%;">Tipo de participación</th>';
                    echo "<th style='width: 10%;'>Estado</th>";
                    echo "<th style='width: 10%;'>Proyecto de Inv.</th>";
                    echo "<th style='width: 10%;'>Tipo de formación</th>";
                    echo "<th style='width: 10%;'>Semillero</th>";
                    echo "<th style='width: 10%;'>Tipo de participación</th>";
                    echo "<th style='width: 5%;'>Descargar archivo</th>";
                    echo '<th style="width: 5%;">Ver/Editar</th>';
                    echo "<th style='width: 5%;'>Eliminar proyecto</th>";
                    echo '<tr>';
                    foreach ($this->formacion as $int) {
                        echo '<tr>';
                            echo '<td>';
                                echo $int["nombre_trabajo"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipotrabajo"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipoparticipacion"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_estadotipotrabajo"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["nombre_proyecto"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_formacioninvestigador"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->semilleros as $val) {
                                    if($val["id"]==$int["id_semillero"]){
                                        echo $val["codigo"]."-".$val["nombre"];
                                    }
                                }
                            echo '</td>';
                             echo '<td>';
                                foreach ($this->vf2 as $val) {
                                    if($val["id_valor_flexible"]==$int["id_rolparticipacion"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';             
                            echo '<td>';
                            if($int["archivo"]!=""){
                                ?>    
                                    <a class="btn" href="<?php echo $this->basePath()?>/application/trabajogradored/bajar/<?php echo $int["id_trabajogrado"];?>/<?php echo $id;?>"><i class="fa fa-download"></i></a>
                                <?php
                            }
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/trabajogradored/index/<?php echo $id;?>/<?php echo $int["id_trabajogrado"];?>"><i class="fa fa-pencil"></i></a>
                            <?php
                            echo '</td>';

                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/trabajogradored/del/<?php echo $int["id_trabajogrado"];?>/<?php echo $id;?>"><i class="fa fa-trash"></i></a>

                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }

                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                ?>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $GLOBALS["ruta_servidor"] . 'js/ui/jquery-ui.min.js'; ?>"></script>
<script>
    $("#tabs").tabs();
</script>
<script type="text/javascript">
    function showHint1(str) {
        var valthis = str.toLowerCase();
        var num = 0;

        $('select#coordinador_1>option').each(function () {
              var text = $(this).text().toLowerCase();
              if(text.indexOf(valthis) !== -1)  
                  {$(this).show(); $(this).prop('selected',true);}
              else{$(this).hide();}
               });
    }
    function showHint2(str) {
        var valthis = str.toLowerCase();
        var num = 0;

        $('select#coordinador_2>option').each(function () {
              var text = $(this).text().toLowerCase();
              if(text.indexOf(valthis) !== -1)  
                  {$(this).show(); $(this).prop('selected',true);}
              else{$(this).hide();}
               });
    }
</script>
<script>
    $(".redes_edit").click(function() {
        $(".edit-slide").css("left", "0%");
    });
    $(".close-edit").click(function() {
        $(".edit-slide").css("left", "-100%");
    });
    $(".cancel-edit").click(function() {
        $(".edit-slide").css("left", "-100%");
    });
</script>