<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<center>
					<h6>¿Eliminar el documento?</h6>
					<a class="btn"
						href="<?php echo $this->basePath() ?>/application/repositorio/eliminar/<?php echo $this->id;?>">Eliminar documento</a> <a class="btn"
						href="<?php echo $this->basePath() ?>/application/repositorio/index">Cancelar</a>
					<br>
					<br>
			</div>
		</div>
	</div>
</div>



