<style>
	.filter-group input[type="text"],select{
		width: 100%;
	}
	.filter-group {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-group-left {float: left;}
	.filter-group-right {float:right;}
	.filter-group .btn {width: 275px;}
	.filter-group .dropdown {display: inline;}
	.filter-group .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.dropdown-menu-right {left:-140px !important;}
</style>
<script type="text/javascript">
	$(function () {
	    var opts = $('#autor option').map(function () {
	        return [[this.value, $(this).text()]];
	    });
	    $('#id_autor').keyup(function () {
	        var rxp = new RegExp($('#id_autor').val(), 'i');
	        var optlist = $('#autor').empty();
	        opts.each(function () {
	            if (rxp.test(this[1])) {
	                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
	            }
	        });
	    });
	});
</script>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-group">
		<div class="filter-group-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-group-right">
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/repositorio/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php								
						$form = $this->form;
						$form->prepare ();
						$form->setAttributes ( array (
						'action' => 'index',
						'method' => 'post' 
						) );
						echo $this->form ()->openTag ( $form );
						echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
						echo $this->formlabel ( $form->get ( 'id_tipo' ) );
						echo $this->formelement ( $form->get ( 'id_tipo' ) );
						echo $this->formlabel ( $form->get ( 'nombre' ) );
						echo $this->formelement ( $form->get ( 'nombre' ) );
						echo $this->formlabel($form->get('id_autor'));
						echo $this->formelement($form->get('id_autor'));
						echo $this->formelement($form->get('autor'));
						echo $this->formelement($form->get('submit'));
 						echo $this->form ()->closeTag ( $form );
 						?>
					</div>						
				</div>
			</div>
			<?php if($this->id_user!="0"){?>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/crearrepositorio/index">Crear repositorio</a>
		<?php } ?>
		</div>
	</div>
</div>

				<?php					
				echo '<div class="col col100 noshadow">';
				echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
				echo '<table class="table" style="width: 100%; max-width: 100%;">';
				echo "<thead>";
				echo "<th style='width: 10%;'>Nombre del documento";
				echo "<th style='width: 5%;'>Tipo de documento</th>";
				echo "<th style='width: 9%;'>Fecha de creaci&#243;n</th>";
				echo "<th style='width: 10%;'>Creado por</th>";
				echo "<th style='width: 13%;'>Descripción</th>";
				echo "<th style='width: 12%;'>Otra información relevante</th>";
				echo "<th style='width: 7%;'>URL</th>";
				echo "<th style='width: 9%;'>Descargar documento</th>";
				echo "<th style='width: 10%;'>Autor(es)</th>";
				if($this->menu==1){ 
					echo "<th style='width: 10%;'>Agregar autor</th>";
					echo "<th style='width: 5%;'>Eliminar</th>";
				} 
				echo '</thead>';
				echo '<tbody>';
				foreach ( $this->datosRepositorio as $dato ) {
					echo '<tr>';
					echo '<td>';
					echo $dato ["nombre"];
					echo '</td>';
					echo '<td>';
					foreach ( $this->d_val as $vf ) {
						if ($vf ["id_valor_flexible"] == $dato ["id_tipo"]) {
							echo $vf ["descripcion_valor"];
						}
					}
					echo '</td>';

					echo '<td style="text-align:center;">';
					echo $dato ["fecha_creacion"]; 
					echo '</td>';

					echo '<td>';
					foreach ($this->d_user as $usuario) {
	                    if($usuario["id_usuario"]==$dato["id_usuario_creador"]){
	                        echo $usuario["primer_nombre"] ." ". $usuario["segundo_nombre"] ." ". $usuario["primer_apellido"] ." ". $usuario["segundo_apellido"];    
	                    }    
	                }
					echo '</td>';
					
					echo '<td>';
					echo $dato ["descripcion"];
					echo '</td>';

					echo '<td>';
					echo $dato ["otra_informacion"];
					echo '</td>';

					echo '<td>';
					if (filter_var($dato ["url"], FILTER_VALIDATE_URL)) {
					    echo '<a href="'.$dato ["url"].'" target="_blank">'.$dato ["url"].'</a>';
					} else {
						echo '<a href="http://'.$dato ["url"].'" target="_blank">'.$dato ["url"].'</a>';

					}
					echo '</td>';

					echo '<td>';
					if($dato["archivo"]!=""){
		                ?>    
		                    <a class="btn" href="<?php echo $this->basePath()?>/application/repositorio/bajar/<?php echo $dato["id_repositorio"];?>"><i class="fa fa-download"></i></a>
		                <?php
		            }else{
		                echo 'Sin archivo';
		            }
					echo '</td>';
					
					echo '<td>';
		            $autores="";
		            foreach ($this->autoresrepositorio as $autor) {
		                if($autor["seccion"]=="2" && $autor["id_repositorio"]==$dato["id_repositorio"]){
		                    foreach ($this->d_user as $usuario) {
		                        if($usuario["id_usuario"]==$autor["id_usuario"]){
		                            $autores .= $usuario["primer_nombre"] . $usuario["segundo_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
		                        }    
		                    }
		                }
		            }
		            echo $autores;
		            echo '</td>';
		            if($this->menu==1){ 
		            	echo '<td style="text-align:center;">';
			            ?>
			                <a class="btn" href="<?php echo $this->basePath() ?>/application/agregarautorrepositorio/index/1/<?php echo $dato["id_repositorio"];?>/2"><i class="fa fa-plus"></i></a>
			            <?php
			            echo '</td>';

		            	echo '<td style="text-align:center;">';
						?>
							<a class="btn" href="<?php echo $this->basePath() ?>/application/repositorio/del/<?php echo $dato["id_repositorio"];?>"><i class="fa fa-trash"></i></a>
						<?php
						echo '</td>';
					} 
				}
				echo '</tr>';
				echo '</table>';

				if(count($this->datosRepositorio) == 0){
					if($this->data["id_tipo"]){
						echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos documentos con este tipo</h3></div>';
					}else if($this->data["nombre"]){
						echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos documentos con este nombre</h3></div>';
					}else if($this->data["autor"]){
						echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos documentos con este autor</h3></div>';
					}
				}
				echo '</div>';
				echo '</div>';