<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="four columns">
<?php
if($id3!=0){
?>				<a
					href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id2 ?>">
					<i class="icon-arrow-left"></i> Regresar
				</a>
<?php }else{ ?>
<a
					href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $this->id2 ?>">
					<i class="icon-arrow-left"></i> Regresar
				</a>

				<?php
			}
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/camposaddproy/index/' . $this->id . '/' . $this->id2. '/' . $this->id3,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    
    echo '<p>';
    echo $this->formlabel($form->get('valor'));
    echo $this->formelement($form->get('valor'));
    echo '<p>';
    
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>

				<?php
    
    ?>

				</div>
			</div>
		</div>
	</div>
</div>