<style>
    .filter-cons input[type="text"],select{
        width: 100%;
    }
    .filter-cons {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-cons-left {float: left;}
    .filter-cons-right {float:right;}
    .filter-cons .btn {width: 275px;}
    .filter-cons .dropdown {display: inline;}
    .filter-cons .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
    .dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
    <div class="filter-cons">
        <div class="filter-cons-left"><h4><?php echo $this->titulo; ?></h4></div>
        <div class="filter-cons-right">
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/consultamonitores/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
            <div class="dropdown">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-menu-inner">
                        <?php                               
                        $form = $this->form;
                        $form->prepare ();
                        $form->setAttributes(array(
                            'action' => 'index',
                            'method' => 'post'
                        ));
                        echo $this->form ()->openTag ( $form );
                        echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
                        echo $this->formlabel($form->get('id_convocatoria'));
                        echo $this->formelement($form->get('id_convocatoria'));
                        echo $this->formlabel($form->get('codigo_proyecto'));
                        echo $this->formelement($form->get('codigo_proyecto'));
                        echo $this->formlabel($form->get('nombre_proyecto'));
                        echo $this->formelement($form->get('nombre_proyecto'));
                        echo $this->formelement($form->get('submit'));
                        echo $this->form ()->closeTag ( $form );
                        ?>
                    </div>                      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col col100 noshadow">
<?php
echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
echo '<table class="table" style="width: 100%; max-width: 100%;">';
echo "<thead>";
echo "<th style='width: 5%;'>#</th>";
echo "<th style='width: 5%;'>ID convocatoria</th>";
echo "<th style='width: 10%;'>Código proyecto</th>";
echo "<th style='width: 10%;'>Nombre del proyecto / Semillero de investigación</th>";
echo "<th style='width: 10%;'>Investigador principal / Coordinadores</th>";
echo "<th style='width: 10%;'>Monitor</th>";
echo "<th style='width: 25%;'>Estado de aprobación de monitoria</th>";
echo "<th style='width: 25%;'>Observaciones de la aprobación</th>";
echo "<th style='width: 5%;'>Verificar productos</th>";
echo '</thead>';
echo '<tbody>';
$cont_number = 1;
$band=true;
foreach ( $this->datosAplicarm as $dato ) {
	$codProyecto="";
	$nombProyecto="";
	$InvesProyecto="";
	$NumPlazasProyecto="";
	foreach ($proyinvest as $proInvesti) {
		if($dato["id_proyecto"] == $proInvesti["id_proyecto_inv"]){
			$codProyecto = strstr($proInvesti ["nombre_proyecto"], '-/-', true);
			foreach ($prT as $proyeT){
			    if($codProyecto == trim($proyeT["codigo_proy"])){
			        $nombProyecto=$proyeT["nombre_proy"];
					$InvesProyecto=$proyeT["id_investigador"];
					$NumPlazasProyecto=$proInvesti["cantidad_plazas"];
					break;
			    }	
			}
			break;
		}
	}			        
	if($this->id_user == $dato["id_usuario"] || $this->menu == 1 || $this->id_user == $InvesProyecto){		        
		if ($dato["id_usuario"]==null || $dato["estado_seleccionado"]!="Seleccionado"){
	 			continue;
		}
		if ($this->buscar=="Si"){
			if($this->dataBuscar["id_convocatoria"] != "" && $dato["id_convocatoria"] != $this->dataBuscar["id_convocatoria"]){
				continue;
			}
			if($this->dataBuscar["codigo_proyecto"] != "" && strpos(strtoupper($codProyecto), strtoupper($this->dataBuscar["codigo_proyecto"]))===FALSE){
				continue;
			}
			if($this->dataBuscar["nombre_proyecto"] != "" && strpos(strtoupper($nombProyecto), strtoupper($this->dataBuscar["nombre_proyecto"]))===FALSE){
				continue;
			}
							
		}

		echo '<tr>';
		echo '<td>';
		echo $cont_number;
		$cont_number=$cont_number+1;
		echo '</td>';
		echo '<td>';
		echo $dato["id_convocatoria"];
		echo '</td>';
		echo '<td>';
		echo $codProyecto;
		echo '</td>';
		echo '<td>';
		echo $nombProyecto;
		echo '</td>';
		echo '<td style="text-align:center;">';
		foreach ($this->usu as $usuaT) {
            if($usuaT["id_usuario"] == $InvesProyecto){
                echo trim($usuaT["primer_nombre"])." ".trim($usuaT["segundo_nombre"])." ".trim($usuaT["primer_apellido"])." ".trim($usuaT["segundo_apellido"]);
                btrsk;
            }
        }
		echo '</td>';
		echo '<td>';
		echo $dato["nombre"];
        echo '</td>';
        echo '<td>';
		echo $dato["estado_aprobacion"];
		echo '</td>';
		echo '<td>';
		echo $dato["obervaciones_aprobacion"];
		echo '</td>';
		echo '<td style="text-align:center;">';
		if($this->menu == 1 || $this->id_user == $InvesProyecto || $this->id_user == $dato["id_usuario"]){
								?>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/aprobacionm/index/<?php echo $dato["id_aplicar"]?>">Verificar</a>
								<?php 
		}
		echo '</td>';
		}
		$band=false;
	}
	echo '</tr>';
	echo '</table>';
	echo '</div>';
	if($band){
		if($this->dataBuscar["id_convocatoria"]){
			echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos monitores para este Id de convocatoria</h3></div>';
		}else if($this->dataBuscar["codigo_proyecto"]){
			echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos monitores para este código del proyecto</h3></div>';
		}else{
			echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos monitores para este nombre del proyecto</h3></div>';
		}
	}
?>
</div>
