<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
					
					<a
    					href="<?php echo $this->basePath() ?>/application/evaluarproy/index">
    					<i class="icon-arrow-left"></i> Regresar
    				</a>
					
        			<?php
                
                        $form = $this->form;
                        $form->prepare();
                        $form->setAttributes(array(
                            'action' => 'index',
                            'method' => 'post'
                        ));
                        echo $this->form()->openTag($form);
                        echo $this->form()->closeTag($form);
                        ?>
                
                		<?php
                        $total = 0;
                        foreach ($this->datos as $dato) {
                            $total = $total + $dato["id_ponderacion2"];
                        }
                        echo 'Total Promedio : ' . $total . ' Sobre 100';
                        echo '<br>';
                        echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                        echo '<table class="table" style="width: 100%; max-width: 100%;">';
                        echo '<thead>';
                        echo '<th style="width: 35%;">Descripción</th>';
                        echo '<th style="width: 10%;">Puntos Asignados</th>';
                        echo '<th style="width: 10%;">Puntos Evaluador</th>';
                        echo '<th style="width: 35%;">Razones/Observaciones de la Evaluación</th>';
                        echo '<th style="width: 10%;">Evaluar Aspecto</th>';
                        
                        echo '</thead>';
                        echo '<tbody>';
                        foreach ($this->datos as $dato) {
                            echo '<tr>';
                            echo '<td>';
                            echo $dato["descripcion"];
                            echo '</td>';
                            echo '<td>';
                            echo $dato["id_ponderacion1"];
                            echo '</td>';
                            echo '<td>';
                            echo $dato["id_ponderacion2"];
                            echo '</td>';
                            echo '<td>';
                            echo $dato["observaciones"];
                            echo '</td>';
                            echo '<td>';
                            ?>
                    					<a class="btn"
                    						href="<?php echo $this->basePath() ?>/application/editarevaluar/index/<?php echo $dato["id_aspecto"];?>/<?php echo $this->id; ?>">Evaluar
                    						Aspecto</a>
                    				<?php
                            echo '</td>';
                            echo '</tr>';
                        }
                        
                        echo '</tr>';
                        echo '</table>';
                        echo '</div>';
                        echo '<br />';
				    ?>

				</div>
			</div>
		</div>
	</div>
</div>