<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
                				<?php
                                echo $this->titulo;
                                ?>
							</h3>
						</div>
					</div>
				</div>
				
				<center>
					<ul class="nav nav-pills">
					  <li role="presentation" class="active">
					  		<a href="<?php echo $this->basePath() ?>/application/convocatoriai/index">Convocatoria de Investigación Interna
							</a>
						</li>
					  <li role="presentation" class="active">
					  		<a href="<?php echo $this->basePath() ?>/application/convocatoriae/index">Convocatoria de Investigación Externa
							</a>
						</li>
					  <li role="presentation" class="active">
					  		<a href="<?php echo $this->basePath() ?>/application/convocatoriam/index">Convocatoria Monitores
							</a>
						</li>
						<li role="presentation" class="active">
					  		<a href="<?php echo $this->basePath() ?>/application/convocatorias/index">Convocatoria Especial
						</a>
						</li>
					</ul>
					<!--<div class="three columns">


						<a class="btn"
							href="<?php echo $this->basePath() ?>/application/convocatoriai/index">Convocatoria de Investigación Interna
						</a>
					</div>
					<div class="three columns">
						<a class="btn"
							href="<?php echo $this->basePath() ?>/application/convocatoriae/index">Convocatoria de Investigación Externa
						</a>
					</div>
					<div class="three columns">
						<a class="btn"
							href="<?php echo $this->basePath() ?>/application/convocatoriam/index">Convocatoria Monitores
						</a>
					</div>
					<div class="three columns">
						<a class="btn"
							href="<?php echo $this->basePath() ?>/application/convocatorias/index">Convocatoria Especial
						</a>
					</div>-->
				</center>
			</div>
		</div>
	</div>

</div>