<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }
    input {
        width: 60%;
        max-width: 60%;
    }
    select {
        width: 60%;
        max-width: 60%;
    }
    .alineadoDerecha {
        float: right;
    }
</style>
<script type="text/javascript">
	function showHint1(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#autor>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/repositorio/index">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('nombre'));
echo $this->formelement($form->get('nombre'));
echo '<p>';
echo $this->formlabel($form->get('id_autor'));
echo $this->formelement($form->get('id_autor'));
echo '</br>';
echo $this->formelement($form->get('autor'));
echo '</div>';
echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_tipo'));
echo $this->formelement($form->get('id_tipo'));
echo '<p>';
echo $this->formlabel($form->get('url'));
echo $this->formelement($form->get('url'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('descripcion'));
echo $this->formelement($form->get('descripcion'));
echo '<p>';
echo $this->formlabel($form->get('otra_informacion'));
echo $this->formelement($form->get('otra_informacion'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));
echo '</div>';

echo '<div class="six columns">';
echo '<div class="alineadoDerecha">';

echo $this->formelement($form->get('submit'));
echo '</div>';
echo '</div>';



echo '<div>';

echo '</div>';

echo $this->form()->closeTag($form);
?>				
</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>

