<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
            				<?php echo $this->titulo; ?>
            				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
                <a
					href="<?php echo $this->basePath() ?>/application/asignareval/index">
					<i class="icon-arrow-left"></i> Regresar
				</a>
								<?php
        
        $form = $this->form;
        $form->prepare();
        $form->setAttributes(array(
            'action' => $this->url . '/application/editareval/index/' . $this->id . '/' . $this->id2 . '/' . $this->id3,
            'method' => 'post'
        ));
        echo $this->form()->openTag($form);
        echo '<h6>';
        echo $this->flashMessenger()->render();
        echo '</h6>';
        if ($this->id2 != "concepto") {
            echo '<p>';
            echo $this->formlabel($form->get('fecha_maxima'));
            echo $this->formelement($form->get('fecha_maxima'));
        } else {
            echo '<p>';
            echo $this->formlabel($form->get('descripcion'));
            echo $this->formelement($form->get('descripcion'));
        }
        
        echo '<p>';
        
        echo $this->formelement($form->get('submit'));
        
        echo '<br>';
        
        echo $this->form()->closeTag($form);
        ?>


</div>
			</div>
		</div>
	</div>
</div>