<style>
	.filter-group input[type="text"],select{
		width: 100%;
	}
	.filter-group {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-group-left {float: left;}
	.filter-group-right {float:right;}
	.filter-group .btn {width: 275px;}
	.filter-group .dropdown {display: inline;}
	.filter-group .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-group">
		<div class="filter-group-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-group-right">
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/grupoinv/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php								
						$form = $this->form;
						$form->prepare ();
						$form->setAttributes(array(
							'action' => 'index',
							'method' => 'post' 
						));
						echo $this->form ()->openTag ( $form );
						echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
						echo $this->formlabel ( $form->get('nombre_grupo'));
						echo $this->formelement ( $form->get('nombre_grupo'));
						echo $this->formlabel ( $form->get ( 'id_unidad_academica' ) );
						echo $this->formelement ( $form->get ( 'id_unidad_academica' ) );
						echo $this->formlabel ( $form->get ( 'id_dependencia_academica' ) );
						echo $this->formelement ( $form->get ( 'id_dependencia_academica' ) );
						echo $this->formlabel ( $form->get ( 'id_programa_academico' ) );
						echo $this->formelement ( $form->get ( 'id_programa_academico' ) );
						echo $this->formelement ( $form->get ( 'submit' ) );
 						echo $this->form ()->closeTag ( $form );
 						?>
					</div>						
				</div>
			</div>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/creargrupoinvestigacion/index"><i class="fa fa-users" style="margin-right: 5px;"></i>Crear grupo</a>
		</div>
	</div>
</div>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
		<table class="table" style="width: 100%; max-width: 100%;">
			<thead>
				<tr>
					<th style="width:5%">Nombre del Grupo</th>
					<th style="width:5%">Fecha Creaci&#243;n</div>
					<th style="width:5%">Clasificaci&#243;n</th>
					<th style="width:5%">L&#237;der</th>
					<th style="width:5%">Estado</th>
					<th style="width:5%">Acciones</th>
				</tr>
			</thead>
			<tbody>
			<?php 
					$band=true;
					foreach ( $this->datos as $dato ) : ?>
				<?php if ($dato ["id_lider"] == $this->id_user || $this->menu == 1) { $band=false; ?>

					<tr>
						<td><?php echo $dato ["nombre_grupo"] ?></td>
						<td>
							<?php 
							$fecha = explode(" ", $dato ["fecha_creacion"]);
							echo $fecha[0]; 
							?>
						</td>
						<td>
							<?php
							foreach ( $this->d_val as $vf ) {
								if ($vf ["id_valor_flexible"] == $dato ["id_clasificacion"]) {
									echo $vf ["descripcion_valor"];
								}
							}
							?>
						</td>
						<td>
							<?php
								if($dato ["id_lider"] == 0){
									echo "Sin asignar";
								}else{
									foreach ( $this->d_user as $vf ) {
										if ($vf ["id_usuario"] == $dato ["id_lider"]) {
											echo $vf ["primer_nombre"] . ' ' . $vf ["segundo_nombre"] .' ' .$vf ["primer_apellido"] . ' ' . $vf ["segundo_apellido"];
										}
									}
								}
							?>
						</td>
						<td>
							<?php
								if ($dato ["estado"] == 'A' || $dato ["estado"] == 'a') {
									echo 'Activo';
							}
							if ($dato ["estado"] == 'I' || $dato ["estado"] == 'i') {
								echo 'Inactivo';
							}
							?>
						</td>
						<td>
							<?php if ($this->menu == 1) { ?>
							<a class="btn" href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $dato["id_grupo_inv"];?>"><i class="fa fa-pencil"></i></a>
							<?php }else{ if($dato["estado"]!="I"){?>
							<a class="btn" href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $dato["id_grupo_inv"];?>"><i class="fa fa-pencil"></i></a>
							<?php }} ?>
							<?php if ($this->menu == 1) { ?>
							<a class="btn"	href="<?php echo $this->basePath() ?>/application/editargrupoinv/del/<?php echo $dato["id_grupo_inv"];?>"><i class="fa fa-trash"></i></a>
							<?php } ?>
						</td>
					</tr>
				<?php } ?>
			<?php endforeach; ?>
			</tbody>
		</table>		
			<?php 
				if($band){
					if($this->data["nombre_grupo"]){
						echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos grupos con este nombre</h3></div>';
					}else{
						echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos grupos con estos parametros de búsqueda</h3></div>';
					}
				}

			?>
	</div>
</div>

