<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('sesion'));
echo $this->formelement($form->get('sesion'));
echo '<p>';
echo $this->formlabel($form->get('fecha'));
echo $this->formelement($form->get('fecha'));
echo '<p>';
echo $this->formlabel($form->get('fecha_fin'));
echo $this->formelement($form->get('fecha_fin'));
echo '<p>';
echo $this->formlabel($form->get('id_rol'));
echo $this->formelement($form->get('id_rol'));
echo '</br>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '</br>';
echo '</br>';

echo $this->form()->closeTag($form);
?>				
</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>
