<style>
    .filter-cons input[type="text"],select{
        width: 100%;
    }
    .filter-cons {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-cons-left {float: left;}
    .filter-cons-right {float:right;}
    .filter-cons .btn {width: 275px;}
    .filter-cons .dropdown {display: inline;}
    .filter-cons .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
    .dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
    <div class="filter-cons">
        <div class="filter-cons-left"><h4><?php echo $this->titulo; ?></h4></div>
        <div class="filter-cons-right">
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/editarproyecto/index/<?php echo $this->grupo; ?>"><i class="icon-arrow-left"></i> Regresar</a>
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/gruposproy/index/<?php echo $this->grupo; ?>"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
            <div class="dropdown">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-menu-inner">
                        <?php                               
                        $form = $this->form;
                        $form->prepare ();
                        $form->setAttributes(array(
                            'action' => $this->basePath() . '/application/gruposproy/index/' . $this->id,
                            'method' => 'post'
                        ));
                        echo $this->form ()->openTag ( $form );
                        echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
                        echo $this->formlabel($form->get('nombre_grupo'));
                        echo $this->formelement($form->get('nombre_grupo'));
                        echo $this->formelement($form->get('submit'));
                        echo $this->form ()->closeTag ( $form );
                        ?>
                    </div>                      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col col100 noshadow">
    <table class="table" style="width: 100%; max-width: 100%;">
        <thead>
            <tr>
                <th>Grupo</th>
                <th>Código</th>
                <th>Asignar grupo</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->datos as $dato) { ?>
            <tr>
                <td><?php echo $dato["nombre_grupo"]; ?></td>
                <td><?php echo $dato["cod_grupo"]; ?></td>
                <td>
                    <a class="btn" href="<?php echo $this->basePath() ?>/application/gruposproy/asignar/<?php echo $dato["id_grupo_inv"];?>/<?php echo $this->grupo ?>">Asignar Grupo</a>
                </td>
            </tr>
        </tbody>
        <?php } ?>
    </table>
</div>
