<script>
$(function () {
    var opts = $('#descripcion option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput').keyup(function () {
        var rxp = new RegExp($('#someinput').val(), 'i');
        var optlist = $('#descripcion').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });

    });

});
</script>
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
					<a
						href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>

	<?php
echo '<br>';
echo '<br>';
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<p>';
echo $this->formlabel($form->get('descripcion'));
echo '<input id="someinput">';
echo '<p>';
echo $this->formelement($form->get('descripcion'));
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));

echo '<p>';
echo '<br>';
echo $this->formelement($form->get('submit'));
echo '<br>';

echo $this->form()->closeTag($form);
?>
				<br>


				<?php
    
    ?>

</div>
			</div>
		</div>
	</div>
</div>