<style>
    .alineadoDerecha {
        float: right;
    }
</style>
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
    <div id="container_1">
<div class="row2">
    <div class="nine3 columns">
        <div id="centersectiontitle">
            <div class="twelve columns">
                <div class="sidebartitle"><h3>
                <?php
                    echo $this->titulo;
                ?>
                </h3>
            </div>
        </div>
    </div>
<div class="twelve columns">
<a href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id; ?>">
    <i class="icon-arrow-left"></i>
     Regresar</a>

    <?php
echo '<br>';echo '<br>';
                $form = $this->form;
                $form->prepare();

                $form->setAttributes(array('action'=> $this->url.'/application/formacionacahv/index/'.$this->id.'/'.$this->id2,
                                        'method'=>'post'));
                echo $this->form()->openTag($form);
                echo "</div>";
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('tipo_formacion'));
                echo $this->formelement($form->get('tipo_formacion'));
                echo '<p>';
                echo $this->formlabel($form->get('nombre_formacion'));
                echo $this->formelement($form->get('nombre_formacion'));
                echo '<p>';
                echo $this->formlabel($form->get('titulo_formacion'));
                echo $this->formelement($form->get('titulo_formacion'));
                echo '<p>';
                echo $this->formlabel($form->get('institucion'));
                echo $this->formelement($form->get('institucion'));                
                echo '<p>';
                echo $this->formlabel($form->get('fecha_grado'));
                echo $this->formelement($form->get('fecha_grado'));
                echo '<p>';
                echo $this->formlabel($form->get('image-file'));
                echo $this->formelement($form->get('image-file'));
                echo "</div>";
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('fecha_inicio'));
                echo $this->formelement($form->get('fecha_inicio'));
                echo '<p>';
                echo $this->formlabel($form->get('fecha_fin'));
                echo $this->formelement($form->get('fecha_fin'));
                echo '<p>';
                echo $this->formlabel($form->get('horas'));
                echo $this->formelement($form->get('horas'));
                echo '<p>';
                echo $this->formlabel($form->get('pais'));
                echo $this->formelement($form->get('pais'));
                echo '<p>';
                echo $this->formlabel($form->get('ciudad'));
                echo $this->formelement($form->get('ciudad'));
                
                echo '<p>';
                echo '<br>';
                echo '<center>';
                echo $this->formelement($form->get('submit'));
                 echo "</center>";
                echo $this->form()->closeTag($form);
                 echo "</div>";

                 echo "<legend>.</legend>";
                ?>
                <br>
</div></div></div>