<?php
$output = fopen('php://output', 'w');

// output the column headings
header('Content-Type: application/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=semilleros.csv');

fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
fputcsv($output, array("Reporte de Semilleros/Otros procesos de formacion"));
fputcsv($output, array(""));
fputcsv($output, array(""));

if(count($this->datos)<=0){
    fputcsv($output, array("No se encontraron resultados."),';');
}else{
    foreach($this->datos as $dato){
        fputcsv($output, array("Nombre del Semillero / Otros procesos de formación: ".trim($dato["nombre"])),';');
        fputcsv($output, array(""));

        fputcsv($output, array("Datos Generales  del Semillero / Otros procesos de formación:"),';');
        $encabezado = array();
        $encabezado["1"] = "Codigo";
        $encabezado["2"] = "Fecha de creación";
        $encabezado["3"] = "Coordinador 1";
        $encabezado["4"] = "Coordinador 2";
        $encabezado["5"] = "Estado";
        $encabezado["6"] = "Unidad";
        $encabezado["7"] = "Dependencia";
        $encabezado["8"] = "Programa";
        $encabezado["9"] = "Objetivo general";
        $encabezado["10"] = "Objetivos especificos";
        $encabezado["11"] = "Temática general (Obligatorio) y línea de investigación (si aplica)";

        fputcsv($output, $encabezado,';');
        $encabezado = array();
        $encabezado["1"] = trim($dato["codigo"]);
        $encabezado["2"] = trim($dato["fecha_creacion"]);
        foreach ($this->usuarios as $us) {
            if ($dato["coordinador_uno"] == $us["id_usuario"]) {
                $encabezado["3"] = trim($us["primer_nombre"]).' '.trim($us["segundo_nombre"]).' '.trim($us["primer_apellido"]).' '.trim($us["segundo_apellido"]);
            }
        }
        foreach ($this->usuarios as $us) {
            if ($dato["coordinador_dos"] == $us["id_usuario"]) {
                $encabezado["4"] = trim($us["primer_nombre"]).' '.trim($us["segundo_nombre"]).' '.trim($us["primer_apellido"]).' '.trim($us["segundo_apellido"]);
            }
        }
        $encabezado["5"] = trim($dato["estado"]);;
        foreach ($this->valflex as $us) {
            if ($dato["id_unidad_academica"] == $us["id_valor_flexible"]) {
                $encabezado["6"] = trim($us["descripcion_valor"]);
            }
        }
        foreach ($this->valflex as $us) {
            if ($dato["id_dependencia_academica"] == $us["id_valor_flexible"]) {
                $encabezado["7"] = trim($us["descripcion_valor"]);
            }
        }
        foreach ($this->valflex as $us) {
            if ($dato["id_programa_academico"] == $us["id_valor_flexible"]) {
                $encabezado["8"] = trim($us["descripcion_valor"]);
            }
        }
        $encabezado["9"] = trim($dato["objetivo_general"]);
        $encabezado["10"] = trim($dato["objetivo_especifico"]);
        $encabezado["11"] = trim($dato["actividades"]);
        fputcsv($output, $encabezado,';');
        fputcsv($output, array(""));

        fputcsv($output, array("Integrantes"),';');
        $encabezado = array();
        $encabezado["1"] = "Nombre del integrante";
        $encabezado["2"] = "Correo institucional";
        $encabezado["3"] = "Tipo de vinculación";
        $encabezado["4"] = "Fecha de vinculación";
        $encabezado["5"] = "Fecha fin de Vinculación";
        $encabezado["6"] = "Rol participación";
        
        fputcsv($output, $encabezado,';');
        $encabezado = array();
        foreach ($this->intSemi as $semi) {
            if ($dato["id"] == $semi["id_semillero"]) {
                foreach ($this->usuarios as $us) {
                    if ($semi["integrante"] == $us["id_usuario"]) {
                        $encabezado["1"] = trim($us["primer_nombre"]).' '.trim($us["segundo_nombre"]).' '.trim($us["primer_apellido"]).' '.trim($us["segundo_apellido"]);
                        $encabezado["2"] = $us["email"];
                    }
                }

                foreach ($this->valflex as $us) {
                    if ($semi["tipo_vinculacion"] == $us["id_valor_flexible"]) {
                        $encabezado["3"] = trim($us["descripcion_valor"]);
                    }
                }

                $encabezado["4"] = $semi["fecha_inicio"];
                $encabezado["5"] = $semi["fecha_fin"];
                foreach ($this->valflex as $us) {
                    if ($semi["rol_participacion"] == $us["id_valor_flexible"]) {
                        $encabezado["6"] = trim($us["descripcion_valor"]);
                    }
                }
            }
        }
        fputcsv($output, $encabezado,';');
        fputcsv($output, array(""));

        fputcsv($output, array("Grupos de investigación al que se encuentra articulado el semillero"),';');
        $encabezado = array();
        $encabezado["1"] = "Nombre del grupo";
        $encabezado["2"] = "Codigo";
        $encabezado["3"] = "Lider";
        $encabezado["4"] = "Descripción";
        fputcsv($output, $encabezado,';');
        $encabezado = array();
        foreach ($this->gruposSemi as $grupos) {
            if ($dato["id"] == $grupos["id_semillero"]) {
                foreach ($this->grupoinv as $grupoinv) {
                    if ($grupos["id_grupo"] == $grupoinv["id_grupo_inv"]) {
                        $encabezado["1"] = trim($grupoinv["nombre_grupo"]);
                        $encabezado["2"] = trim($grupoinv["cod_grupo"]);
                        foreach ($this->usuarios as $us) {
                            if ($grupoinv["id_lider"] == $us["id_usuario"]) {
                                $encabezado["3"] = trim($us["primer_nombre"]).' '.trim($us["segundo_nombre"]).' '.trim($us["primer_apellido"]).' '.trim($us["segundo_apellido"]);
                            }
                        }
                        $encabezado["4"] = trim($grupoinv["descripcion"]);
                    }
                }
            }
        }
        fputcsv($output, $encabezado,';');
        fputcsv($output, array(""));
        fputcsv($output, array(""));


    }
}
fclose($output);

?>