<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }

    .alineadoDerecha {
        float: right;
    }
</style>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editarredinv/index/<?php echo $this->red; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="twelve columns">';
echo $this->formlabel($form->get('nombre'));
echo $this->formelement($form->get('nombre'));
echo '<p>';
echo $this->formlabel($form->get('codigo'));
echo $this->formelement($form->get('codigo'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_inicio'));
echo $this->formelement($form->get('fecha_inicio'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_fin'));
echo $this->formelement($form->get('fecha_fin'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('resumen'));
echo $this->formelement($form->get('resumen'));

echo '<p>';
echo $this->formlabel($form->get('objetivo'));
echo $this->formelement($form->get('objetivo'));

echo '<p>';
echo $this->formlabel($form->get('productos'));
echo $this->formelement($form->get('productos'));

echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));

echo '</br>';
echo '<div>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '</div>';

echo $this->form()->closeTag($form);
?>				
</br>
</br>
</br>
<legend>.</legend>

</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>