<style>
	[type|="checkbox"] {
    	vertical-align: baseline;
    }

	label[for=seleccionados]{
       display: inline-block;
       margin-left: 15px;
    }
    
    label[for=elegibles]{
       display: inline-block;
       margin-left: 15px;
    }
</style>


<?php 
	//ini_set( 'default_charset', "ISO-8859-1" );
	header('Content-type: text/html; charset=ISO-8859-1' , true );
	if ($this->pdf == 'S') { ?>
	<style>
	    .container {
			width: 1000px;
			margin: auto;
			padding: 10px;
			border: 0px solid #000;
		}

		body {
			font-family: Arial, sans-serif;
		}

		html {
			margin: 10px;
			padding: 10px;
		}

		body {
			font-family: dejavu sans, Arial;
			font-size: 0.85em;
		}

		.bold {
			font-weight: bold;
		}

		.font-xxl {
			font-size: 0.4em;
		}

		.font-l {
			font-size: 1.5em;
		}

		.font-n {
			font-size: 0.8em;
		}

		.font-s {
			font-size: 0.6em;
		}

		.font-middle {
			text-align: center;
		}

		.page-wrap {
			padding: 0px;
			margin: 0px;
		}

		table {
			width: 100%;
			border-collapse: collapse;
			margin: 5px 1px 5px 1px;
		}

		td, th {
			border: 1px solid black;
			padding: 1px 1px 1px 1px;
		}

		.brdr-top {
			border-top: 1px solid black;
		}

		.brdr-bottom {
			border-bottom: 1px solid black;
		}

		.brdr-left {
			border-left: 1px solid black;
		}

		.brdr-right {
			border-right: 1px solid black;
		}

		.bordreless td, .bordreless th {
			border: 0px thin #ffffff;
		}
	</style>
		<p>_____________________________________________________________________________________________</p>
			<h1>MONITORES</h1>
		<p>_____________________________________________________________________________________________</p>
		<br>
		<table>
			<tbody>
				<tr>
					<td class="bold">No.</td>
					<td class="bold">Código proyecto</td>
					<td class="bold">Nombre del proyecto / Semillero de investigación / Grupo de estudio</td>
					<td class="bold">Investigador principal / Coordinador(es)</td>
					<td class="bold">Nombre completo</td>
					<td class="bold">Número de documento de identidad</td>
					<td class="bold">Número de teléfono celular</td>
					<td class="bold">Correo electrónico</td>
				</tr> 
				<?php
			        $sum = 0;
			        $cont=1;
			        foreach ($this->datos as $dato){
			        	if($this->seleccionados==1){
			        		if($dato["estado_seleccionado"]!="Seleccionado"){
			        			 continue;
			        		}
			        	}

			            foreach ($this->usuarios as $us) {
			                if ($dato["id_usuario"] == $us["id_usuario"]) {
			                    $nom = utf8_decode(trim($us["primer_nombre"]).' '.trim($us["segundo_nombre"]).' '.trim($us["primer_apellido"]).' '.trim($us["segundo_apellido"]));
			                    $doc = $us["documento"];
			                    $cel = $us["celular"];
			                    $email = $us["email"];
			                }
			            }
			            $sum = $sum + 1;
			            
			            foreach ($this->proy as $p) {
			                if ($dato["id_proyecto"] == $p["id_proyecto_inv"]) {
			                    $n_proy = $p["nombre_proyecto"];
			                }
			            }
			            echo "<tr>";
			            echo "<td>".utf8_decode($dato["id_aplicar"])."</td>"; 
			            $codProyecto = strstr($n_proy, '-/-', true);
			            echo "<td>".utf8_decode($codProyecto)."</td>"; 
			            echo "<td>".utf8_decode(substr(strstr($n_proy, '-/-'),3,strlen(strstr($n_proy, '-/-'))))."</td>"; 
			            echo "<td>";
						foreach ($prT as $proyeT){
			                if($codProyecto == trim($proyeT["codigo_proy"])){
			                    foreach ($this->usuarios as $usua){
			                        if($proyeT["id_investigador"] == $usua["id_usuario"]){
			                            echo utf8_decode(trim($usua["primer_nombre"])." ".trim($usua["segundo_nombre"])." ".trim($usua["primer_apellido"])." ".trim($usua["segundo_apellido"]));
			                        }
			                    }
			                }
			            }
			            echo "</td>";
						echo "<td>".utf8_decode($nom)."</td>";
						echo "<td>".utf8_decode($doc)."</td>";
						echo "<td>".utf8_decode($cel)."</td>";
						echo "<td>".utf8_decode($email)."</td>";
						
			            echo "</tr>";
			        }
				echo "</tbody>";
		echo "</table>";
		echo 'Total: ' . $sum;
	?>

<?php
	} else { 
		include("public/menu.php"); 
		?>
		<div id="wrapper_1">
			<div id="container_1">
				<div class="row2">
					<div class="nine3 columns">
						<div id="centersectiontitle">
							<div class="twelve columns">
								<div class="sidebartitle">
									<h3>
	                					<?php echo utf8_decode($this->titulo); ?>
									</h3>
								</div>
							</div>
						</div>
						<!-- FILTROS -->
						<div class="twelve columns">
							<a href="<?php echo $this->basePath() ?>/application/reportes/index"><i class="icon-arrow-left"></i> Regresar</a><br> <br>
					<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/pdfmonitores/index',
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo '<p>';
    echo $this->formlabel($form->get('facultad'));
    echo $this->formelement($form->get('facultad'));
    echo '<p>';
    echo $this->formlabel($form->get('programa'));
    echo $this->formelement($form->get('programa'));
    echo '<p>';
    echo $this->formelement($form->get('elegibles'));
    echo $this->formlabel($form->get('elegibles'));
    echo '<p>';
    echo $this->formelement($form->get('seleccionados'));
    echo $this->formlabel($form->get('seleccionados'));
    echo '<p>';
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>
									</div>
								</div>
							</div>
						</div>
					</div>

<?php }?>

