<script type="text/javascript">
	$(function () {
	    var opts = $('#id_autor option').map(function () {
	        return [[this.value, $(this).text()]];
	    });
	    $('#filtro_autor').keyup(function () {
	    	console.log(2);
	        var rxp = new RegExp($('#filtro_autor').val(), 'i');
	        var optlist = $('#id_autor').empty();
	        opts.each(function () {
	            if (rxp.test(this[1])) {
	                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
	            }
	        });

	    });
	});
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
				<a href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</br>
				</br>


				</div>

				<div class="six columns">


	<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url . '/application/articulos/index/' . $this->id .'/'. $this->id2,
    'method' => 'post'
));
echo $this->form()->openTag($form);
echo '<p>';
echo $this->formlabel($form->get('nombre_revista'));
echo $this->formelement($form->get('nombre_revista'));
echo '<p>';
echo $this->formlabel($form->get('ano'));
echo $this->formelement($form->get('ano'));
echo '<p>';
echo $this->formlabel($form->get('id_pais'));
echo $this->formelement($form->get('id_pais'));
echo '<p>';
echo $this->formlabel($form->get('issn'));
echo $this->formelement($form->get('issn'));
echo '<p>';
echo $this->formlabel($form->get('pagina_inicio'));
echo $this->formelement($form->get('pagina_inicio'));
echo '<p>';
echo $this->formlabel($form->get('fasciculo'));
echo $this->formelement($form->get('fasciculo'));
echo '<p>';
echo $this->formlabel($form->get('filtro_autor'));
echo $this->formelement($form->get('filtro_autor'));
echo '<p>';
echo $this->formlabel($form->get('id_autor'));
echo $this->formelement($form->get('id_autor'));
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));
echo '<p>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('nombre_articulo'));
echo $this->formelement($form->get('nombre_articulo'));
echo '<p>';
echo $this->formlabel($form->get('mes'));
echo $this->formelement($form->get('mes'));
echo '<p>';
echo $this->formlabel($form->get('id_ciudad'));
echo $this->formelement($form->get('id_ciudad'));
echo '<p>';
echo $this->formlabel($form->get('num_paginas'));
echo $this->formelement($form->get('num_paginas'));
echo '<p>';
echo $this->formlabel($form->get('pagina_fin'));
echo $this->formelement($form->get('pagina_fin'));
echo '<p>';
echo $this->formlabel($form->get('volumen'));
echo $this->formelement($form->get('volumen'));
echo '<p>';
echo $this->formlabel($form->get('serie'));
echo $this->formelement($form->get('serie'));
echo '<p>';
echo $this->formlabel($form->get('categoria'));
echo $this->formelement($form->get('categoria'));

echo '<br>';

echo $this->form()->closeTag($form);
?>
				<br>

				<?php
    
    ?>

</div>
			</div>
		</div>