<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">

		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>Eliminar el registro?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/url/eliminar/<?php echo $this->datos;?>/<?php echo $this->id2;?>">Eliminar Url</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editarconvocatoriai/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


