<? include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="five columns">
<a href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $this->grupo; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

	<?php
echo '<br>';echo '<br>';
				$form = $this->form;
				$form->prepare();

				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('nombre_grupo'));
				echo $this->formelement($form->get('nombre_grupo'));
				echo '<p>';
				
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


<a class="btn" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>
<?php

echo $this->form()->closeTag($form);
				echo '<br>';

?>				
				<br>

				<?php
				
echo '<table class="table">';
echo '<thead>';
				echo '<th>Grupo</th>';
				echo '<th>Código</th>';
				echo '<th></th>';
				echo '<th></th>';
echo '</thead>';
echo '<tbody>';
				foreach ($this->datos as $dato){
				echo '<tr>';
				echo '<td>';
					echo $dato["nombre_grupo"];
				echo'</td>';
				echo '<td>';
					echo $dato["cod_grupo"];
				echo'</td>';
				echo '<td>';
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/gruposrel/asignar/<?php echo $dato["id_grupo_inv"];?>/<?php echo $this->grupo ?>">Asignar Grupo</a>
				<?php
				echo'</td>';
				echo '</tr>';
				}
				
				echo '</tr>';
				echo '</table>';
echo '</div>';
				?>

</div></div></div>