<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
    <div id="container_1">
        <div class="row2">
            <div class="nine3 columns">
                <div id="centersectiontitle">
                    <div class="twelve columns">
                        <div class="sidebartitle">
                            <h3>
                            <?php
                                echo $this->titulo;
                            ?>
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="twelve columns">
                    <a
                        href="<?php echo $this->basePath() ?>/application/convocatoria/index">
                        <i class="icon-arrow-left"></i> Regresar
                    </a>
    <?php
echo '<br>';
echo '<br>';

$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url . '/application/convocatoriam/index/' . $this->id,
    'method' => 'post'
));
echo $this->form()->openTag($form);
echo '<div class="twelve columns" >';
echo '<p>';
echo $this->formlabel($form->get('titulo'));
echo $this->formelement($form->get('titulo'));
echo '<p>';
echo $this->formlabel($form->get('descripcion'));
echo $this->formelement($form->get('descripcion'));
echo '<p>';
echo $this->formlabel($form->get('observaciones'));
echo $this->formelement($form->get('observaciones'));
echo '<p>';
echo $this->formlabel($form->get('fecha_apertura'));
echo $this->formelement($form->get('fecha_apertura'));
echo '<p>';
echo $this->formlabel($form->get('fecha_cierre'));
echo $this->formelement($form->get('fecha_cierre'));
echo '<p>';
echo $this->formlabel($form->get('cronograma'));
echo $this->formelement($form->get('cronograma'));
echo '<p>';

echo $this->formelement($form->get('submit'));
echo $this->form()->closeTag($form);
echo '<br>';
?>          
</div>

</br>
</br>
</br>
            </div>
        </div>
    </div>
</div>