<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="four columns">
				<a
					href="<?php echo $this->basePath() ?>/application/editarconvocatoriai/index">
					<i class="icon-arrow-left"></i> Regresar
				</a>
				<?php
    
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/copiarconvocatoria/index/' . $this->id,
        'method' => 'post'
    ));
    
    echo $this->form()->openTag($form);
    echo '<h6>';
    echo $this->flashMessenger()->render();
    echo '</h6>';
    echo '<p>';
    echo $this->formlabel($form->get('titulo'));
    echo $this->formelement($form->get('titulo'));
    echo '<p>';
    
    echo $this->formelement($form->get('submit'));
    
    echo '<br>';
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>

				<?php
    
    ?>


</div>
			</div>
		</div>
	</div>
</div>