<style>
	a {
        width: 100% !important;
        max-width: 100% !important;
    }
</style> 

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="twelve columns">



<a class="btn" href="<?php echo $this->basePath() ?>/application/pdfgi/index">Reporte Grupos de Investigación</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/reportesemilleros/index">Reporte Semilleros</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/reporteredes/index">Reporte Redes</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/pdfmonitores/index">Reporte PDF de Monitores</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/excelsemillerostodo/index">Reporte Excel de semilleros</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/excelredestodo/index">Reporte Excel de redes</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/excelgrupostodo/index">Reporte Excel de grupos</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/Excelmonitores/index">Reporte EXCEL de Monitores</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/pdfsiafi/index">Reporte de Siafi</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/reporteconvocatoria/index">Reporte Convocatorias y  Proyectos Interno/Externo</a>
<br><br>
<a class="btn" href="<?php echo $this->basePath() ?>/application/reporteinvpre/index">Reporte Equipos de Investigación y Presupuesto</a>
<br><br>
</div>

</div></div></div>
