<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="five columns">
<a href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $this->id; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

	<?php
echo '<br>';echo '<br>';
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/asociaciones/index/'.$this->id.'/'.$this->id2,
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('nombre_asociacion'));
				echo $this->formelement($form->get('nombre_asociacion'));
				
				echo '<p>';
                echo $this->formlabel($form->get('image-file'));
                echo $this->formelement($form->get('image-file'));
				
				echo '<p>';
                echo '<br>';
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


				<?php
				

				?>

</div>
</div>
</div>