<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo "INSCRIPCIÓN PARA ASPIRANTES A MONITORIAS DE INVESTIGACIÓN";
    echo "</br>";
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/aplicarm/index/' . $this->id,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    ?>
        <a href="<?php echo $this->basePath() ?>/application/consulconvocatoria/index"><i class="icon-arrow-left"></i> Regresar</a><br><br>
    <?php
    echo '<p>';
    echo $this->formlabel($form->get('fecha'));
    echo $this->formelement($form->get('fecha'));
    echo '</div>';
    echo '<div class="six columns">';
    echo '<p>';
    echo $this->formlabel($form->get('primer_apellido'));
    echo $this->formelement($form->get('primer_apellido'));
    echo '<p>';
    echo $this->formlabel($form->get('nombres'));
    echo $this->formelement($form->get('nombres'));
    echo '<p>';
    echo $this->formlabel($form->get('cod_estudiante'));
    echo $this->formelement($form->get('cod_estudiante'));
    echo '<p>';
    echo $this->formlabel($form->get('id_facultad'));
    echo $this->formelement($form->get('id_facultad'));
    echo '<p>';
    echo $this->formlabel($form->get('direccion'));
    echo $this->formelement($form->get('direccion'));
    echo '<p>';
    echo $this->formlabel($form->get('celular'));
    echo $this->formelement($form->get('celular'));
    if($this->menu=="1"){
        echo '<p>';
        echo $this->formlabel($form->get('promedio_ponderado'));
        echo $this->formelement($form->get('promedio_ponderado'));
        echo '<p>';
        echo $this->formlabel($form->get('cumplimiento_conjunto'));
        echo $this->formelement($form->get('cumplimiento_conjunto'));
    }
    echo '<p>';
    echo $this->formlabel($form->get('semestre'));
    echo $this->formelement($form->get('semestre'));
    echo '</div>';
    echo '<div class="six columns">';
    echo '<p>';
    echo $this->formlabel($form->get('segundo_apellido'));
    echo $this->formelement($form->get('segundo_apellido'));
    echo '<p>';
    echo $this->formlabel($form->get('fecha_nacimiento'));
    echo $this->formelement($form->get('fecha_nacimiento'));
    echo '<p>';
    echo $this->formlabel($form->get('identificacion'));
    echo $this->formelement($form->get('identificacion'));
    echo '<p>';
    echo $this->formlabel($form->get('id_programa_curricular'));
    echo $this->formelement($form->get('id_programa_curricular'));
    echo '<p>';
    echo $this->formlabel($form->get('telefono'));
    echo $this->formelement($form->get('telefono'));
    echo '<p>';
    echo $this->formlabel($form->get('email'));
    echo $this->formelement($form->get('email'));
    if($this->menu=="1"){
        echo '<p>';
        echo $this->formlabel($form->get('creditos_aprobados'));
        echo $this->formelement($form->get('creditos_aprobados'));
        echo '<p>';
        echo $this->formlabel($form->get('creditos_programa'));
        echo $this->formelement($form->get('creditos_programa'));
    }
    echo '<p>';
    echo $this->formlabel($form->get('id_proyecto'));
    echo $this->formelement($form->get('id_proyecto'));
    echo "</div>";
    echo '<div class="twelve columns">';    
    echo "<h3>";
    echo "Escrito corto de tres párrafos (Describa su interés por participar en esta monitoría)";
    echo "</h3>";
    echo $this->formelement($form->get('justificacion'));
    echo $this->terminos;
    echo '</br>';
    echo '</br>';
    echo '<p>';
    echo $this->formelement($form->get('submit'));
    echo $this->form()->closeTag($form);
    echo "</div>";
    ?>
			</div>
		</div>
	</div>
</div>