<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }

</style>
<script type="text/javascript">
	function showHint1(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#coordinador_1>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
	function showHint2(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#coordinador_2>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="four columns">
<?php
echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';
?>
<a href="<?php echo $this->basePath() ?>/application/redesinv/index">
	<i class="icon-arrow-left"></i>
	 Regresar</a>
				<br>
				<br>
				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/crearredinvestigacion/index',
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('nombre_red'));
				echo $this->formelement($form->get('nombre_red'));
				echo '<p>';
				echo $this->formlabel($form->get('codigo_red'));
				echo $this->formelement($form->get('codigo_red'));
				echo '<p>';
				echo $this->formlabel($form->get('id_coordinador_1'));
				echo $this->formelement($form->get('id_coordinador_1'));
				echo $this->formelement($form->get('coordinador_1'));
				echo '<p>';
				echo $this->formlabel($form->get('id_coordinador_2'));
				echo $this->formelement($form->get('id_coordinador_2'));
				echo $this->formelement($form->get('coordinador_2'));
				echo '<p>';
				echo $this->formlabel($form->get('estado_red'));
				echo $this->formelement($form->get('estado_red'));
				echo '<p>';
				echo '<p>';
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>
</div></div></div>