<style>
    select{
        width:80%;
    }
    select{
        width:80%;
    }
    input[type=text]{
        width:80%;
    }
    input[type=number]{
        width:80%;
    }
    .alineadoDerecha {
        float: right;
        margin-right: 20%;
    }
    .titulos{
        color: red;
        font-size: 22px;
    }
</style>

<?php
	include("public/menu.php");
	require_once("public/rutas.php"); 
?>

<script>
$(function () {
    var opts = $('#id_grupo_inv option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput').keyup(function () {
        var rxp = new RegExp($('#someinput').val(), 'i');
        var optlist = $('#id_grupo_inv').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });

    });

});
</script>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
        <div class="twelve columns">
            <a href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id; ?>">
                <i class="icon-arrow-left"></i> Regresar
            </a>
        </div>
        </br></br>
	</div>
	<fieldset>
<div class="twelve columns">

				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(
					array(
						'action'=> $this->url.'/application/paresevaluadores/index/'.$id,
						'method'=>'post'
					)
				);
				echo $this->form()->openTag($form);
                echo '<div class="six columns">';
				echo '<p>';
				echo $this->formlabel($form->get('nombre'));
				echo $this->formelement($form->get('nombre'));
				echo '<p>';
				echo $this->formlabel($form->get('documento'));
				echo $this->formelement($form->get('documento'));
				echo '<p>';
				echo $this->formlabel($form->get('usuario'));
				echo $this->formelement($form->get('usuario'));
                echo '<p>';				
				echo $this->formelement($form->get('submit'));
				
                echo '</div>';
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('tema'));
                echo $this->formelement($form->get('tema'));
                echo '<p>';
                echo $this->formlabel($form->get('tipo_evaluador'));
                echo $this->formelement($form->get('tipo_evaluador'));
                echo '</div>';
                echo $this->form()->closeTag($form);
				?>
</div>
</fieldset>



				<?php

if($this->consulta==1){ 
    if($this->campos["nombre"]=="" && $this->campos["documento"]==""  && $this->campos["usuario"]==""  && $this->campos["tema"]==""  && $this->campos["tipo_evaluador"]==""){
        echo '<h3>Debe utilizar los filtros para cargar la información</h3>';
    }else{
        if($this->campos["tema"]==""){
            echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
            echo '<table class="table" style="width: 100%; max-width: 100%;">';
            echo '<thead>';
            echo '<th style="width: 80%;">Nombre</th>';
            echo '<th style="width: 20%;">Ver</th>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($this->datos as $datos){
                echo '<tr>';
                    echo '<td>';
                        echo $datos["primer_nombre"].' '.$datos["segundo_nombre"].' '.$datos["primer_apellido"].' '.$datos["segundo_apellido"];
                    echo '</td>';
                    echo '<td style="text-align:center;">';
                    ?>
                        <a class="btn" href="<?php echo $this->basePath() ?>/application/paresevaluadores/add/<?php echo $datos["id_usuario"];?>/<?php echo $id;?>">Agregar</a>
                    <?php
                    echo '</td>';
                echo '</tr>';
                
            }
            echo '</tbody>';
            echo '</table>';
            echo '</div>';
        }else{

            echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
            echo '<table class="table" style="width: 100%; max-width: 100%;">';
            echo '<thead>';
            echo '<th style="width: 80%;">Nombre</th>';
            echo '<th style="width: 20%;">Agregar</th>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($this->useractividades as $usActividades){
                foreach ($this->datos as $datos){
                    if($usActividades["id_usuario"]==$datos["id_usuario"]){
                        echo '<tr>';
                            echo '<td>';
                                echo $datos["primer_nombre"].' '.$datos["segundo_nombre"].' '.$datos["primer_apellido"].' '.$datos["segundo_apellido"];
                            echo '</td>';
                            echo '<td style="text-align:center;">';
                            ?>
                                <a class="btn" href="<?php echo $this->basePath() ?>/application/paresevaluadores/add/<?php echo $datos["id_usuario"];?>/<?php echo $id;?>">Agregar</a>
                            <?php
                            echo '</td>';
                        echo '</tr>';
                    }
                }
            }
            echo '</tbody>';
            echo '</table>';
            echo '</div>';
        }
        
    }
}






?>

</div></div></div>