<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>Eliminar el registro?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/cronogramaap/eliminar/<?php echo $this->datos;?>/<?php echo $this->id2;?>/<?php echo $this->id3;?>">Eliminar Actividad</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


