<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }
</style>
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
    <div id="container_1">
        <div class="row2">
            <div class="nine3 columns">
                <div id="centersectiontitle">
                    <div class="twelve columns">
                        <div class="sidebartitle"><h3>
                        <?php
                            echo $this->titulo;
                        ?>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="twelve columns">
                <?php 
                    if($id3=="1"){ ?>
                        <a href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id ?>">
                        <i class="icon-arrow-left"></i> Regresar        
                <?php
                    }else{ ?>
                        <a href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $this->id ?>">
                        <i class="icon-arrow-left"></i> Regresar     
                <?php
                    }  ?>
                
                </a>
                <br><br>
                <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttributes(array(
                        'action' => $this->url . '/application/cronogramaap/index/'.$this->id.'/'.$this->id2.'/'.$this->id3,
                        'method' => 'post'
                    ));
                    echo $this->form()->openTag($form);
                    echo '<p>';
                    if($id3!="1"){
                        echo $this->formlabel($form->get('nombre_actividad'));
                        echo $this->formelement($form->get('nombre_actividad'));
                        echo '<p>';
                        echo $this->formlabel($form->get('descripcion'));
                        echo $this->formelement($form->get('descripcion'));
                        echo '<p>';
                        echo $this->formlabel($form->get('objetivo'));
                        echo $this->formelement($form->get('objetivo'));
                    }else{
                        echo $this->formlabel($form->get('nombre_actividad'));
                        echo $this->formelement($form->get('nombre_actividad'));
                        echo '<p>';
                        echo $this->formlabel($form->get('descripcion'));
                        echo $this->formelement($form->get('descripcion'));
                        echo '<p>';
                        echo $this->formlabel($form->get('id_meta'));
                        echo $this->formelement($form->get('id_meta'));
                        echo " *Este campo corresponde a los objetivos especificos diligenciados previamente en la aplicación a la convocatoria.";
                        echo '<p>';
                        echo $this->formlabel($form->get('id_rolresponsable'));
                        echo $this->formelement($form->get('id_rolresponsable'));
                    }
                    
                    
                    echo '<p>';
                    echo $this->formlabel($form->get('fecha_inicio'));
                    echo $this->formelement($form->get('fecha_inicio'));
                    echo '<p>';
                    echo $this->formlabel($form->get('fecha_cierre'));
                    echo $this->formelement($form->get('fecha_cierre'));
                    echo '<p>';
                    echo $this->formelement($form->get('submit'));                  
                    echo $this->form()->closeTag($form);
                ?>
                <br>
            </div>
        </div>
    </div>
</div>


