<style>
	.filter-gestion {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-gestion-left {float: left;}
    .filter-gestion-right {float:right;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
    <div class="filter-gestion">
    	<div class="filter-gestion-left"><h4><?php echo $this->titulo; ?></h4></div>           
        <div class="filter-gestion-right">
            <a class="btn" href="<?php echo $this->basePath() ?>/application/gestionmodulos/index">Módulos</a>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionsubmodulos/index">Submódulos</a>
			<a class="btn" href="<?php echo $this->basePath() ?>/application/gestionformularios/index">Formularios</a>
        </div>
    </div>    
</div>