<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }

    .alineadoDerecha {
        float: right;
    }
</style>
<script type="text/javascript">
	function showHint(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#id_autor>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editarredinv/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('titulo'));
echo $this->formelement($form->get('titulo'));

echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('tipo_libro'));
echo $this->formelement($form->get('tipo_libro'));

echo '<p>';
echo $this->formlabel($form->get('ano'));
echo $this->formelement($form->get('ano'));

echo '<p>';
echo $this->formlabel($form->get('pais'));
echo $this->formelement($form->get('pais'));

echo '<p>';
echo $this->formlabel($form->get('editorial'));
echo $this->formelement($form->get('editorial'));

echo '<p>';
echo $this->formlabel($form->get('isbn'));
echo $this->formelement($form->get('isbn'));

echo '<p>';
echo $this->formlabel($form->get('filtro_autor'));
echo $this->formelement($form->get('filtro_autor'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('paginas'));
echo $this->formelement($form->get('paginas'));

echo '<p>';
echo $this->formlabel($form->get('mes'));
echo $this->formelement($form->get('mes'));

echo '<p>';
echo $this->formlabel($form->get('ciudad'));
echo $this->formelement($form->get('ciudad'));

echo '<p>';
echo $this->formlabel($form->get('edicion'));
echo $this->formelement($form->get('edicion'));

echo '<p>';
echo $this->formlabel($form->get('serie'));
echo $this->formelement($form->get('serie'));

echo '<p>';
echo $this->formlabel($form->get('medio_divulgacion'));
echo $this->formelement($form->get('medio_divulgacion'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_autor'));
echo $this->formelement($form->get('id_autor'));
echo '<p>';
echo '<div>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '</br>';
echo '</br>';
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));
echo '</div>';



echo $this->form()->closeTag($form);
?>				


</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>