<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
					<a
						href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a><br> <br>
				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/experiencialabhv/index/' . $this->id.'/'.$this->id2,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo "</div>";
    echo '<div class="six columns">';
    echo '<p>';
    echo $this->formlabel($form->get('empresa'));
    echo $this->formelement($form->get('empresa'));
    echo '<p>';
    echo $this->formlabel($form->get('cargo'));
    echo $this->formelement($form->get('cargo'));
    echo '<p>';
    echo $this->formlabel($form->get('fecha_inicio'));
    echo $this->formelement($form->get('fecha_inicio'));
    echo "</div>";
    echo '<div class="six columns">';
    echo '<p>';
    echo $this->formlabel($form->get('tipo_vinculacion'));
    echo $this->formelement($form->get('tipo_vinculacion'));
    echo '<p>';
    echo $this->formlabel($form->get('dedicacion_horaria'));
    echo $this->formelement($form->get('dedicacion_horaria'));
    echo '<p>';
    echo $this->formlabel($form->get('fecha_fin'));
    echo $this->formelement($form->get('fecha_fin'));
    echo "</div>";
    echo '<div class="twelve columns">';
    echo '<p>';
    echo $this->formlabel($form->get('descripcion_actividades'));
    echo $this->formelement($form->get('descripcion_actividades'));
    echo '<p>';
    echo $this->formlabel($form->get('otra_info'));
    echo $this->formelement($form->get('otra_info'));
    
    echo '<p>';
    echo $this->formlabel($form->get('image-file'));
    echo $this->formelement($form->get('image-file'));
    echo '<br>';
    echo "</div>";
    echo '<p>';
    echo '<div class="twelve columns">';
    echo $this->formelement($form->get('submit'));
    echo "</div>";

    echo $this->form()->closeTag($form);
    ?>
				<br>
<br>
<legend>.</legend>
</div>
			</div>
		</div>