<style>
	select{
		width:60%;
		min-width:40%;
	}
	input[type=text]{
		width:60%;
		min-width:40%;
	}
</style>
<script>
$(function () {
    var opts = $('#id_lider option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput').keyup(function () {
        var rxp = new RegExp($('#someinput').val(), 'i');
        var optlist = $('#id_lider').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });

    });

});
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="six columns">
<?php
echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';
?>
<a href="<?php echo $this->basePath() ?>/application/grupoinv/index">
	<i class="icon-arrow-left"></i>
	 Regresar</a>
				<br>
				<br>
				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/creargrupoinvestigacion/index',
										'method'=>'post'));
				echo $this->form()->openTag($form);
				if($this->menu==1){
				echo '<p>';
				echo $this->formlabel($form->get('nombre_grupo'));
				echo $this->formelement($form->get('nombre_grupo'));
				echo '<p>';
				echo $this->formlabel($form->get('cod_grupo'));
				echo $this->formelement($form->get('cod_grupo'));
				echo '<p>';
				echo $this->formlabel($form->get('id_clasificacion'));
				echo $this->formelement($form->get('id_clasificacion'));
				echo '<p>';
				echo $this->formlabel($form->get('id_lider'));
				echo '<input id="someinput" type="text">';
				echo '<p>';
				echo $this->formelement($form->get('id_lider'));
				echo '<p>';
				echo $this->formlabel($form->get('estado'));
				echo $this->formelement($form->get('estado'));
				} else {
				echo '<p>';
				echo $this->formlabel($form->get('url'));
				echo $this->formelement($form->get('url'));
				echo '<p>';
				echo $this->formlabel($form->get('plan_accion'));
				echo $this->formelement($form->get('plan_accion'));
				echo '<p>';
				echo $this->formlabel($form->get('mision'));
				echo $this->formelement($form->get('mision'));
				echo '<p>';
				echo $this->formlabel($form->get('vision'));
				echo $this->formelement($form->get('vision'));
				echo '<br>';
				echo $this->formlabel($form->get('redes_grupo'));
				echo $this->formelement($form->get('redes_grupo'));
				echo '<p>';
				echo $this->formlabel($form->get('asociaciones'));
				echo $this->formelement($form->get('asociaciones'));
				echo '<p>';
				echo $this->formlabel($form->get('email'));
				echo $this->formelement($form->get('email'));
				echo '<p>';
				echo $this->formlabel($form->get('telefono'));
				echo $this->formelement($form->get('telefono'));
				echo '<p>';
				echo $this->formlabel($form->get('dir_postal'));
				echo $this->formelement($form->get('dir_postal'));
				echo '<br>';
				echo $this->formlabel($form->get('plan_estrategico'));
				echo $this->formelement($form->get('plan_estrategico'));
				echo '<p>';
				echo $this->formlabel($form->get('sectores_aplicacion'));
				echo $this->formelement($form->get('sectores_aplicacion'));
				 } 
				?>
				<br>
</div>
<div class="six columns">
<?php
echo '<p>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo $this->formelement($form->get('submit'));
echo '<br>';
echo $this->form()->closeTag($form);





				

?>
</div>


</div></div>