<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>¿Eliminar miembro de la red de investigación?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/integrantesred/eliminar/<?php echo $this->datos;?>/<?php echo $this->id2;?>">Eliminar miembro</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editarredinv/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


