<script type="text/javascript">
	function showHint(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#id_autor>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">

					<a
						href="<?php echo $this->basePath() ?>/application/editarredinv/index/<?php echo $this->red; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>

	<?php
echo '<br>';
echo '<br>';

$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="six columns">';

echo $this->formlabel($form->get('filtro_autor'));
echo $this->formelement($form->get('filtro_autor'));
echo '</br>';
echo $this->formelement($form->get('id_autor'));
echo '<br>';
echo $this->formlabel($form->get('tipo_vinculacion'));
echo $this->formelement($form->get('tipo_vinculacion'));
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));

echo '<p>';
echo '<br>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '<div class="six columns">';
echo '<br>';
echo '<br>';
echo $this->formlabel($form->get('fecha_vinculacion'));
echo $this->formelement($form->get('fecha_vinculacion'));
echo '<br>';
echo '<br>';
echo $this->formlabel($form->get('fin_vinculacion'));
echo $this->formelement($form->get('fin_vinculacion'));
echo '<br>';
echo 'Si se encuentre actualmente vinculado, no elegir fecha fin de vinculación o accionar “X”';
echo '<br>';

echo '</div>';
echo $this->form()->closeTag($form);
echo '<br>';
echo '</div>';
echo '<br>';
echo '<br>';
echo "<label>.</label>";
				?>


</div>

</br>
</br>
</br>
			</div>
		</div>
	</div>
</div>