<style>
    textarea {
        height: 70px;
        width: 100%;
        max-width: 100%;

    }
</style> 

<meta charset="UTF-8">
<script type="text/javascript">
$(function () {
    var opts = $('#id_investigador option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput2').keyup(function () {
        var rxp = new RegExp($('#someinput2').val(), 'i');
        var optlist = $('#id_investigador').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });
    });
});

function tipoInves(){
    var sTipo = document.getElementById("stipo").value;
    if(sTipo == "proyecto"){
        document.getElementsByName("primera_vigencia")[0].disabled = false;
        document.getElementsByName("duracion")[0].disabled = false;
        document.getElementsByName("periodo")[0].disabled = false;
    
    }else{
        document.getElementsByName("primera_vigencia")[0].disabled = true;
        document.getElementsByName("duracion")[0].disabled = true;
        document.getElementsByName("periodo")[0].disabled = true;
    }   
}


function tipoProyecto(){
    var tipo = document.getElementsByName("tipo_proyecto")[0].value;
    document.getElementsByName("convocatoria")[0].value = "";
    if(tipo == "E"){
        document.getElementsByName("convocatoria")[0].disabled = false;
    }else{
        document.getElementsByName("convocatoria")[0].disabled = true;

    }   
}
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">

				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
					<script type="text/javascript">

					function myFunction(id_campo) {
                        var lineaInv = document.getElementById("id_linea_inv");
                        for (i = 0; i < lineaInv.length; i++) {
                            if(lineaInv.options[i].value != ''){
                                var option = lineaInv.options[i]; // item
                                var id = lineaInv.options[i].value.split(/-/); 
                                var idPadreValorFlexible = id[1];
                                if(idPadreValorFlexible == document.getElementById(id_campo).value){
                                    option.style.display = "block";
                                }else{
                                    option.style.display = "none";
                                }
                                if(option.text == "Seleccione"){
                                    option.selected = true;
                                }
                            }
                        }
                        if(document.getElementById(id_campo).value == ''){
                            document.getElementById("id_linea_inv").disabled = true;
                        }else{
                            document.getElementById("id_linea_inv").disabled = false;
                        }
                    }
                    
                    function myFunction2() {
                        var dependenciasAca = document.getElementById("id_dependencia_academica");
                    	for (i = 0; i < dependenciasAca.length; i++) {
                    		if(dependenciasAca.options[i].value != ''){
                    			var option = dependenciasAca.options[i]; // item
                                var id = dependenciasAca.options[i].value.split(/-/); // extrae el id del padre    
                                var idPadreValorFlexible = id[1];
                        
                                //valida que el item de la iteracion es del padre seleccionado
                                if(idPadreValorFlexible == document.getElementById("id_unidad_academica").value.split(/-/)[0]){
                                    option.style.display = "block";
                                }else{
                                	option.style.display = "none";
                                }
                        
                                // Selecciona el placeholder por defecto en linea
                                if(option.text == ""){
                                	option.selected = true;
                                }
                    		}                                	                                   
                        }
                        
                        //Bloquea el campo hijo dependiendo de la selección
                        if(document.getElementById("id_unidad_academica").value == ''){
                        	document.getElementById("id_dependencia_academica").disabled = true;
                        }else{
                        	document.getElementById("id_dependencia_academica").disabled = false;
                        }
                        var id = "<?php echo $this->id; ?>";
                    }
                    
                    function myFunction3(){
                        var programaAca = document.getElementById("id_programa_academico");                               
                        for (i = 0; i < programaAca.length; i++) {
                        	if(programaAca.options[i].value != ''){
                        		var option = programaAca.options[i]; // item
                                var id = programaAca.options[i].value.split(/-/); // extrae el id del padre    
                                var idPadreValorFlexible = id[1];
                        
                                //valida que el item de la iteracion es del padre seleccionado
                                if(idPadreValorFlexible == document.getElementById("id_dependencia_academica").value.split(/-/)[0]){
                                    option.style.display = "block";
                                }else{
                                	option.style.display = "none";
                                }
                        
                                // Selecciona el placeholder por defecto en linea
                                if(option.text == ""){
                                	option.selected = true;
                                }
                            }                                                                       
                        }
                        //Bloquea el campo hijo dependiendo de la selección
                        if(document.getElementById("id_dependencia_academica").value == ''){
                        	document.getElementById("id_programa_academico").disabled = true;
                        }else{
                        	document.getElementById("id_programa_academico").disabled = false;
                        }
                        
                        var id = "<?php echo $this->id; ?>";
                    }
                    
                    </script>

				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/proyectos/index',
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo '<h6>';
    echo $this->flashMessenger()->render();
    echo '</h6>';
    
    echo '<p>';
    echo '<h5>';
    echo 'Este proyecto sera creado por fuera de una convocatoria del sistema.';
    echo '</h5>';
    echo '<p>';
    
    echo $this->formlabel($form->get('nombre_proy'));
    echo $this->formelement($form->get('nombre_proy'));
    echo '<p>';
    if ($this->menu == 1) {
        echo $this->formlabel($form->get('codigo_proy'));
        echo $this->formelement($form->get('codigo_proy'));
        echo '<p>';
    }
    echo $this->formlabel($form->get('id_investigador'));
    echo '<input id="someinput2">';
    echo $this->formelement($form->get('id_investigador'));
    echo '<p>';
    ?>
    <label>Tipo de investigación: </label>
    <select id="stipo" name="stipo" onchange="tipoInves()">
      <option value="proyecto">Proyecto de investigación</option>
      <option value="otro">Otros</option>
    </select>
    <?php
    echo '<p>';
    echo $this->formlabel($form->get('primera_vigencia'));
    echo $this->formelement($form->get('primera_vigencia'));
    echo '<p>';
    echo $this->formlabel($form->get('duracion'));
    echo $this->formelement($form->get('duracion'));
    echo $this->formelement($form->get('periodo'));
    echo '<p>';
    echo $this->formlabel($form->get('fecha_inicio'));
    echo $this->formelement($form->get('fecha_inicio'));
    echo '<p>';
    echo '<div class="six columns" style="padding-left: 0px;">';
    echo $this->formlabel($form->get('fecha_terminacion'));
    echo $this->formelement($form->get('fecha_terminacion'));
    echo '</div>';
    echo '<div class="six columns">';
    echo $this->formlabel($form->get('prorroga'));
    echo $this->formelement($form->get('prorroga'));
    echo '</div>';
    echo '<p>';
    echo $this->formlabel($form->get('tipo_proyecto'));
    echo $this->formelement($form->get('tipo_proyecto'));
    echo '<p>';
    echo $this->formlabel($form->get('convocatoria'));
    echo $this->formelement($form->get('convocatoria'));
    echo '<p>';
    echo $this->formlabel($form->get('id_campo'));
    echo $this->formelement($form->get('id_campo'));
    echo '<p>';
    echo $this->formlabel($form->get('id_linea_inv'));
    echo $this->formelement($form->get('id_linea_inv'));
    echo '<p>';
    echo $this->formlabel($form->get('id_unidad_academica'));
    echo $this->formelement($form->get('id_unidad_academica'));
    echo '<p>';
    echo $this->formlabel($form->get('id_dependencia_academica'));
    echo $this->formelement($form->get('id_dependencia_academica'));
    echo '<p>';
    echo $this->formlabel($form->get('id_programa_academico'));
    echo $this->formelement($form->get('id_programa_academico'));
    echo '<p>';
    echo $this->formlabel($form->get('resumen_ejecutivo'));
    echo $this->formelement($form->get('resumen_ejecutivo'));
    echo '<p>';
    echo $this->formlabel($form->get('objetivo_general'));
    echo $this->formelement($form->get('objetivo_general'));
    echo '<p>';
    echo $this->formlabel($form->get('documento_formalizacion'));
    echo $this->formelement($form->get('documento_formalizacion'));
    echo '<p>';
    echo $this->formlabel($form->get('modificaciones_documento'));
    echo $this->formelement($form->get('modificaciones_documento'));
    
    echo '<p>';
    
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>

				<?php
    
    ?>
</div>
			</div>
		</div>
	</div>
</div>
