<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div><br>
<a href="<?php echo $this->basePath() ?>/application/editarconvocatoriai/index/<?php echo $this->id; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a><br><br>
<div class="twelve columns">

				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/camposadd/index/'.$this->id,
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('titulo'));
				echo $this->formelement($form->get('titulo'));
				echo '<p>';
				echo $this->formlabel($form->get('descripcion'));
				echo $this->formelement($form->get('descripcion'));
				echo '<p>';
				echo $this->formlabel($form->get('objetivo'));
				echo $this->formelement($form->get('objetivo'));
				echo '<p>';
				echo $this->formlabel($form->get('obligatorio'));
				echo $this->formelement($form->get('obligatorio'));
				echo '<p>';

				
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>

				<?php
				

				?>

</div></div></div>

