<div class="rowmenu">
	<div class="twelve columns">
	<?php if($this->menu==1){ ?>
		<ul class="menu">
				<li><a href="<?php echo $this->basePath()?>/application/index/index">Inicio</a></li>
				<li><a href="">Administracion y Procesos de Soporte</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/usuario/index">Gestion Usuarios</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/tipovalores/index">Tipos Valores</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/anexodocumento/index">Anexo Documentos</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/gestionarsolicitudes/index">Gestionar Solicitudes</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/mensajeusuario/index">Mensaje a Usuario</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/roles/index">Gestion de Roles y Permisos</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/auditoria/index">Auditoria</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/reportes/index">Reportes</a></li>
					</ul>
				</li>
				<li><a href="">Herramientas de Socializacion</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/noticias/index">Noticias</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/eventos/index">Eventos</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/foro/index">Foro</a></li>
					</ul>
				</li>
				<li><a href="">Grupos de Investigacion</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/grupoinv/index">Gestion Grupos Investigacion</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/consultagi/index">Consulta Grupos Investigacion</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/consultagp/index">Consulta Grupos Proyectos</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/consultai/index">Consulta Investigadores</a></li>
					</ul>
				</li>
<li><a href="<?php echo $this->basePath()?>/application/login/cerrar"><span class="label">Cerrar Sesion</span></a></li>
		</ul>
		<?php } else{?>
		<ul class="menu">
				<li><a href="<?php echo $this->basePath()?>/application/index/index">Inicio</a></li>
				<li><a href="">Modulo Administracion y Procesos de Soporte</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/mensajeadministrador/index">Mensaje al Administrador</a></li>
						<li><a href="<?php echo $this->basePath()?>/application/cambiarcontrasena/index">Cambiar Clave </a></li>
					</ul>
				</li>
				<li><a href="">Herramientas de Socializacion</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/foro/index">Foro</a></li>
					</ul>
				</li>
				<li><a href="">Grupos de Investigacion</a>
					<ul>
						<li><a href="<?php echo $this->basePath()?>/application/grupoinv/index">Editar Grupo Investigacion</a></li>
					</ul>
				</li>
<li><a href="<?php echo $this->basePath()?>/application/login/cerrar"><span class="label">Cerrar Sesion</span></a></li>
		</ul>
		<?php } ?>
	</div>
</div>
<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="eigth columns">
<?php

?>
<br><br><?php  foreach ($this->datos as $d) {?>
			<div class="circledate">
				<div class="textcircle">
					<?php echo $d["fecha_inicio"]; ?>
				</div>
			</div>
<div class="eigth columns">
			<h4><?php echo $d["titulo"]; ?></span></h4>

				<?php echo $d["fecha_inicio"]; ?> - <?php echo $d["fecha_fin"]; ?> 
			</p>
			<p>
				<?php echo $d["evento"]; ?> 
			</p>
			<p>
			<?php $ur='http://'.$d["url"];  ?>
			<a href="<?php echo $ur ?>">
				<?php echo $d["url"]; ?> 
			</a>
			</p>
			<p>
			
<?php

$pos = strpos( trim($d["archivo"],' '), '.png');
$pos2 = strpos( trim($d["archivo"],' '), '.jpg');

if ($pos!='' || $pos2!=''){
?>
<IMG SRC="/public/images/uploads/<?php echo  trim($d["archivo"],' ');?>" width="550" height="550">
<br>
<a href="<?php echo $this->basePath()?>/application/foro/bajar/<?php echo $d["id_foro"];?>">Bajar archivo : </a><?php echo $d["archivo"]; ?> 
<?php
}else
{
?>
<?php if($d["archivo"]==''){}else{ ?> 
<a href="<?php echo $this->basePath()?>/application/foro/bajar/<?php echo $d["id_foro"];?>">Bajar archivo : </a><?php echo $d["archivo"]; ?> 
<?php }} ?>
</div>
			</p>
			<div class="hr">
			</div>
<?php }?>
</div>