
<style>
    .filter-cons input[type="text"],select{
        width: 100%;
    }
    .filter-cons {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-cons-left {float: left;}
    .filter-cons-right {float:right;}
    .filter-cons .btn {width: 275px;}
    .filter-cons .dropdown {display: inline;}
    .filter-cons .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
    .dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
    <div class="filter-cons">
        <div class="filter-cons-left"><h4><?php echo $this->titulo; ?></h4></div>
        <div class="filter-cons-right">
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/consulproyectos/index"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
            <div class="dropdown">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-menu-inner">
                        <?php                               
                        $form = $this->form;
                        $form->prepare ();
                        echo $this->form ()->openTag ( $form );
                        echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
                        echo $this->formlabel($form->get('id_convocatoria'));
                        echo $this->formelement($form->get('id_convocatoria'));
                        echo $this->formlabel($form->get('id_aplicar'));
                        echo $this->formelement($form->get('id_aplicar'));
                        echo $this->formlabel($form->get('nombre_proy'));
                        echo $this->formelement($form->get('nombre_proy'));
                        echo $this->formelement($form->get('submit'));
                        echo $this->form ()->closeTag ( $form );
                        ?>
                    </div>                      
                </div>
            </div>
        </div>
    </div>
</div>
<?php   
    if ($this->consulta == 1) {
        echo '<div class="col col100 noshadow">';
        echo '<div style="overflow-x:auto; width: 100%;" >';
        echo '<table class="table" style="width:100%; max-width: 100%;">';
        echo '<thead>';
        echo '<th style="width:4%;"># item</th>';
        echo '<th style="width:8%;">ID de la convocatoria</th>';
        echo '<th style="width:8%;">ID de la propuesta</th>';
        echo '<th style="width:30%;">Nombre de la propuesta</th>';
        echo '<th style="width:10%;">Evaluación</th>';
        echo '<th style="width:30%;">Evaluador(es)</th>';
        echo '<th style="width:10%;">Editar propuesta</th>';
        /*
        if ($this->menu == 1) {
            echo '<th style="width:10%;">Asignar evaluador</th>';
        }
        */
        echo '</thead>';
        echo '<tbody>';
        $item=0;
        foreach ($this->datos as $dato) {
           echo '<tr>';
           echo '<td>';
           echo "<center>".++$item."</center>";
           echo '</td>';
           echo '<td>';
           echo "<center>".$dato["id_convocatoria"]."</center>";
           echo '</td>';
           echo '<td>';
           echo "<center>".$dato["id_aplicar"]."</center>";
           echo '</td>';
            echo '<td>';
            echo $dato["nombre_proy"];
            echo '</td>';
            $conteo = 0;
            foreach ($this->evaluados as $e) {
                if ($e["id_aplicar"] == $dato["id_aplicar"]) {
                    if ($e["id_ponderacion2"] != null) {
                        $conteo += $e["id_ponderacion2"];
                    }
                }
            }
            echo '<td>';
            echo "<center>".$conteo. " sobre 100"."</center>";
            echo '</td>';
            echo '<td>';
            foreach ($this->evaluador as $eval) {
                if ($eval["id_aplicar"] == $dato["id_aplicar"]) {
                    foreach ($this->usuario as $usua) {
                        if ($eval["id_usuario"] == $usua["id_usuario"]) {
                            echo $usua["primer_nombre"] . ' ' . $usua["primer_apellido"];
                        }
                    }
                    echo '<br>';
                }
            }
            echo '</td>';
            echo '<td>';
            $tipoconvo="";
            foreach ($this->convo as $conv){
                if($dato["id_convocatoria"]==$conv["id_convocatoria"]){
                    $tipoconvo=$conv["tipo_conv"];
                }
            }
            if(trim($tipoconvo)==="i"){
                ?>
                    <center><a class="btn"
                        href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $dato["id_aplicar"];?>"><i class="fa fa-pencil"></i></a>
                    </center>
                <?php
                
            }else{
                ?>
                    <center><a class="btn"
                        href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $dato["id_aplicar"].'/editar';?>"><i class="fa fa-pencil"></i></a>
                    </center>
                <?php
            }
            echo '</td>';
            /*
            if ($this->menu == 1) {
                echo '<td>';
        ?>
                <a class="btn" href="<?php echo $this->basePath() ?>/application/asignareval/index/<?php echo $dato["id_aplicar"];?>">Asignar evaluador</a>
        <?php
                echo '</td>';
            /*}
            */
            echo '</tr>';
            
           
        }
        echo '</table>';
        echo '</div>';
        echo '</div>';
        if(count($this->datos) == 0){
            if($this->data["id_convocatoria"]){
                echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos propuestas con este ID</h3></div>';
            }else if($this->data["id_aplicar"]){
                echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos propuestas con este ID</h3></div>';
            }else{
                echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos propuestas con este nombre</h3></div>';
            }
        }
    }
?>

