<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>¿Cerrar el Proyecto?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/editarproyecto/cerrar/<?php echo $this->datos;?>">Cerrar Proyecto</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editarproyecto/index/<?php echo $this->datos;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


