<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<br>
<a href="<?php echo $this->basePath() ?>/application/editarconvocatoriai/index/<?php echo $this->id; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>
<br><br>
<div class="twelve columns">

				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/requisitosdoc/index/'.$this->id.'/'.$this->id2."/".$this->id3,
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('id_tipo_doc'));
				echo $this->formelement($form->get('id_tipo_doc'));
				?>
				<a href="<?php echo $this->basePath()?>/application/agregarvalflex/index/28" target="_blank">Insertar nuevo documeno requerido</a>
				<?php
				echo '<p>';
				echo $this->formlabel($form->get('descripcion'));
				echo $this->formelement($form->get('descripcion'));
				echo '<p>';
				echo $this->formlabel($form->get('fecha_limite'));
				echo $this->formelement($form->get('fecha_limite'));
				echo '<p>';
				echo $this->formlabel($form->get('hora_limite'));
				echo $this->formelement($form->get('hora_limite'));
				echo '<p>';
				echo $this->formlabel($form->get('responsable'));
				echo $this->formelement($form->get('responsable'));
				echo '<p>';
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>

				<?php
				

				?>
</div></div></div>