<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="four columns">
<?php
echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';

if($id3==1){ ?>
	<a href="<?php echo $this->basePath() ?>/application/editaraplicari/index/<?php echo $this->id2; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

<?php }else{ ?>
<a href="<?php echo $this->basePath() ?>/application/editaraplicar/index/<?php echo $this->id2; ?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

	<?php
}
echo '<br>';echo '<br>';
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/editartablae/index/'.$this->id.'/'.$this->id2.'/'.$this->id3,
										'method'=>'post'));
				echo $this->form()->openTag($form);

				echo '<p>';
				echo $this->formlabel($form->get('id_rol'));
				echo $this->formelement($form->get('id_rol'));
				echo '<p>';
				echo $this->formlabel($form->get('id_tipo_dedicacion'));
				echo $this->formelement($form->get('id_tipo_dedicacion'));
				echo '<p>';
				echo $this->formlabel($form->get('horas_sol'));
				echo $this->formelement($form->get('horas_sol'));
				echo '<p>';
				echo $this->formelement($form->get('submit'));
?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>
<?php
				echo $this->form()->closeTag($form);
				?>
				<br>

</div></div></div>