<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="four columns">
				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/responderforo/index/'.$this->id,
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';

echo '<p>';

?>
<a href="<?php echo $this->basePath() ?>/application/foro/ver/<?php echo $this->id?>"><i class="icon-arrow-left"></i> Regresar</a><br><br>
<?php


echo '<p>';
				echo $this->formlabel($form->get('mensaje'));
				echo $this->formelement($form->get('mensaje'));
				echo '<br>';
				echo $this->formlabel($form->get('image-file'));
				echo $this->formelement($form->get('image-file'));
				echo '<p>';
				
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


				<?php
				

				?>

</div></div></div>