<style>
	select{
		width:80%;
	}
	input[type=text]{
		width:80%;
	}
	input[type=number]{
		width:80%;
	}
	.alineadoDerecha {
        float: right;
        margin-right: 20%;

    }
</style>
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">

<?php

$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url . '/application/crearusuario/index/' . $this->id,
    'method' => 'post'
));
echo $this->form()->openTag($form);

echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';

?>
<a href="<?php echo $this->basePath() ?>/application/usuario/index"><i class="icon-arrow-left"></i> Regresar</a><br>

<?php
echo '</div>';
echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('primer_nombre'));
echo $this->formelement($form->get('primer_nombre'));
echo '<p>';
echo $this->formlabel($form->get('primer_apellido'));
echo $this->formelement($form->get('primer_apellido'));
echo '<p>';
echo $this->formlabel($form->get('id_tipo_documento'));
echo $this->formelement($form->get('id_tipo_documento'));
echo '<p>';
echo $this->formlabel($form->get('email'));
echo $this->formelement($form->get('email'));
echo '</div>';
echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('segundo_nombre'));
echo $this->formelement($form->get('segundo_nombre'));
echo '<p>';
echo $this->formlabel($form->get('segundo_apellido'));
echo $this->formelement($form->get('segundo_apellido'));
echo '<p>';
echo $this->formlabel($form->get('documento'));
echo $this->formelement($form->get('documento'));
echo '</br>';
echo '</br>';
echo '</br>';
echo '<div class="alineadoDerecha">';
echo '<p>';
echo $this->formelement($form->get('submit')); echo "       ";
?>
<a class="btn"
						href="<?php echo $this->basePath() ?>/application/usuario/index">Cancelar</a>
<?php
echo '<br>';
echo '</div>';
echo '</div>';
echo $this->form()->closeTag($form);
?>

</div>
			</div>
		</div>
	</div>
</div>