<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
				echo $this->titulo;
				?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
								<?php
								
								$form = $this->form;
								$form->prepare ();
								$form->setAttributes ( array (
										'action' => 'index',
										'method' => 'post' 
								) );
								echo $this->form ()->openTag ( $form );
								echo '<h6>';
								echo $this->flashMessenger ()->render ();
								echo '</h6>';
								echo '<br>';
								
								echo '<p>';
								echo $this->formlabel ( $form->get ( 'id_convocatoria' ) );
								echo $this->formelement ( $form->get ( 'id_convocatoria' ) );

								echo '<p>';
								echo $this->formlabel ( $form->get ( 'codigo_proyecto' ) );
								echo $this->formelement ( $form->get ( 'codigo_proyecto' ) );

								echo '<p>';
								echo $this->formlabel ( $form->get ( 'nombre_proyecto' ) );
								echo $this->formelement ( $form->get ( 'nombre_proyecto' ) );
								
								echo '<p>';
								echo $this->formelement ( $form->get ( 'submit' ) );
								
								echo '<br>';
								echo '<br>';
								echo $this->form ()->closeTag ( $form );
								?>
				<?php
				echo '</div>';
				echo '<div class="twelve columns">';
				echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
				echo '<table class="table" style="width: 100%; max-width: 100%;">';
				echo "<thead>";
				echo "<th style='width: 10%;'>#</th>";
				echo "<th style='width: 10%;'>ID convocatoria</th>";
				echo "<th style='width: 10%;'>Código proyecto</th>";
				echo "<th style='width: 10%;'>Nombre del proyecto / Semillero de investigación</th>";
				echo "<th style='width: 10%;'>Investigador principal / Coordinadores</th>";
				echo "<th style='width: 10%;'>Número de plazas disponible</th>";
				echo "<th style='width: 10%;'>Monitor inscrito elegible</th>";
				echo "<th style='width: 10%;'>Ver inscripción</th>";
				echo "<th style='width: 10%;'>Etapa de requisitos de inscripción</th>";
				echo "<th style='width: 5%;'>Entrevista</th>";
				echo "<th style='width: 10%;'>Resultado evaluación</th>";
				echo "<th style='width: 10%;'>Seleccionar monitor</th>";
				echo "<th style='width: 5%;'>Resultado del proceso</th>";
				echo '</thead>';
				echo '<tbody>';
				$cont_number = 1;
				foreach ( $this->datosAplicarm as $dato ) {

					$codProyecto="";
			        $nombProyecto="";
			        $InvesProyecto="";
			        $NumPlazasProyecto="";
			        foreach ($proyinvest as $proInvesti) {
			        	if($dato["id_proyecto"] == $proInvesti["id_proyecto_inv"]){
			        		$codProyecto = strstr($proInvesti ["nombre_proyecto"], '-/-', true);
			        		foreach ($prT as $proyeT){
			        			if($codProyecto == trim($proyeT["codigo_proy"])){
			        				$nombProyecto=$proyeT["nombre_proy"];
							        $InvesProyecto=$proyeT["id_investigador"];
							        $NumPlazasProyecto=$proInvesti["cantidad_plazas"];
			        			}	
			        		}
			        	}
			        }

					if($this->id_user == $dato["id_usuario"] || $this->menu == 1 || $this->id_user == $InvesProyecto){
						/*
						if (strcmp($dato ["estado"],"I") === 0 && $this->menu!=1){
	 					   	continue;
						}
						*/
						//echo "ini ";
						$codProyecto="";
				        $nombProyecto="";
				        $InvesProyecto="";
				        $NumPlazasProyecto="";
				        $idProyecto = "";
				        $NumPlazasDisponible = "";

				        foreach ($proyinvest as $proInvesti) {
				        	if($dato["id_proyecto"] == $proInvesti["id_proyecto_inv"]){
				        		$codProyecto = strstr($proInvesti ["nombre_proyecto"], '-/-', true);
				        		foreach ($prT as $proyeT){
				        			if($codProyecto == trim($proyeT["codigo_proy"])){
				        				$nombProyecto=$proyeT["nombre_proy"];
								        $InvesProyecto=$proyeT["id_investigador"];
								        $NumPlazasProyecto=$proInvesti["cantidad_plazas"];
								        //echo $NumPlazasProyecto."+ ";
								        $idProyecto = $proInvesti["id_proyecto_inv"];
								        $NumPlazasDisponible = $proInvesti["plazas_disponibles"];
								        if($NumPlazasDisponible === NULL){
								        	$NumPlazasDisponible = $NumPlazasProyecto;
								        }
				        			}	
				        		}
				        	}
				        }
				        //echo $NumPlazasProyecto."*";
				        //if ($NumPlazasProyecto == "" || $dato["id_usuario"]==null){
				        if ($NumPlazasProyecto == "" || $dato["id_usuario"]==null){
				        	//print_r("continue 1: ".$NumPlazasProyecto."- / ".$dato["id_usuario"]. " / ".$codProyecto." ");
	 					   	continue;
						}

						if ($this->buscar=="Si"){
							if($this->dataBuscar["id_convocatoria"] != "" && $dato["id_convocatoria"] != $this->dataBuscar["id_convocatoria"]){
								//print_r("continue 2");
								continue;
							}
							if($this->dataBuscar["codigo_proyecto"] != "" && strpos(strtoupper($codProyecto), strtoupper($this->dataBuscar["codigo_proyecto"]))===FALSE){
								//print_r("continue 3");
								continue;
							}
							if($this->dataBuscar["nombre_proyecto"] != "" && strpos(strtoupper($nombProyecto), strtoupper($this->dataBuscar["nombre_proyecto"]))===FALSE){
								//print_r("continue 4");
								continue;
							}
							
						}

						echo '<tr>';
						echo '<td>';
						echo $cont_number;
						$cont_number=$cont_number+1;
						echo '</td>';
						echo '<td>';
						echo $dato["id_convocatoria"];
						echo '</td>';
						echo '<td>';
						echo $codProyecto;
						echo '</td>';
						echo '<td>';
						echo $nombProyecto;
						echo '</td>';
						echo '<td style="text-align:center;">';
						foreach ($this->usu as $usuaT) {
                            if($usuaT["id_usuario"] == $InvesProyecto){
                                echo trim($usuaT["primer_nombre"])." ".trim($usuaT["segundo_nombre"])." ".trim($usuaT["primer_apellido"])." ".trim($usuaT["segundo_apellido"]);
                            }
                        }
						echo '</td>';
						echo '<td style="text-align:center;">';
						echo $NumPlazasDisponible." de ".$NumPlazasProyecto;
						echo '</td>';
						echo '<td>';
						foreach ($this->usu as $usuaT) {
                            if($usuaT["id_usuario"] == $dato["id_usuario"]){
                                echo trim($usuaT["primer_nombre"])." ".trim($usuaT["segundo_nombre"])." ".trim($usuaT["primer_apellido"])." ".trim($usuaT["segundo_apellido"]);
                            }
                        }
                        echo '</td>';
                        echo '<td style="text-align:center;">';
                        	$fcierre = "";
                        	$hcierre = "";
	                        foreach ($this->convo as $convoT) {
	                            if($convoT["id_convocatoria"] == $dato["id_convocatoria"]){
	                               $fcierre = trim($convoT["fecha_cierre"]);
	                               $hcierre = trim($convoT["hora_cierre"]);
	                               
	                            }
	                        }

	                        date_default_timezone_set('America/Bogota');
	                        $fecha_actual = strtotime(date("d-m-Y H:i:00"));
							$fecha_convo = strtotime($fcierre." ".$hcierre);
	
							if($fecha_actual < $fecha_convo){
								if($this->menu == 1 || $this->id_user ==  $dato["id_usuario"]){
									?>
										<a class="btn" href="<?php echo $this->basePath() ?>/application/editaraplicarm/index/<?php echo $dato["id_aplicar"]?>/0/0/1">Ver / Editar</a>
									<?php 
								}else{
									if($this->id_user ==  $InvesProyecto){
										?>
											<a class="btn" href="<?php echo $this->basePath() ?>/application/editaraplicarm/index/<?php echo $dato["id_aplicar"]?>/0/1/1">Ver / Editar</a>
										<?php
									}
								}
							}else{
								if($this->menu == 1){
									?>
										<a class="btn" href="<?php echo $this->basePath() ?>/application/editaraplicarm/index/<?php echo $dato["id_aplicar"]?>/0/0/1">Ver / Editar</a>
									<?php 
								}else{
									?>
										<a class="btn" href="<?php echo $this->basePath() ?>/application/editaraplicarm/index/<?php echo $dato["id_aplicar"]?>/0/1/1">Ver / Editar</a>
									<?php 
								}
							}

                        	
						echo '</td>';
						echo '<td style="text-align:center;">';
						if($dato["estado_aprobacionm"] == ""){
							echo "Pendiente";
						}else{
							if($dato["estado_aprobacionm"] == "Aprobado"){
								echo "Cumple";
							}else{
								echo "No cumple";
							}
						}
						echo '</td>';

						echo '<td style="text-align:center;">';
							if($dato["estado_aprobacionm"] == "Aprobado"){
								if($this->menu == 1 || $this->id_user == $InvesProyecto){
									?>
										<a class="btn" href="<?php echo $this->basePath() ?>/application/entrevistam/index/<?php echo $dato["id_aplicar"]?>">Entrevistar</a>
									<?php 
								}
							}
						echo '</td>';
						echo '<td style="text-align:center;">';
						$suma_pr = 0;
                        $cont_pr = 0;
                        foreach ($this->evalCri as $evaluarCriT) {
                            if($evaluarCriT["id_aplicar"] == $dato["id_aplicar"]){
                                $suma_pr = $suma_pr + floatval($evaluarCriT["evaluacion_cuantitativa"]);
                                $cont_pr = $cont_pr + 1; 
                            }
                        }
                        
                        if($cont_pr == 0){
					        echo "0";
					    }else{
					        echo round($suma_pr/$cont_pr, 2);    
					    }
						
						echo '</td>';

						if($NumPlazasDisponible==0 && $dato["estado_seleccionado"]===NULL){
							$seleccionado=0;
						}else{
							if($dato["estado_seleccionado"]=="No seleccionado"){
								$seleccionado = 0;
							}else{
								$seleccionado = 1;
							}
						}
						echo '<td style="text-align:center;">';
							if($dato["estado_aprobacionm"] == "Aprobado"){
								if($dato["fecha_entrevista"] != null){
									if($this->menu == 1 || $this->id_user == $InvesProyecto){
										if($NumPlazasDisponible > 0){
											?>
												<a class="btn" href="<?php echo $this->basePath() ?>/application/entrevistam/seleccionarm/<?php echo $dato["id_aplicar"]; ?>/<?php echo $NumPlazasDisponible; ?>/<?php echo $idProyecto; ?>/<?php echo $seleccionado; ?>">Seleccionar</a>
											<?php
										}else{
											echo 'El proyecto no cuenta con plazas disponibles.';	
										}
									}
								}
							}
						echo '</td>';
						echo '<td style="text-align:center;">';
							if($NumPlazasDisponible==0 && $dato["estado_seleccionado"]===NULL){
								echo "No seleccionado";
							}else{
								echo $dato["estado_seleccionado"];	
							}
						echo '</td>';
					}
				}
				echo '</tr>';
				echo '</table>';
				echo '</div>';
				echo '</br>';
				echo '<legend></legend>';