<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<center>
					<h6>¿Eliminar el semillero de investigación?</h6>
					<a class="btn"
						href="<?php echo $this->basePath() ?>/application/editarsemilleroinv/eliminar/<?php echo $this->datos;?>">Eliminar semillero</a> <a class="btn"
						href="<?php echo $this->basePath() ?>/application/semillerosinv/index">Cancelar</a>

					<br>
					<br>
			
			</div>
		</div>
	</div>
</div>



