
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="six columns">
<?php


$form = $this->form;
$form->prepare();
echo '<br>';
echo $this->form()->openTag($form);
echo '<p>';

?>
<h6>
Su usuario es el correo institucional, de lo contrario comuniquese al correo primeCIUP@pedagogica.edu.co o contactese con la Subdireccion de Gestion de Proyectos CIUP
</h6>
<div class="alert">
<?php

echo $this->flashMessenger()->render();
?>
</div>
<?php
echo $this->formlabel($form->get('usuario'));
echo $this->formelement($form->get('usuario'));
echo '<p>';
echo $this->formlabel($form->get('documento'));
echo $this->formelement($form->get('documento'));
echo '</p>';
echo '<br>';
echo '<p>';
echo $this->formelement($form->get('submit'));
?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>
<?php
echo '</p>';
echo $this->form()->closeTag($form);
?>
</div>
</div></div>
