<style>
    .titulos{
        color: red;
        font-size: 22px;
    }
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }
    [type|="checkbox"] {
    	vertical-align: baseline;
    }
    label[for=integrantes]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=lineas]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=grupos]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=semilleros]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=redes]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=asociaciones]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=reconocimientos]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=instituciones]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=articulos]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=libros]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=capitulos]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=otras]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=bibliograficos]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=proyectosext]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=proyectosint]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=produccion]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=infogeneral]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=identificadores]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=divulgacion]{
       display: inline-block;
       margin-left: 15px;
    }
    label[for=formacion]{
       display: inline-block;
       margin-left: 15px;
    }
</style> 
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle"><h3>
							<?php
								echo $this->titulo;
							?>
							</h3>
						</div>
					</div>
				</div>
				<div >

					<?php
					
					echo '<fieldset>';
					
					$form = $this->form;
					$form->prepare();

					$form->setAttributes(array('action'=> $this->url.'/application/consultagi/index',
											'method'=>'post'));
					echo $this->form()->openTag($form);
					echo '<p>';
					echo $this->formlabel($form->get('nombre_grupo'));
					echo $this->formelement($form->get('nombre_grupo'));
					echo '<p>';
					
					echo $this->formlabel($form->get('id_unidad_academica'));
					echo $this->formelement($form->get('id_unidad_academica'));
					echo '<p>';
					echo $this->formlabel($form->get('id_dependencia_academica'));
					echo $this->formelement($form->get('id_dependencia_academica'));
					echo '<p>';
					echo $this->formlabel($form->get('id_programa_academico'));
					echo $this->formelement($form->get('id_programa_academico'));
					echo '<p>';
					echo $this->formlabel($form->get('id_lineas'));
					echo $this->formelement($form->get('id_lineas'));
					echo '<p>';
					echo '</fieldset>';
					echo '<br>';
					if($this->menu!='0'){
						echo '<fieldset>';
						echo '<legend>Seleccione la información que desea visualizar</legend>';
						echo '<div class="four columns">';
						echo '<p>';
						echo $this->formelement($form->get('infogeneral'));
						echo $this->formlabel($form->get('infogeneral'));
						echo '<p>';
						echo $this->formelement($form->get('integrantes'));
						echo $this->formlabel($form->get('integrantes'));
						echo '<p>';
						echo $this->formelement($form->get('lineas'));
						echo $this->formlabel($form->get('lineas'));
						echo '<p>';
						echo $this->formelement($form->get('grupos'));
						echo $this->formlabel($form->get('grupos'));
						echo '<p>';
						echo $this->formelement($form->get('redes'));
						echo $this->formlabel($form->get('redes'));
						echo '<p>';
						echo $this->formelement($form->get('asociaciones'));
						echo $this->formlabel($form->get('asociaciones'));
						echo '<p>';
						echo $this->formelement($form->get('reconocimientos'));
						echo $this->formlabel($form->get('reconocimientos'));
						echo '<p>';
						echo $this->formelement($form->get('semilleros'));
						echo $this->formlabel($form->get('semilleros'));
						echo '</div>';
						echo '<div class="four columns">';
						echo '<p>';
						echo $this->formelement($form->get('instituciones'));
						echo $this->formlabel($form->get('instituciones'));
						echo '<p>';
						echo $this->formelement($form->get('articulos'));
						echo $this->formlabel($form->get('articulos'));
						echo '<p>';
						echo $this->formelement($form->get('libros'));
						echo $this->formlabel($form->get('libros'));
						echo '<p>';
						echo $this->formelement($form->get('capitulos'));
						echo $this->formlabel($form->get('capitulos'));
						echo '<p>';
						echo $this->formelement($form->get('otras'));
						echo $this->formlabel($form->get('otras'));
						echo '<p>';
						echo $this->formelement($form->get('bibliograficos'));
						echo $this->formlabel($form->get('bibliograficos'));
						echo '<p>';
						echo $this->formelement($form->get('proyectosext'));
						echo $this->formlabel($form->get('proyectosext'));
						echo '</div>';
						echo '<div class="four columns">';
						echo '<p>';
						echo $this->formelement($form->get('proyectosint'));
						echo $this->formlabel($form->get('proyectosint'));
						echo '<p>';
						echo $this->formelement($form->get('produccion'));
						echo $this->formlabel($form->get('produccion'));	
						echo '<p>';
						echo $this->formelement($form->get('identificadores'));
						echo $this->formlabel($form->get('identificadores'));	
						echo '<p>';
						echo $this->formelement($form->get('divulgacion'));
						echo $this->formlabel($form->get('divulgacion'));	
						echo '<p>';
						echo $this->formelement($form->get('formacion'));
						echo $this->formlabel($form->get('formacion'));	
						echo '<p>';
						echo '<br>';
						echo $this->formelement($form->get('submit'));
						echo '<br>';
						echo '</fieldset>';
					}else{
						echo $this->formelement($form->get('submit'));
						echo '<br>';
					}
					
					echo $this->form()->closeTag($form);
					?>
					<br>

					<div >
						<?php
							if($this->consulta==1){
								if($this->menu!='0'){
									if($this->datos == null && $this->info != null && $this->info["nombre_grupo"] != ""){
										echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos grupos de investigación con este nombre</h3></div>';
									}
									foreach ($this->datos as $dato){
										if($info->infogeneral == 0 && $info->integrantes == 0 && $info->lineas == 0 && $info->grupos == 0 && $info->redes == 0 && $info->asociaciones == 0 && $info->reconocimientos == 0 && $info->semilleros == 0 && $info->instituciones == 0 && $info->articulos == 0 && $info->libros == 0 && $info->capitulos == 0 && $info->otras == 0 && $info->bibliograficos == 0 && $info->proyectosext == 0 && $info->proyectosint == 0 && $info->produccion == 0 && $info->identificadores == 0 && $info->divulgacion == 0 && $info->formacion == 0){

											$info->infogeneral = $info->integrantes = $info->lineas = $info->grupos = $info->redes = $info->asociaciones = $info->reconocimientos = $info->semilleros = $info->instituciones = $info->articulos = $info->libros = $info->capitulos = $info->otras = $info->bibliograficos = $info->proyectosext = $info->proyectosint = $info->produccion = $info->identificadores = $info->divulgacion = $info->formacion = 1;
										}

										echo '<fieldset class="fieldset-blue">';
										echo "<legend><h5 class='titulos'>"."  ".$dato ["nombre_grupo"]."</h5></legend>";
										echo '<font size="3">';
										echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
										echo '<table class="table" style="width: 100%; max-width: 100%;">';
										echo '<thead>';
										echo '<th style="width:20%;">Código</th>';
										echo '<th style="width:10%;">Lider</th>';
										echo '<th style="width:10%;">Fecha creación</th>';
										echo '<th style="width:10%;">Unidad</th>';
										echo '<th style="width:10%;">Dependencia</th>';
										echo '<th style="width:10%;">Programa</th>';
										echo '<th style="width:10%;">URL</th>';
										echo '<th style="width:10%;">Email</th>';
										echo '<th style="width:10%;">Estado</th>';
										echo '</thead>';
										echo '<tbody>';
										echo '<tr>';
										echo '<td>';
										echo $dato["cod_grupo"];
										echo'</td>';
										echo '<td>';
										foreach ( $this->d_user as $vf ) {
											if ($vf ["id_usuario"] == $dato ["id_lider"]) {
												echo $vf ["primer_nombre"] . ' ' . $vf ["primer_apellido"];
											}
										}
										echo'</td>';
										echo '<td>';
										echo $dato["fecha_creacion"];
										echo'</td>';
										echo '<td>';
										foreach($this->valflex as $vflex){
										if($vflex["id_valor_flexible"]==$dato["id_unidad_academica"]){
										echo $vflex["descripcion_valor"];
										}
										}
										echo'</td>';
										echo '<td>';
										foreach($this->valflex as $vflex){
										if($vflex["id_valor_flexible"]==$dato["id_dependencia_academica"]){
										echo $vflex["descripcion_valor"];
										}
										}
										echo'</td>';
										echo '<td>';
										foreach($this->valflex as $vflex){
										if($vflex["id_valor_flexible"]==$dato["id_programa_academico"]){
										echo $vflex["descripcion_valor"];
										}
										}
										echo'</td>';
										echo '<td>';
										echo $dato["url"];
										echo'</td>';
										echo '<td>';
										echo $dato["email"];
										echo'</td>';
										echo '<td>';
										if($dato["estado"]=="A"){
											echo "Activo";
										}else{
											echo "Inactivo";
										}
										echo'</td>';
										echo '</tr>';

										echo '</tbody>';
										echo '</table>';
										echo '</font>';
										echo '</div>';
										echo '</fieldset>';
										if($this->info["infogeneral"] != '0'){
											echo '</br>';
											echo '<label><b>Visión</b></label>';
											echo '<textarea disabled>'.$dato ["vision"].'</textarea>';

											echo '</br>';
											echo '<label><b>Misión</b></label>';
											echo '<textarea disabled>'.$dato ["mision"].'</textarea>';

											echo '</br>';
											echo '<label><b>Retos</b></label>';
											echo '<textarea disabled>'.$dato ["retos"].'</textarea>';

											echo '</br>';
											echo '<label><b>Estado del arte</b></label>';
											echo '<textarea disabled>'.$dato ["estado_arte"].'</textarea>';

											echo '</br>';
											echo '<label><b>Descripción del grupo</b></label>';
											echo '<textarea disabled>'.$dato ["descripcion"].'</textarea>';

											echo '</br>';
											echo '<label><b>Descriptores</b></label>';
											echo '<textarea disabled>'.$dato ["descriptores"].'</textarea>';

											echo '</br>';
											echo '<label><b>Plan estratégico</b></label>';
											echo '<textarea disabled>'.$dato ["plan_estrategico"].'</textarea>';

											echo '</br>';
											echo '<label><b>Plan de acción</b></label>';
											echo '<textarea disabled>'.$dato ["plan_accion"].'</textarea>';

											echo '</br>';
											echo '<label><b>Sectores de aplicación</b></label>';
											echo '<textarea disabled>'.$dato ["sectores_aplicacion"].'</textarea>';
										}
										if($this->info["integrantes"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Integrantes</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo '<th>Nombre del integrate</th>';
											echo '</thead>';
											echo '<tbody>';
										
											foreach ($this->datos5 as $dato5){
												if($dato5["id_grupo_inv"]==$dato["id_grupo_inv"]){
													echo '<tr>';
													foreach ( $this->d_user as $vf ) {
														if ($vf ["id_usuario"] == $dato5 ["id_integrante"]) {
															echo '<td>';
															echo $vf ["primer_nombre"] . ' ' . $vf ["segundo_nombre"] . ' ' .$vf ["primer_apellido"] . ' ' . $vf ["segundo_apellido"];
															echo'</td>';
														}
													}
													echo '</tr>';
												}																				
											}
											echo '</tbody>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}
										if($this->info["lineas"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Líneas de investigación</legend>';
											echo '<font size="3">';					
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
											echo '<th style="width: 20%">Nombre</th>';
											echo '<th style="width: 30%">Objetivo</th>';
											echo '<th style="width: 25%">Efectos</th>';
											echo '<th style="width: 25%">Logros</th>';
											echo '</thead>';
											echo '<tbody>';
											foreach ($this->datos2 as $dato2){
												if($dato2["id_grupo_inv"]==$dato["id_grupo_inv"]){
												echo '<tr>';
												echo '<td>';
												echo $dato2["nombre_linea"];
												echo'</td>';
												echo '<td>';
												echo $dato2["objetivo"];
												echo'</td>';
												echo '<td>';
												echo $dato2["efectos"];
												echo'</td>';
												echo '<td>';
												echo $dato2["logros"];
												echo'</td>';
												echo '</tr>';
												}
											}
											//Lineas hv usuario
					                  foreach($this->dataDocumentos as $documento){
					                        if($documento["tipo_documento"]=="linea"){
					                            foreach ($this->LineasHv as $lineashv) {
					                                if($lineashv["id_linea_inv"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
					                                    echo '<tr>';
					                                    echo '<td>';
					                                    echo $lineashv["nombre_linea"];
					                                    echo '</td>';
					                                    echo '<td>';
					                                    echo $lineashv["objetivo"];
					                                    echo '</td>';
					                                    echo '<td>';
					                                    echo $lineashv["efectos"];
					                                    echo '</td>';
					                                    echo '<td>';
					                                    echo $lineashv["logros"];
					                                    echo '</td>';
					                                    echo '</tr>';
					                                }
					                            }
					                        }
					                  }//Lineas hv usuario
					                  echo '</tbody>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["grupos"] != '0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Grupos relacionados o colaboración entre grupos</legend>';
											echo '<font size="3">';					
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
										    echo '<th style="width: 25%;">Nombre</th>';
										    echo '<th style="width: 25%;">Líder</th>';
										    echo '<th style="width: 25%;">Clasificación</th>';
										    echo '<th style="width: 25%;">Descripción</th>';
										    echo '<tr>';

										    foreach ($this->grupos as $gr) {
										    	if($gr["id_grupo_inv"]==$dato["id_grupo_inv"]){
										    	echo '<tr>';
										        echo '<td>';
										        $clasificacion="";
										        $lider="";
										        $descripcion="";

										        foreach ($this->grupostotal as $dr) {
										            if ($dr["id_grupo_inv"] == $gr["id_grupo"]) {
										                echo $dr["nombre_grupo"];
										                $clasificacion = $dr["id_clasificacion"];
										                $lider = $dr["id_lider"];
										                $descripcion = $dr["descripcion"];
										            }
										         }
											    echo '</td>';
										        echo '<td>';
										        foreach ($this->usuarios as $usuas) {
										            if ($usuas["id_usuario"] == $lider) {
										                echo $usuas["primer_nombre"] . ' ' .$usuas["segundo_nombre"] . ' ' .$usuas["primer_apellido"] . ' ' . $usuas["segundo_apellido"];
										            }
										        }
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vf) {
										            if ($clasificacion == $vf["id_valor_flexible"]) {
										                echo $vf["descripcion_valor"];
										            }
										        }
										        echo '</td>';
										        echo '<td>';
										       	echo $descripcion;
										        echo '</td>';  
										        echo '</tr>';
										    	}
										    }
										    
										    echo '</tr>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["redes"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Redes del grupo</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
										    echo '<th style="width: 20%;">Nombre de la red del grupo</th>';
										    echo '<th style="width: 15%;">Código</th>';
										    echo '<th style="width: 20%;">Coordinador 1</th>';
										    echo '<th style="width: 20%;">Coordinador 2</th>';
										    echo '<th style="width: 20%;">Descripción</th>';
										    echo '</tr>';
										    foreach ($this->redes as $red) {
										    	if($red["id_grupo_inv"]==$dato["id_grupo_inv"]){
											        foreach ($this->redinvestigacion as $redinv) {
											            if($red["id_red"]==$redinv["id"]){
											                echo '<tr>';
											                echo '<td>';
											                echo $redinv["nombre"];
											                echo '</td>';
											                echo '<td>';
											                echo $redinv["codigo"];
											                echo '</td>';
											                echo '<td>';
											                foreach ($this->usuarios as $usuas) {
											                    if ($usuas["id_usuario"] == $redinv["coordinador_uno"]) {
											                        echo $usuas["primer_nombre"] . ' ' .$usuas["segundo_nombre"] . ' ' .$usuas["primer_apellido"] . ' ' . $usuas["segundo_apellido"];
											                    }
											                }
											                echo '</td>';
											                echo '<td>';
											                foreach ($this->usuarios as $usuas) {
											                    if ($usuas["id_usuario"] == $redinv["coordinador_dos"]) {
											                        echo $usuas["primer_nombre"] . ' ' .$usuas["segundo_nombre"] . ' ' .$usuas["primer_apellido"] . ' ' . $usuas["segundo_apellido"];
											                    }
											                }
											                echo '</td>';
											                echo '<td>';
											                echo $redinv["descripcion"];
											                echo '</td>';
											                echo '</tr>';
											            }
											        }
										    	}
										    }
										    echo '</tr>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["asociaciones"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Asociaciones</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
										    echo '<th>Nombre</th>';
										    echo '</tr>';
										    foreach ($this->asociaciones as $as) {
										    	if($as["id_grupo_inv"]==$dato["id_grupo_inv"]){
											        echo '<tr>';
											        echo '<td>';
											        echo $as["nombre_asociacion"];
											        echo '</td>';
											        echo '</tr>';
											      }
										    }
										    
										    echo '</tr>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["reconocimientos"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Reconocimientos</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo '<th style="width: 25%;">Nombre</th>';
											echo '<th style="width: 40%;">Número de acto administrativo</th>';
											echo '<th style="width: 20%;">Fecha</th>';
											echo '<th style="width: 15%;">Valor</th>';
											echo '</thead>';
											echo '<tbody>';
										
											foreach ($this->datos7 as $dato7){
												if($dato7["id_grupo_inv"]==$dato["id_grupo_inv"]){
													echo '<tr>';
													echo '<td>'.$dato7["descripcion"].'</td>';
													echo '<td>'.$dato7["num_acto"].'</td>';
													echo '<td>'.$dato7["semestre"].'</td>';
													echo '<td>'.number_format($dato7["valor"],2).'</td>';
													echo '</tr>';
												}																				
											}
											echo '</tbody>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["semilleros"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Semilleros y colectivos del grupo</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
										    echo '<thead>';
										    echo '<th style="width: 20%;">Nombre del Semillero/Otros procesos de formación</th>';
										    echo '<th style="width: 15%;">Código</th>';
										    echo '<th style="width: 20%;">Coordinador 1</th>';
										    echo '<th style="width: 20%;">Coordinador 2</th>';
										    echo '<th style="width: 20%;">Actividades</th>';
										    echo '</tr>';
										    foreach ($this->semillerost as $sem) {
										    	if($sem["id_grupo_inv"]==$dato["id_grupo_inv"]){
											        foreach ($this->semillerosinvestigacion as $semi) {
											            if($sem["id_semillero"]==$semi["id"]){
											                echo '<tr>';
											                echo '<td>';
											                echo $semi["nombre"];
											                echo '</td>';
											                echo '<td>';
											                echo $semi["codigo"];
											                echo '</td>';
											                echo '<td>';
											                foreach ($this->usuarios as $usuas) {
											                    if ($usuas["id_usuario"] == $semi["coordinador_uno"]) {
											                        echo $usuas["primer_nombre"] . ' ' .$usuas["segundo_nombre"] . ' ' .$usuas["primer_apellido"] . ' ' . $usuas["segundo_apellido"];
											                    }
											                }
											                echo '</td>';
											                echo '<td>';
											                foreach ($this->usuarios as $usuas) {
											                    if ($usuas["id_usuario"] == $semi["coordinador_dos"]) {
											                        echo $usuas["primer_nombre"] . ' ' .$usuas["segundo_nombre"] . ' ' .$usuas["primer_apellido"] . ' ' . $usuas["segundo_apellido"];
											                    }
											                }
											                echo '</td>';
											                echo '<td>';
											                echo $semi["actividades"];
											                echo '</td>';
											                echo '</tr>';
											            }
											        }
											        
										    	}
										    }
										    
										    echo '</tr>';
										    echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["instituciones"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Instituciones que tienen integrantes en el grupo</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo '<th>Descripción</th>';
											echo '</thead>';
											echo '<tbody>';
										
											foreach ($this->instituciones as $dato6){
												if($dato6["id_grupo_inv"]==$dato["id_grupo_inv"]){
													foreach ($this->valflex as $vf) {
											            if ($dato6["descripcion"] == $vf["id_valor_flexible"]) {
											            	echo '<tr>';
															echo '<td>';
															echo $vf["descripcion_valor"];
															echo'</td>';
															echo '</tr>';
											                ;
											            }
											        }
												}																				
											}
											echo '</tbody>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["articulos"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Artículos de investigación</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
										    echo "<th style='width: 7%;'>Nombre revista</th>";
										    echo "<th style='width: 7%;'>Nombre articulo</th>";
										    echo "<th style='width: 6%;'>Categorización</th>";
										    echo "<th style='width: 4%;'>Año</th>";
										    echo "<th style='width: 4%;'>Mes</th>";
										    echo "<th style='width: 5%;'>País</th>";
										    echo "<th style='width: 5%;'>Ciudad</th>";
										    echo "<th style='width: 5%;'>ISSN/e-ISSN</th>";
										    echo "<th style='width: 8%;'>No. de páginas</th>";
										    echo "<th style='width: 5%;'>Página inicio</th>";
										    echo "<th style='width: 5%;'>Página fin</th>";
										    echo "<th style='width: 5%;'>Fascículo</th>";
										    echo "<th style='width: 5%;'>Volumen</th>";
										    echo "<th style='width: 5%;'>No. serie</th>";
										    echo "<th style='width: 14%;'>Autor(es)</th>";
										    echo '</tr>';
										    foreach ($this->datos8 as $art) {
										    	if($art["id_grupo_inv"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										        echo '<td>';
										        echo $art["nombre_revista"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["nombre_articulo"];
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vf) {
										            if ($art["categoria"] == $vf["id_valor_flexible"]) {
										                echo $vf["descripcion_valor"];
										            }
										        }
										        echo '</td>';
										        echo '<td>';
										        echo $art["ano"];
										        echo '</td>';
										        echo '<td>';
										        switch ($art["mes"]) {
										                case 1:
										                    echo "Enero";
										                    break;
										                case 2:
										                    echo "Febrero";
										                    break;
										                case 3:
										                    echo "Marzo";
										                    break;
										                case 4:
										                    echo "Abril";
										                    break;
										                case 5:
										                    echo "Mayo";
										                    break;
										                case 6:
										                    echo "Junio";
										                    break;
										                case 7:
										                    echo "Julio";
										                    break;
										                case 8:
										                    echo "Agosto";
										                    break;
										                case 9:
										                    echo "Septiembre";
										                    break;
										                case 10:
										                    echo "Octubre";
										                    break;
										                case 11:
										                    echo "Noviembre";
										                    break;
										                case 12:
										                    echo "Diciembre";
										                    break;
										            }
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vl) {
										            if ($vl["id_valor_flexible"] == $art["id_pais"]) {
										                $art["id_pais"] = $vl["descripcion_valor"];
										            }
										        }
										        echo $art["id_pais"];
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vl) {
										            if ($vl["id_valor_flexible"] == $art["id_ciudad"]) {
										                $art["id_pais"] = $vl["descripcion_valor"];
										            }
										        }
										        echo $art["id_ciudad"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["issn"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["num_paginas"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["pagina_inicio"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["pagina_fin"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["fasciculo"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["volumen"];
										        echo '</td>';
										        echo '<td>';
										        echo $art["serie"];
										        echo '</td>';
										        $autorAux="";
										        foreach ($this->usuarios as $usa) {
										            if ($usa["id_usuario"] == $art["id_autor"]) {
										                
										                $autorAux .= trim($usa["primer_nombre"]) . ' ' . trim($usa["primer_apellido"]). " - ";
										            }
										        }
										        foreach ($this->auto as $aut) {
										            if ($art["id_gi_articulo"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Articulos') {
										                foreach ($this->usuarios as $ua) {
										                    if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                        $autorAux .= trim($ua["primer_nombre"]) . ' ' . trim($ua["primer_apellido"]). " - ";
										                    }
										                }
										            }
										        }
										        echo '<td>';
										        echo $autorAux;
										        echo '</td>';
										        echo '</tr>';
										    	}
										    }
										    //Articulos usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="articulo"){
										            foreach ($this->Articuloshv as $art) {
										                if($art["id_gi_articulo"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                    echo '<td>';
										                    echo $art["nombre_revista"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["nombre_articulo"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $art["categoria"]) {
										                            echo $vl["descripcion_valor"];
										                        }
										                    }
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["ano"];
										                    echo '</td>';
										                    echo '<td>';
										                    switch ($art["mes"]) {
										                            case 1:
										                                echo "Enero";
										                                break;
										                            case 2:
										                                echo "Febrero";
										                                break;
										                            case 3:
										                                echo "Marzo";
										                                break;
										                            case 4:
										                                echo "Abril";
										                                break;
										                            case 5:
										                                echo "Mayo";
										                                break;
										                            case 6:
										                                echo "Junio";
										                                break;
										                            case 7:
										                                echo "Julio";
										                                break;
										                            case 8:
										                                echo "Agosto";
										                                break;
										                            case 9:
										                                echo "Septiembre";
										                                break;
										                            case 10:
										                                echo "Octubre";
										                                break;
										                            case 11:
										                                echo "Noviembre";
										                                break;
										                            case 12:
										                                echo "Diciembre";
										                                break;
										                        }
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $art["id_pais"]) {
										                            $art["id_pais"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $art["id_pais"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $art["id_ciudad"]) {
										                            $art["id_pais"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $art["id_ciudad"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["issn"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["num_paginas"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["pagina_inicio"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["pagina_fin"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["fasciculo"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["volumen"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $art["serie"];
										                    echo '</td>';
										                    $autorAux="";
										                    foreach ($this->usuarios as $usa) {
										                        if ($usa["id_usuario"] == $art["id_autor"]) {
										                            
										                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
										                        }
										                    }
										                    foreach ($this->auto as $aut) {
										                        if ($art["id_gi_articulo"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Articuloshv') {
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
										                                }
										                            }
										                        }
										                    }
										                    echo '<td>';
										                    echo $autorAux;
										                    echo '</td>';
										                    /*
										                    echo '<td>';
										                        if($art["archivo"]!=""){
										                            ?>    
										                                <a href="<?php echo $this->basePath()?>/application/articuloshv/bajar/<?php echo $art["id_gi_articulo"];?>/<?php echo $art["id_usuario"];?>">Descargar archivo</a>
										                            <?php echo " - " . $art["archivo"];
										                        }
										                    echo '</td>';
										                    */
										                }
										            }
										        }
										    }//Articulos usuario  
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["libros"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Libros</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo "<th style='width: 8%;'>Título del libro</th>";
                    echo "<th style='width: 7%;'>Tipo de libro</th>";
										    echo "<th style='width: 4%;'>No. de Páginas</th>";
										    echo "<th style='width: 4%;'>Año</th>";
										    echo "<th style='width: 4%;'>Mes</th>";
										    echo "<th style='width: 5%;'>País de publicación</th>";
										    echo "<th style='width: 5%;'>Ciudad de publicación</th>";
										    echo "<th style='width: 5%;'>Serie</th>";
										    echo "<th style='width: 8%;'>Editorial</th>";
										    echo "<th style='width: 8%;'>No. de Edición</th>";
										    echo "<th style='width: 8%;'>ISBN ó e-ISBN</th>";
										    echo "<th style='width: 8%;'>Medio de divulgación</th>";
										    echo "<th style='width: 10%;'>Autor(es)</th>";
										    echo '</tr>';
										    foreach ($this->datos3 as $lib) {
										    	if($lib["id_grupo_inv"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										        echo '<td>';
										        echo $lib["titulo_libro"];
										        echo '</td>';
										        echo '<td>';
					                            foreach ($this->valflex as $vl) {
					                                if ($vl["id_valor_flexible"] == $lib["tipo_libro"]) {
					                                    echo $vl["descripcion_valor"];
					                                }
					                            }
					                        echo '</td>';
										        echo '<td>';
										        echo $lib["num_paginas"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["ano"];
										        echo '</td>';
										        echo '<td>';
										        switch ($lib["mes"]) {
										                case 1:
										                    echo "Enero";
										                    break;
										                case 2:
										                    echo "Febrero";
										                    break;
										                case 3:
										                    echo "Marzo";
										                    break;
										                case 4:
										                    echo "Abril";
										                    break;
										                case 5:
										                    echo "Mayo";
										                    break;
										                case 6:
										                    echo "Junio";
										                    break;
										                case 7:
										                    echo "Julio";
										                    break;
										                case 8:
										                    echo "Agosto";
										                    break;
										                case 9:
										                    echo "Septiembre";
										                    break;
										                case 10:
										                    echo "Octubre";
										                    break;
										                case 11:
										                    echo "Noviembre";
										                    break;
										                case 12:
										                    echo "Diciembre";
										                    break;
										            }
										        echo '</td>';
										        echo '<td>';
										        echo $lib["pais"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["ciudad"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["serie"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["editorial"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["edicion"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["isbn"];
										        echo '</td>';
										        echo '<td>';
										        echo $lib["medio_divulgacion"];
										        echo '</td>';
										        $autorAux="";
										        foreach ($this->usuarios as $usa) {
										            if ($usa["id_usuario"] == $lib["id_autor"]) {    
										                $autorAux .= trim($usa["primer_nombre"]) . ' ' . trim($usa["primer_apellido"]). " - ";
										            }
										        }
										        foreach ($this->auto as $aut) {
										            if ($lib["id_gi_libro"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Libros') {
										                foreach ($this->usuarios as $ua) {
										                    if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                        $autorAux .= trim($ua["primer_nombre"]) . ' ' . trim($ua["primer_apellido"]). " - ";
										                    }
										                }
										            }
										        }
										        echo '<td>';
										        echo $autorAux;
										        echo '</td>'; 
										        echo '</tr>';
										    	}
										    }
										    //Libros usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="libro"){
										            foreach ($this->libroshv as $lib) {
										                if($lib["id_gi_libro"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                    echo '<td>';
										                    echo $lib["titulo_libro"];
										                    echo '</td>';
										                    echo '<td>';
								                            foreach ($this->valflex as $vl) {
								                                if ($vl["id_valor_flexible"] == $lib["tipo_libro"]) {
								                                    echo $vl["descripcion_valor"];
								                                }
								                            }
								                        echo '</td>';
										                    echo '<td>';
										                    echo $lib["num_paginas"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["ano"];
										                    echo '</td>';
										                    echo '<td>';
										                    switch ($lib["mes"]) {
										                            case 1:
										                                echo "Enero";
										                                break;
										                            case 2:
										                                echo "Febrero";
										                                break;
										                            case 3:
										                                echo "Marzo";
										                                break;
										                            case 4:
										                                echo "Abril";
										                                break;
										                            case 5:
										                                echo "Mayo";
										                                break;
										                            case 6:
										                                echo "Junio";
										                                break;
										                            case 7:
										                                echo "Julio";
										                                break;
										                            case 8:
										                                echo "Agosto";
										                                break;
										                            case 9:
										                                echo "Septiembre";
										                                break;
										                            case 10:
										                                echo "Octubre";
										                                break;
										                            case 11:
										                                echo "Noviembre";
										                                break;
										                            case 12:
										                                echo "Diciembre";
										                                break;
										                        }
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["pais"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["ciudad"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["serie"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["editorial"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["edicion"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["isbn"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $lib["medio_divulgacion"];
										                    echo '</td>';
										                    $autorAux="";
										                    foreach ($this->usuarios as $usa) {
										                        if ($usa["id_usuario"] == $lib["id_autor"]) {    
										                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
										                        }
										                    }
										                    foreach ($this->auto as $aut) {
										                        if ($lib["id_gi_libro"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Libroshv') {
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
										                                }
										                            }
										                        }
										                    }
										                    echo '<td>';
										                    echo $autorAux;
										                    echo '</td>';   
										                    /* 
										                    echo '<td>';
										                        if($lib["archivo"]!=""){
										                            ?>    
										                                <a href="<?php echo $this->basePath()?>/application/libroshv/bajar/<?php echo $lib["id_gi_libro"];?>/<?php echo $lib["id_usuario"];?>">Descargar archivo</a>
										                            <?php echo " - " . $lib["archivo"];
										                        }
										                    echo '</td>';
										                    */
										                }
										            }
										        }
										    }//Libros usuario  
										    
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}	

										if($this->info["capitulos"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Capítulos de libros</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo "<th style='width: 6%;'>Título del libro</th>";
										    echo "<th style='width: 4%;'>Año</th>";
										    echo "<th style='width: 3%;'>Mes</th>";
										    echo "<th style='width: 5%;'>País de publicación</th>";
										    echo "<th style='width: 5%;'>Ciudad de publicación</th>";
										    echo "<th style='width: 4%;'>Serie</th>";
										    echo "<th style='width: 7%;'>Editorial</th>";
										    echo "<th style='width: 5%;'>No. de Edición</th>";
										    echo "<th style='width: 7%;'>ISBN ó e-ISBN</th>";
										    echo "<th style='width: 7%;'>Medio de divulgación</th>";
										    echo "<th style='width: 6%;'>Título del capítulo</th>";
										    echo "<th style='width: 3%;'>No. de capítulo</th>";
										    echo "<th style='width: 4%;'>Páginas del capítulo</th>";
										    echo "<th style='width: 3%;'>Página inicio</th>";
										    echo "<th style='width: 3%;'>Página fin</th>";
										    echo "<th style='width: 7%;'>Autor</th>";
										    echo '<tr>';

										    foreach ($this->capitulos as $int) {
										    	if($int["id_grupo"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										            echo '<td>';
										            echo $int["titulo"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["ano"];
										            echo '</td>';
										        
										            echo '<td>';
										            switch ($int["mes"]) {
										                case 1:
										                    echo "Enero";
										                    break;
										                case 2:
										                    echo "Febrero";
										                    break;
										                case 3:
										                    echo "Marzo";
										                    break;
										                case 4:
										                    echo "Abril";
										                    break;
										                case 5:
										                    echo "Mayo";
										                    break;
										                case 6:
										                    echo "Junio";
										                    break;
										                case 7:
										                    echo "Julio";
										                    break;
										                case 8:
										                    echo "Agosto";
										                    break;
										                case 9:
										                    echo "Septiembre";
										                    break;
										                case 10:
										                    echo "Octubre";
										                    break;
										                case 11:
										                    echo "Noviembre";
										                    break;
										                case 12:
										                    echo "Diciembre";
										                    break;
										            }
										            echo '</td>';
										        
										            echo '<td>';
										            echo $int["pais"];
										            echo '</td>';
										        
										            echo '<td>';
										            echo $int["ciudad"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["serie"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["editorial"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["edicion"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["isbn"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["medio_divulgacion"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["titulo_capitulo"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["numero_capitulo"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["paginas_capitulo"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["pagina_inicio"];
										            echo '</td>';

										            echo '<td>';
										            echo $int["pagina_fin"];
										            echo '</td>';

										            echo '<td>';
										            $autores="";
										            foreach ($this->autoresgrupo as $autor) {
										                if($autor["seccion"]=="3" && $autor["id_objeto"]==$int["id"]){
										                    foreach ($this->usuarios as $usuario) {
										                        if($usuario["id_usuario"]==$autor["id_usuario"]){
										                            $autores .= $usuario["primer_nombre"] . $usuario["primer_apellido"] . $usuario["segundo_apellido"] . " - ";    
										                        }    
										                    }
										                }
										            }
										            echo $autores;
										            echo '</td>';
										        echo '</tr>';
										    	}
										    }
										    //Capitulo de libros usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="capitulo"){
										            foreach ($this->capituloshv as $int) {
										                if($int["id"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                        echo '<td>';
										                        echo $int["titulo"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["ano"];
										                        echo '</td>';
										                    
										                        echo '<td>';
										                        switch ($int["mes"]) {
										                            case 1:
										                                echo "Enero";
										                                break;
										                            case 2:
										                                echo "Febrero";
										                                break;
										                            case 3:
										                                echo "Marzo";
										                                break;
										                            case 4:
										                                echo "Abril";
										                                break;
										                            case 5:
										                                echo "Mayo";
										                                break;
										                            case 6:
										                                echo "Junio";
										                                break;
										                            case 7:
										                                echo "Julio";
										                                break;
										                            case 8:
										                                echo "Agosto";
										                                break;
										                            case 9:
										                                echo "Septiembre";
										                                break;
										                            case 10:
										                                echo "Octubre";
										                                break;
										                            case 11:
										                                echo "Noviembre";
										                                break;
										                            case 12:
										                                echo "Diciembre";
										                                break;
										                        }
										                        echo '</td>';
										                    
										                        echo '<td>';
										                        echo $int["pais"];
										                        echo '</td>';
										                    
										                        echo '<td>';
										                        echo $int["ciudad"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["serie"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["editorial"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["edicion"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["isbn"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["medio_divulgacion"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["titulo_capitulo"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["numero_capitulo"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["paginas_capitulo"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["pagina_inicio"];
										                        echo '</td>';

										                        echo '<td>';
										                        echo $int["pagina_fin"];
										                        echo '</td>';

										                        echo '<td>';
										                        $autores="";
										                        foreach ($this->usuarios as $usa) {
										                            if ($usa["id_usuario"] == $int["id_autor"]) {
										                                $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
										                            }
										                        }
										                        foreach ($this->autoresusuario as $autor) {
										                            if($autor["seccion"]=="3" && $autor["id_objeto"]==$int["id"]){
										                                foreach ($this->usuarios as $usuario) {
										                                    if($usuario["id_usuario"]==$autor["id_usuario"]){
										                                        $autores .= $usuario["primer_nombre"]." ".$usuario["segundo_nombre"]." ".$usuario["primer_apellido"]." ".$usuario["segundo_apellido"]." - ";    
										                                    }    
										                                }
										                            }
										                        }
										                        echo $autores;
										                        echo '</td>';
										                        /*
										                        echo '<td>';
										                            if($int["archivo"]!=""){
										                                ?>    
										                                    <a href="<?php echo $this->basePath()?>/application/capitulosusuario/bajar/<?php echo $int["id"];?>/<?php echo $int["id_usuario"];?>">Descargar archivo</a>
										                                <?php echo " - " . $int["archivo"];
										                            }
										                        echo '</td>'; 
										                        */
										                    echo '</tr>';
										                }
										            }
										        }
										    }//Capitulo de libros usuario
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}	

										if($this->info["otras"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Otras producciones de investigaci&#243;n</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo "<th style='width: 10%;'>Nombre producto</th>";
										    echo "<th style='width: 10%;'>Descripción producto</th>";
										    echo "<th style='width: 10%;'>Tipo producto</th>";
										    echo "<th style='width: 3%;'>Año</th>";
										    echo "<th style='width: 3%;'>Mes</th>";
										    echo "<th style='width: 4%;'>Pais</th>";
										    echo "<th style='width: 5%;'>Ciudad</th>";
										    echo "<th style='width: 10%;'>Instituciones participantes</th>";
										    echo "<th style='width: 15%;'>Registro</th>";
										    echo "<th style='width: 10%;'>Otra información</th>";
										    echo "<th style='width: 10%;'>Autor(es)</th>";
										    echo '</tr>';
										    foreach ($this->otras as $ot) {
										    	if($ot["id_grupo_inv"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										        echo '<td>';
										        echo $ot["nombre_producto"];
										        echo '</td>';
										        echo '<td>';
										        echo $ot["descripcion_producto"];
										        echo '</td>';
										        echo '<td>';
										        echo $ot["tipo_producto"];
										        echo '</td>';
										        echo '<td>';
										        echo $ot["ano"];
										        echo '</td>';
										        echo '<td>';
										        switch ($ot["mes"]) {
										            case 1:
										                echo "Enero";
										                break;
										            case 2:
										                echo "Febrero";
										                break;
										            case 3:
										                echo "Marzo";
										                break;
										            case 4:
										                echo "Abril";
										                break;
										            case 5:
										                echo "Mayo";
										                break;
										            case 6:
										                echo "Junio";
										                break;
										            case 7:
										                echo "Julio";
										                break;
										            case 8:
										                echo "Agosto";
										                break;
										            case 9:
										                echo "Septiembre";
										                break;
										            case 10:
										                echo "Octubre";
										                break;
										            case 11:
										                echo "Noviembre";
										                break;
										            case 12:
										                echo "Diciembre";
										                break;
										        }
										        echo '</td>';
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vl) {
										            if ($vl["id_valor_flexible"] == $ot["id_pais"]) {
										                $ot["id_pais"] = $vl["descripcion_valor"];
										            }
										        }
										        echo $ot["id_pais"];
										        echo '</td>';
										        echo '<td>';
										        foreach ($this->valflex as $vl) {
										            if ($vl["id_valor_flexible"] == $ot["id_ciudad"]) {
										                $ot["id_pais"] = $vl["descripcion_valor"];
										            }
										        }
										        echo $ot["id_ciudad"];
										        echo '</td>';
										        echo '</td>';
										        echo '<td>';
										        echo $ot["instituciones"];
										        echo '</td>';
										        echo '<td>';
										        echo $ot["registro"];
										        echo '</td>';
										        echo '<td>';
										        echo $ot["otra_info"];
										        echo '</td>';
										        $autorAux="";
										        foreach ($this->usuarios as $usa) {
										            if ($usa["id_usuario"] == $ot["id_autor"]) {    
										                $autorAux .= trim($usa["primer_nombre"]) . ' ' . trim($usa["primer_apellido"]). " - ";
										            }
										        }
										        foreach ($this->auto as $aut) {
										            if ($ot["id_otra_prod"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'otra_prod') {
										                foreach ($this->usuarios as $ua) {
										                    if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                        $autorAux .= trim($ua["primer_nombre"]) . ' ' . trim($ua["primer_apellido"]). " - ";
										                    }
										                }
										            }
										        }
										        echo '<td>';
										        echo $autorAux;
										        echo '</td>';
										        echo '</tr>';
										    	}
										    }
										    //Otras producciones usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="producciones"){
										            foreach ($this->Otrasproduccioneshv as $ot) {
										                if($ot["id_otra_prod"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                    echo '<td>';
										                    echo $ot["nombre_producto"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["descripcion_producto"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["tipo_producto"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["ano"];
										                    echo '</td>';
										                    echo '<td>';
										                    switch ($ot["mes"]) {
										                        case 1:
										                            echo "Enero";
										                            break;
										                        case 2:
										                            echo "Febrero";
										                            break;
										                        case 3:
										                            echo "Marzo";
										                            break;
										                        case 4:
										                            echo "Abril";
										                            break;
										                        case 5:
										                            echo "Mayo";
										                            break;
										                        case 6:
										                            echo "Junio";
										                            break;
										                        case 7:
										                            echo "Julio";
										                            break;
										                        case 8:
										                            echo "Agosto";
										                            break;
										                        case 9:
										                            echo "Septiembre";
										                            break;
										                        case 10:
										                            echo "Octubre";
										                            break;
										                        case 11:
										                            echo "Noviembre";
										                            break;
										                        case 12:
										                            echo "Diciembre";
										                            break;
										                    }
										                    echo '</td>';
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $ot["id_pais"]) {
										                            $ot["id_pais"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $ot["id_pais"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $ot["id_ciudad"]) {
										                            $ot["id_pais"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $ot["id_ciudad"];
										                    echo '</td>';
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["instituciones"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["registro"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $ot["otra_info"];
										                    echo '</td>';
										                    $autorAux="";
										                    foreach ($this->usuarios as $usa) {
										                        if ($usa["id_usuario"] == $ot["id_autor"]) {    
										                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
										                        }
										                    }
										                    foreach ($this->auto as $aut) {
										                        if ($ot["id_otra_prod"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'otra_prodhv') {
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
										                                }
										                            }
										                        }
										                    }
										                    echo '<td>';
										                    echo $autorAux;
										                    echo '</td>';
										                    /*
										                    echo '<td>';
										                        if($ot["archivo"]!=""){
										                            ?>    
										                                <a href="<?php echo $this->basePath()?>/application/otrasproduccioneshv/bajar/<?php echo $ot["id_otra_prod"];?>/<?php echo $ot["id_usuario"];?>">Descargar archivo</a>
										                            <?php echo " - " . $ot["archivo"];
										                        }
										                    echo '</td>';  
										                  	*/
										                    echo '</tr>';
										                }
										            }  
										        }
										    }//Otras producciones usuario
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}	

										if($this->info["bibliograficos"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Otros documentos bibliográficos</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';					
											echo "<th style='width: 6%;'>Nombre</th>";
										    echo "<th style='width: 3%;'>No. Páginas</th>";
										    echo "<th style='width: 3%;'>Año</th>";
										    echo "<th style='width: 3%;'>Mes</th>";
										    echo "<th style='width: 4%;'>Pais</th>";
										    echo "<th style='width: 4%;'>Ciudad</th>";
										    echo "<th style='width: 15%;'>No. De Indexación</th>";
										    echo "<th style='width: 15%;'>Instituciones participantes</th>";
										    echo "<th style='width: 5%;'>URL</th>";
										    echo "<th style='width: 14%;'>Descripción</th>";
										    echo "<th style='width: 12%;'>Medio de divulgación</th>";
										    echo "<th style='width: 6%;'>Autor(es)</th>";
										    echo '</tr>';
										    foreach ($this->datos9 as $bli) {
										    	if($bli["id_grupo_inv"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										        echo '<td>';
										        echo $bli["nombre_documento"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["numero_paginas"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["ano"];
										        echo '</td>';
										        echo '<td>';
										        switch ($bli["mes"]) {
										            case 1:
										                echo "Enero";
										                break;
										            case 2:
										                echo "Febrero";
										                break;
										            case 3:
										                echo "Marzo";
										                break;
										            case 4:
										                echo "Abril";
										                break;
										            case 5:
										                echo "Mayo";
										                break;
										            case 6:
										                echo "Junio";
										                break;
										            case 7:
										                echo "Julio";
										                break;
										            case 8:
										                echo "Agosto";
										                break;
										            case 9:
										                echo "Septiembre";
										                break;
										            case 10:
										                echo "Octubre";
										                break;
										            case 11:
										                echo "Noviembre";
										                break;
										            case 12:
										                echo "Diciembre";
										                break;
										        }
										        echo '</td>';
										        echo '<td>';
										        echo $bli["pais"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["ciudad"];
										        echo '</td>';        
										        echo '<td>';
										        echo $bli["num_indexacion"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["instituciones"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["url"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["descripcion"];
										        echo '</td>';
										        echo '<td>';
										        echo $bli["medio_divulgacion"];
										        echo '</td>';
										        $autorAux="";
										        foreach ($this->usuarios as $usa) {
										            if ($usa["id_usuario"] == $bli["id_autor"]) {    
										                $autorAux .= trim($usa["primer_nombre"]) . ' ' . trim($usa["primer_apellido"]). " - ";
										            }
										        }
										        foreach ($this->auto as $aut) {
										            if ($bli["id_bibliografico"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'bibliografico') {
										                foreach ($this->usuarios as $ua) {
										                    if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                        $autorAux .= trim($ua["primer_nombre"]) . ' ' . trim($ua["primer_apellido"]). " - ";
										                    }
										                }
										            }
										        }
										        echo '<td>';
										        echo $autorAux;
										        echo '</td>';
										        echo '</tr>';
										     }
										    }
										    //Otros documentos usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="documentos"){
										            foreach ($this->Bibliograficoshv as $bli) {
										                if($bli["id_bibliografico"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                    echo '<td>';
										                    echo $bli["nombre_documento"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["numero_paginas"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["ano"];
										                    echo '</td>';
										                    echo '<td>';
										                    switch ($bli["mes"]) {
										                        case 1:
										                            echo "Enero";
										                            break;
										                        case 2:
										                            echo "Febrero";
										                            break;
										                        case 3:
										                            echo "Marzo";
										                            break;
										                        case 4:
										                            echo "Abril";
										                            break;
										                        case 5:
										                            echo "Mayo";
										                            break;
										                        case 6:
										                            echo "Junio";
										                            break;
										                        case 7:
										                            echo "Julio";
										                            break;
										                        case 8:
										                            echo "Agosto";
										                            break;
										                        case 9:
										                            echo "Septiembre";
										                            break;
										                        case 10:
										                            echo "Octubre";
										                            break;
										                        case 11:
										                            echo "Noviembre";
										                            break;
										                        case 12:
										                            echo "Diciembre";
										                            break;
										                    }
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["pais"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["ciudad"];
										                    echo '</td>';        
										                    echo '<td>';
										                    echo $bli["num_indexacion"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["instituciones"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["url"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["descripcion"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $bli["medio_divulgacion"];
										                    echo '</td>';
										                    $autorAux="";
										                    foreach ($this->usuarios as $usa) {
										                        if ($usa["id_usuario"] == $bli["id_autor"]) {    
										                            $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
										                        }
										                    }
										                    foreach ($this->auto as $aut) {
										                        if ($bli["id_bibliografico"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'bibliograficohv') {
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $aut["id_usuario"]) {
										                                    $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
										                                }
										                            }
										                        }
										                    }
										                    echo '<td>';
										                    echo $autorAux;
										                    echo '</td>';
										                    /*
										                    echo '<td>';
										                        if($bli["archivo"]!=""){
										                            ?>    
										                                <a href="<?php echo $this->basePath()?>/application/bibliograficoshv/bajar/<?php echo $bli["id_bibliografico"];?>/<?php echo $bli["id_usuario"];?>">Descargar archivo</a>
										                            <?php echo " - " . $bli["archivo"];
										                        }
										                    echo '</td>';
										                    */
										                    echo '</tr>';
										                }
										            }
										        }
										    }//Otros documentos usuario
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}									

										if($this->info["proyectosext"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Proyectos de investigación externos</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
    										echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
											echo "<th style='width: 5%;'>Código del proyecto</th>";
										    echo "<th style='width: 5%;'>Nombre del proyecto</th>";
										    echo "<th style='width: 5%;'>Fecha inicio</th>";
										    echo "<th style='width: 5%;'>Fecha fin</th>";
										    echo "<th style='width: 20%;'>Resumen ejecutivo</th>";
										    echo "<th style='width: 15%;'>Objetivo general</th>";
										    echo "<th style='width: 20%;'>Equipo de trabajo</th>";
										    echo "<th style='width: 10%;'>Productos derivados</th>";
										    echo '</tr>';
										    foreach ($this->datos4 as $proyext) {
										    	if($proyext["id_grupo_inv"]==$dato["id_grupo_inv"]){
										        echo '<tr>';
										        echo '<td>';
										        echo $proyext["codigo_proyecto"];
										        echo '</td>';
										        echo '<td>';
										        echo $proyext["nombre_proyecto"];
										        echo '</td>';
										        echo '<td>';
										        echo $proyext["fecha_inicio"];
										        echo '</td>';
										        echo '<td>';
										        echo $proyext["fecha_fin"];
										        echo '</td>';
										        echo '<td>';
										        echo $proyext["resumen_ejecutivo"];
										        echo '</td>';
										        echo '<td>';
										        echo $proyext["objetivo_general"];
										        echo '</td>';
										        echo '<td>';
										        echo '<table style="border-style: hidden;">';
										        $rol="";
										        foreach ($this->auto as $auts) {
										            if ($proyext["id_proyecto_ext"] == $auts["id_padre"] && trim($auts["nombre_padre"]) == 'proy_ext') {
										                foreach ($this->valflex as $v) {
										                    if ($v["id_valor_flexible"] == $auts["id_rol"]) {
										                        $rol = $v["descripcion_valor"];
										                    }
										                }
										                foreach ($this->usuarios as $ua) {
										                    if ($ua["id_usuario"] == $auts["id_usuario"]) {
										                        echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["primer_apellido"] . '</td><td>'.$rol.'</td>');
										                        echo '</tr>';
										                    }
										                }
										            }
										        }
										        echo '</table></td>';
										        echo '<td>';
										        echo $proyext["productos_derivados"];
										        echo '</td>';
										       echo '</tr>';
										   		}
										    }
										    //Proyectos externos usuario
										    foreach($this->dataDocumentos as $documento){
										        if($documento["tipo_documento"]=="externos"){
										            foreach ($this->Proyectosexthv as $proyext) {
										                if($proyext["id_proyecto_ext"] == $documento["id_documento"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
										                    echo '<tr>';
										                    echo '<td>';
										                    echo $proyext["codigo_proyecto"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyext["nombre_proyecto"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyext["fecha_inicio"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyext["fecha_fin"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyext["resumen_ejecutivo"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyext["objetivo_general"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo '<table style="border-style: hidden;">';
										                    foreach ($this->auto as $auts) {
										                        if ($proyext["id_proyecto_ext"] == $auts["id_padre"] && trim($auts["nombre_padre"]) == 'proy_exthv') {
										                            foreach ($this->valflex as $v) {
										                                if ($v["id_valor_flexible"] == $auts["id_rol"]) {
										                                    $rol = $v["descripcion_valor"];
										                                }
										                            }
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $auts["id_usuario"]) {
										                                    echo '<tr><td>'.trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"]).'</td><td>'.$rol.'</td>';
										                                    echo '</tr>';
										                                }
										                            }
										                        }
										                    }
										                    echo '</table></td>';
										                    echo '<td>';
										                    echo $proyext["productos_derivados"];
										                    echo '</td>';
										                    /*
										                    echo '<td>';
										                        if($proyext["archivo"]!=""){
										                            ?>    
										                                <a href="<?php echo $this->basePath()?>/application/proyectosexthv/bajar/<?php echo $proyext["id_proyecto_ext"];?>/<?php echo $proyext["id_usuario"];?>">Descargar archivo</a>
										                            <?php echo " - " . $proyext["archivo"];
										                        }
										                    echo '</td>';
										                    */
										                    echo '</tr>';
										                }
										            }
										        }
										    }//Proyectos externos usuario
										    echo '</tr>';
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["proyectosint"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Proyectos de investigación internos</legend>';
											echo '<font size="3">';
											echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
											echo "<th style='width: 5%;'>Código del proyecto</th>";
											echo "<th style='width: 5%;'>Nombre del proyecto</th>";
											echo "<th style='width: 5%;'>Investigador principal</th>";
											echo "<th style='width: 5%;'>Duración</th>";
											echo "<th style='width: 5%;'>Unidad académica</th>";
											echo "<th style='width: 20%;'>Dependencia académica</th>";
											echo "<th style='width: 15%;'>Resumen ejecutivo</th>";
											echo "<th style='width: 20%;'>Objetivo general</th>";
											echo "<th style='width: 10%;'>Equipo de trabajo</th>";
										    echo '</tr>';
										    foreach ($this->proyectosint as $proyint) {
										    	if($proyint["id_grupo_inv"]==$dato["id_grupo_inv"]){
											        foreach ($this->proyectos as $proyectosT) {
											            if($proyint["id_proyecto"]==$proyectosT["id_proyecto"]){
										                   echo '<tr>';
										                    echo '<td>';
										                    echo $proyectosT["codigo_proy"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyectosT["nombre_proy"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->usuarios as $ua) {
										                        if ($ua["id_usuario"] == $proyectosT["id_investigador"]) {
										                            echo trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]);
										                        }
										                    }
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyectosT["duracion"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $proyectosT["id_unidad_academica"]) {
										                            $proyectosT["id_unidad_academica"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $proyectosT["id_unidad_academica"];
										                    echo '</td>';
										                    echo '<td>';
										                    foreach ($this->valflex as $vl) {
										                        if ($vl["id_valor_flexible"] == $proyectosT["id_dependencia_academica"]) {
										                            $proyectosT["id_dependencia_academica"] = $vl["descripcion_valor"];
										                        }
										                    }
										                    echo $proyectosT["id_dependencia_academica"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyectosT["resumen_ejecutivo"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo $proyectosT["objetivo_general"];
										                    echo '</td>';
										                    echo '<td>';
										                    echo '<table style="border-style: hidden;">';
										                    $rol="";
										                    foreach ($this->tablaequipo as $auts) {
										                        if ($proyectosT["id_proyecto"] == $auts["id_proyecto"]) {
										                            foreach ($this->valflex as $v) {
										                                if ($v["id_valor_flexible"] == $auts["id_rol"]) {
										                                    $rol = $v["descripcion_valor"];
										                                }
										                            }
										                            foreach ($this->usuarios as $ua) {
										                                if ($ua["id_usuario"] == $auts["id_integrante"]) {
										                                    echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]). '</td><td>'.$rol.'</td>';
										                                    echo '</tr>';
										                                }
										                            }
										                        }
										                    }
										                    echo '</table></td>';
										                    echo '</td>';
											            }
											        }
											    }
										    }
										    echo '</tr>';
										    //Proyectos internos usuario
										    foreach($this->dataDocumentos as $documento){
						                    if($documento["tipo_documento"]=="internos"){
						                        foreach ($this->Proyectosintusua as $proyint) {
						                            if($proyint["id"] == $documento["id_documento"]){
						                                foreach ($this->proyectos as $proyectosT) {
						                                    if($proyint["id_proyecto"]==$proyectosT["id_proyecto"] && $documento["id_grupoinv"]==$dato["id_grupo_inv"]){
						                                           echo '<tr>';
						                                            echo '<td>';
						                                            echo $proyectosT["codigo_proy"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            echo $proyectosT["nombre_proy"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            foreach ($this->usuarios as $ua) {
						                                                if ($ua["id_usuario"] == $proyectosT["id_investigador"]) {
						                                                    echo trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]);
						                                                }
						                                            }
						                                            echo '</td>';
						                                            echo '<td>';
						                                            echo $proyectosT["duracion"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            foreach ($this->valflex as $vl) {
						                                                if ($vl["id_valor_flexible"] == $proyectosT["id_unidad_academica"]) {
						                                                    $proyectosT["id_unidad_academica"] = $vl["descripcion_valor"];
						                                                }
						                                            }
						                                            echo $proyectosT["id_unidad_academica"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            foreach ($this->valflex as $vl) {
						                                                if ($vl["id_valor_flexible"] == $proyectosT["id_dependencia_academica"]) {
						                                                    $proyectosT["id_dependencia_academica"] = $vl["descripcion_valor"];
						                                                }
						                                            }
						                                            echo $proyectosT["id_dependencia_academica"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            echo $proyectosT["resumen_ejecutivo"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            echo $proyectosT["objetivo_general"];
						                                            echo '</td>';
						                                            echo '<td>';
						                                            echo '<table style="border-style: hidden;">';
						                                            $rol="";
						                                            foreach ($this->tablaequipo as $auts) {
						                                                if ($proyectosT["id_proyecto"] == $auts["id_proyecto"]) {
						                                                    foreach ($this->valflex as $v) {
						                                                        if ($v["id_valor_flexible"] == $auts["id_rol"]) {
						                                                            $rol = $v["descripcion_valor"];
						                                                        }
						                                                    }
						                                                    foreach ($this->usuarios as $ua) {
						                                                        if ($ua["id_usuario"] == $auts["id_integrante"]) {
						                                                            echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]). '</td><td>'.$rol.'</td>';
						                                                            echo '</tr>';
						                                                        }
						                                                    }
						                                                }
						                                            }
						                                            echo '</table></td>';
						                                    }
						                                }
						                            }
						                        }
						                    }
						                }//Proyectos internos usuario
											echo '</table>';
											echo '</div>';
											echo '</font>';
											echo '</fieldset>';
										}

										if($this->info["produccion"]!='0'){
											echo '<br>';
											echo '<fieldset class="fieldset-blue">';
											echo '<legend>Producción académica</legend>';
											echo '<font size="3">';
											echo '<table class="table" style="width: 100%; max-width: 100%;">';
											echo '<thead>';
											echo '<thead>';
										    echo '<th>Tipo archivo</th>';
										    echo '<th>Nombre archivo</th>';
										    echo '</tr>';
										    foreach ($this->arch as $arch) {
										    	if($arch["id_grupo_inv"]==$dato["id_grupo_inv"]){
											        echo '<tr>';
											        echo '<td>';
											        foreach ($this->valflex as $vf) {
											            if ($vf["id_valor_flexible"] == $arch["id_tipo_archivo"]) {
											                echo $vf["descripcion_valor"];
											            }
											        }
											        echo '</td>';
											        echo '<td>';
											        if($this->menu == 1){
											        	?>
															<a href="<?php echo $this->basePath()?>/application/archivos/bajar/<?php echo $arch["id_archivo"];?>">Bajar archivo: </a><?php echo $arch["archivo"]; ?> 
														<?php
											        }else{
											        	echo $arch["archivo"]; 
											        }
											        echo '</td>';
											        echo '</tr>';
										    	}
										    }									    
										    echo '</tr>';
											echo '</table>';
											echo '</font>';
											echo '</fieldset>';
										}
										echo '<br>';
										echo '<br>';

						if($this->info["identificadores"]!='0'){
										?>
						<<fieldset class="fieldset-blue">
						    <a name='Identificadores'></a>
						    <legend>Identificadores de Investigación</legend>
						    <?php
						    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
						    echo '<table class="table" style="width: 100%; max-width: 100%;">';
						    echo '<thead>';
						    echo "<th style='width: 5%;'>ID</th>";
		                echo "<th style='width: 10%;'>Nombre registrado</th>";
		                echo '<th style="width: 5%;">Tipo de identificador</th>';
		                echo "<th style='width: 10%;'>Tipo de categoría</th>";
		                echo "<th style='width: 5%;'>Fecha de registro</th>";
		                echo "<th style='width: 5%;'>Dirección web</th>";
		                echo "<th style='width: 5%;'>Ciudad</th>";
		                echo "<th style='width: 20%;'>Descripción</th>";
		                echo "<th style='width: 20%;'>Otra información relevante</th>";
						    echo '<tr>';

						    foreach ($this->identificadores as $int) {
						    	if($int["id_red"] == $dato["id_grupo_inv"]){
						    		echo '<tr>';
                            echo '<td>';
                                echo $int["id_field"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["nombre"];
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->valflex as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipoidentificador"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                foreach ($this->valflex as $val) {
                                    if($val["id_valor_flexible"]==$int["id_tipocategoria"]){
                                        echo $val["descripcion_valor"];
                                    }
                                }
                            echo '</td>';
                            echo '<td>';
                                echo $int["fecha_registro"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["web"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["ciudad"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["descripcion"];
                            echo '</td>';
                            echo '<td>';
                                echo $int["otra_informacion"];
                            echo '</td>';                        
                        	echo '</tr>';
						    	}
                      }

						    echo '</tr>';
						    echo '</table>';
						    echo '</div>';

						?>
						</fieldset>
						</br>
						</br>
						<?php
							}

							if($this->info["divulgacion"]!='0'){
						?>
						<fieldset class="fieldset-blue">
						    <a name='Divulgacion'></a>
						    <legend>Divulgación</legend>
						    <?php
						    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
						    echo '<table class="table" style="width: 100%; max-width: 100%;">';
						    echo '<thead>';
						    echo "<th style='width: 15%;'>Nombre de trabajo</th>";
                      echo "<th style='width: 15%;'>Tipo de evento</th>";
                      echo '<th style="width: 15%;">Tipo de participación</th>';
                      echo "<th style='width: 15%;'>Nombre de trabajo</th>";
                      echo "<th style='width: 10%;'>Tipo de medio</th>";
                      echo "<th style='width: 15%;'>Medio de divulgación</th>";
						    echo '<tr>';

						    foreach ($this->eventos as $int) {
						    	if($int["id_red"] == $dato["id_grupo_inv"]){
	                        echo '<tr>';
	                            echo '<td>';
	                                echo $int["nombre_trabajo"];
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_tipoevento"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_tipoparticipacion"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                echo $int["nombre_trabajo_medio"];
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_tipomedio"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                echo $int["medio_divulgacion"];
	                            echo '</td>';                   
	                        echo '</tr>';
	                     }
                     }

						    echo '</tr>';
						    echo '</table>';
						    echo '</div>';
						?>
						</fieldset>
						</br>
						</br>
<?php
							}

							if($this->info["formacion"]!='0'){
						?>

						<fieldset class="fieldset-blue">
						    <a name='Formacion'></a>
						    <legend>Formación</legend>
						    <?php
						    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
						    echo '<table class="table" style="width: 100%; max-width: 100%;">';
						    echo '<thead>';
						    echo "<th style='width: 15%;'>Trabajo de grado</th>";
                      echo "<th style='width: 10%;'>Tipo de trabajo</th>";
                      echo '<th style="width: 10%;">Tipo de participación</th>';
                      echo "<th style='width: 10%;'>Estado</th>";
                      echo "<th style='width: 10%;'>Proyecto de Inv.</th>";
                      echo "<th style='width: 10%;'>Tipo de formación</th>";
                      echo "<th style='width: 10%;'>Semillero</th>";
                      echo "<th style='width: 10%;'>Tipo de participación</th>";
						    echo '<tr>';

						    foreach ($this->formacion as $int) {
                 			if($int["id_red"] == $dato["id_grupo_inv"]){
	                        echo '<tr>';
	                            echo '<td>';
	                                echo $int["nombre_trabajo"];
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_tipotrabajo"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_tipoparticipacion"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_estadotipotrabajo"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                echo $int["nombre_proyecto"];
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_formacioninvestigador"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';
	                            echo '<td>';
	                                foreach ($this->semilleros as $val) {
	                                    if($val["id"]==$int["id_semillero"]){
	                                        echo $val["codigo"]."-".$val["nombre"];
	                                    }
	                                }
	                            echo '</td>';
	                             echo '<td>';
	                                foreach ($this->valflex as $val) {
	                                    if($val["id_valor_flexible"]==$int["id_rolparticipacion"]){
	                                        echo $val["descripcion_valor"];
	                                    }
	                                }
	                            echo '</td>';             
	                        echo '</tr>';
	                       }
                      }

						    echo '</tr>';
						    echo '</table>';
						    echo '</div>';
						?>
						</fieldset>
						</br>
						</br>
						<?php
							}
						?>
						
						<?php									
									}//fin foreach ($this->datos as $dato)
								}//fin if menú
								else{
									if($this->datos == null && $this->info != null && $this->info["nombre_grupo"] != ""){
										echo '<div style="text-align: center;display: inline-block; width: 100%;"><h3>No encontramos grupos de investigación con este nombre</h3></div>';
									}else{
										echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
										echo '<table class="table" style="width: 100%; max-width: 100%;">';
										echo '<thead>';
										echo '<th style="width: 80%;">Nombre</th>';
										echo '<th style="width: 20%;">Información del grupo</th>';
										echo '</thead>';
										echo '<tbody>';
										foreach ($this->datos as $dato){
										    echo '<tr>';
										        echo '<td>';
										            echo $dato ["nombre_grupo"];
										        echo '</td>';
										        echo '<td style="text-align:center;">';
										        ?>
										            <a class="btn" href="<?php echo $this->basePath() ?>/application/hgrupoinvestigacion/index/<?php echo $dato["id_grupo_inv"];?>">Ver</a>
										        <?php
										        echo '</td>';
										    echo '</tr>';
										}
										echo '</tbody>';
										echo '</table>';
										echo '</div>';
									}
								}
							}
						?>
					</div>

</div></div></div></div></div>