<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="four columns">
				<?php
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/crearforo/responder',
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('titulo'));
				echo $this->formelement($form->get('titulo'));
				echo '<p>';
				echo $this->formlabel($form->get('mensaje'));
				echo $this->formelement($form->get('mensaje'));
				echo '<br>';
				echo $this->formlabel($form->get('image-file'));
				echo $this->formelement($form->get('image-file'));
				echo '<p>';
				
				echo $this->formelement($form->get('submit2'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


				<?php
				

				?>

</div></div></div>