<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }
    .alineadoDerecha {
        float: right;
    }
</style> 
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
    <div id="container_1">
<div class="row2">
    <div class="nine3 columns">
        <div id="centersectiontitle">
            <div class="twelve columns">
                <div class="sidebartitle"><h3>
                <?php
                    echo $this->titulo;
                ?>
                </h3>
            </div>
        </div>
    </div>
<div class="twelve columns">
<a href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id; ?>">
    <i class="icon-arrow-left"></i>
     Regresar</a>
    <?php
echo '<br>';echo '<br>';
                $form = $this->form;
                $form->prepare();

                $form->setAttributes(array('action'=> $this->url.'/application/proyectosexthv/index/'.$this->id.'/'.$this->id2,
                                        'method'=>'post'));
                echo $this->form()->openTag($form);
                echo '<p>';
                echo $this->formlabel($form->get('nombre_proyecto'));
                echo $this->formelement($form->get('nombre_proyecto'));
                echo '<p>';
                echo $this->formlabel($form->get('codigo_proyecto'));
                echo $this->formelement($form->get('codigo_proyecto'));
                echo '</div>';
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('fecha_inicio'));
                echo $this->formelement($form->get('fecha_inicio'));
                echo '</div>';
                echo '<div class="six columns">';
                echo '<p>';
                echo $this->formlabel($form->get('fecha_fin'));
                echo $this->formelement($form->get('fecha_fin'));
                echo '</div>';
                echo '<div class="twelve columns">';
                echo '<p>';
                echo $this->formlabel($form->get('resumen_ejecutivo'));
                echo $this->formelement($form->get('resumen_ejecutivo'));
                echo '<p>';
                echo $this->formlabel($form->get('objetivo_general'));
                echo $this->formelement($form->get('objetivo_general'));
                echo '<p>';
                echo $this->formlabel($form->get('productos_derivados'));
                echo $this->formelement($form->get('productos_derivados'));
                echo '<div>';        
                echo '<p>';
                echo $this->formlabel($form->get('image-file'));
                echo $this->formelement($form->get('image-file'));
                echo '<p>';
                echo $this->formelement($form->get('submit'));
                echo '</div" >';
                echo '<br>';
                
                echo $this->form()->closeTag($form);
                ?>
                <br>


                <?php
                

                ?>

</div>
</div>
</div>