<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>Eliminar el registro?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/editarinformem/eliminar/<?php echo $this->datos;?>/<?php echo $this->id2;?>">Eliminar Registro</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editarmonitor/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


