<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="twelve columns">
<a href="<?php echo $this->basePath() ?>/application/aprobacionm/index/<?php echo $this->id2;?>">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

	<?php
echo '<br>';echo '<br>';
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/editarinformem/index/'.$this->id.'/'.$this->id2,
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
if($this->menu==1){
				echo $this->formlabel($form->get('estado'));
				echo $this->formelement($form->get('estado'));
				echo '<p>';
				echo $this->formlabel($form->get('observaciones'));
				echo $this->formelement($form->get('observaciones'));
				echo '<p>';
}
				echo $this->formelement($form->get('submit'));
				echo '<br>';
				
				echo $this->form()->closeTag($form);
				?>
				<br>


				<?php
				

				?>

</div></div></div>