<script>
$(function () {
    var opts = $('#proyect option').map(function () {
        return [[this.value, $(this).text()]];
    });
    $('#someinput2').keyup(function () {
        var rxp = new RegExp($('#someinput2').val(), 'i');
        var optlist = $('#proyect').empty();
        opts.each(function () {
            if (rxp.test(this[1])) {
                optlist.append($('<option/>').attr('value', this[0]).text(this[1]));
            }
        });

    });

});
</script>
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>

				<div class="seven columns">
					<a
						href="<?php echo $this->basePath() ?>/application/editaraplicarm/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/agregarproyectosinv/index/'.$this->id."/".$this->id2,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo "<br>";
    echo '<p>';
    echo $this->formlabel($form->get('id_proyecto'));
    echo '<input id="someinput2">';
    echo '<p>';
    echo $this->formelement($form->get('id_proyecto'));
    echo '<p>';
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>

				<?php
    
    ?>
				</div>
			</div>
		</div>
	</div>
</div>