<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
                                <?php
                                    echo $this->titulo;
                                ?>
				            </h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
                    </br>
                    <?php
                        foreach ($this->dataDocumentos as $documento) {
                        
                            echo "<fieldset>";
                            switch ($documento["tipo_documento"]) {
                                case "linea":
                                    echo "<h4>Linea de investigación</h4>";
                                    break;
                                case "articulo":
                                    echo "<h4>Artículo de investigación</h4>";
                                    break;
                                case "libro":
                                    echo "<h4>Libro</h4>";
                                    break;
                                case "capitulo":
                                    echo "<h4>Capítulo de libro</h4>";
                                    break;
                                case "producciones":
                                    echo "<h4>Otra producción de investigación</h4>";
                                    break;
                                case "documentos":
                                    echo "<h4>Otro documento bibliográfico</h4>";
                                    break;
                                case "externos":
                                    echo "<h4>Proyecto de investigación externo</h4>";
                                    break;
                                case "internos":
                                    echo "<h4>Proyecto de investigación interno</h4>";
                                    break;
                            }
                            echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                            echo '<table class="table" style="width: 100%; max-width: 100%;">';
                            echo '<thead>';
                            echo '<th style="width: 10%;">Fecha de solicitud</th>';
                            if($documento["modulo"] == "1"){
                                echo '<th style="width: 30%;">Nombre grupo de estudio</th>';
                            }else if($documento["modulo"] == "2"){
                                echo '<th style="width: 30%;">Nombre Red de Investigación</th>';
                            }else{
                                echo '<th style="width: 30%;">Nombre Semillero de Investigación</th>';
                            }

                            
                            echo '<th style="width: 30%;">Nombre del solicitante</th>';
                            echo '<th style="width: 10%;">Estado de la solicitud</th>';
                            if($documento["estado_solicitud"]=="P"){
                                echo '<th style="width: 20%;">Aprobar solicitud</th>';
                            }
                            echo '</thead>';
                            echo '<tbody>';
                            echo '<td><center>';
                            echo $documento["fecha_solcitud"];
                            echo '</td></center>';
                            echo '<td><center>';
                            if($documento["modulo"] == "1"){
                                foreach ($this->Grupoinvestigacion as $grupo) {
                                    if($grupo["id_grupo_inv"] == $documento["id_grupoinv"]){
                                        echo $grupo["nombre_grupo"];
                                        break;
                                    }
                                }
                            }else if($documento["modulo"] == "2"){
                                foreach ($this->Redinvestigacion as $red) {
                                    if($red["id"] == $documento["id_grupoinv"]){
                                        echo $red["nombre"];
                                        break;
                                    }
                                }
                            }else{
                                foreach ($this->Semillero as $semillero) {
                                    if($semillero["id"] == $documento["id_grupoinv"]){
                                        echo $semillero["nombre"];
                                        break;
                                    }
                                }
                            }
                            
                            echo '</td></center>';
                            echo '<td><center>';
                            foreach ($this->usuarios as $usuario) {
                                if($usuario["id_usuario"] == $documento["id_usuario_solicitud"]){
                                    echo $usuario["primer_nombre"].' '.$usuario["segundo_nombre"].' '.$usuario["primer_apellido"].' '.$usuario["segundo_apellido"];
                                    break;
                                }
                            }
                            echo '</td></center>';
                            echo '<td><center>';
                                switch ($documento["estado_solicitud"]) {
                                    case "P":
                                        echo "<h5>Pendiente de aprobación</h5>";
                                        break;
                                    case "N":
                                        echo "<h5>No aprobada</h5>";
                                        break;
                                    case "A":
                                        echo "<h5>Aprobada</h5>";
                                        break;
                                }
                            echo '</td></center>';
                            if($documento["estado_solicitud"]=="P"){
                                echo '<td><center>';
                                    ?>
                                        <a class="btn" href="<?php echo $this->basePath() ?>/application/solicitudesvinculacion/aprobar/<?php echo $documento["id"];?>/A/<?php echo $this->id;?>">Aprobar</a>
                                    <?php
                                    ?>
                                        <a class="btn" href="<?php echo $this->basePath() ?>/application/solicitudesvinculacion/aprobar/<?php echo $documento["id"];?>/N/<?php echo $this->id;?>">No aprobar</a>
                                    <?php
                                echo '</td></center>';
                            }
                            
                            echo '</tbody>';
                            echo '</table>';
                            echo '</div>';
                            echo "</br>";

                            switch ($documento["tipo_documento"]) {
                                case "linea":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo '<th style="width: 20%;">Nombre</th>';
                                    echo '<th style="width: 20%;">Objetivo</th>';
                                    echo '<th style="width: 20%;">Efectos</th>';
                                    echo '<th style="width: 20%;">Logros</th>';
                                    echo '<th style="width: 20%;">Estado</th>';
                                    echo '</tr>';
                                    foreach ($this->lineashv as $li) {
                                        if($li["id_linea_inv"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $li["nombre_linea"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $li["objetivo"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $li["efectos"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $li["logros"];
                                            echo '</td>';
                                            echo '<td>';
                                            if ($li["id_estado"] == 1) {
                                                echo "Activa";
                                            } else {
                                                echo "Inactiva";
                                            }
                                            
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                    
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break; //Break linea
                                case "articulo":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 6%;'>Nombre revista</th>";
                                    echo "<th style='width: 6%;'>Nombre articulo</th>";
                                    echo "<th style='width: 5%;'>Categorización</th>";
                                    echo "<th style='width: 4%;'>Año</th>";
                                    echo "<th style='width: 4%;'>Mes</th>";
                                    echo "<th style='width: 4%;'>País</th>";
                                    echo "<th style='width: 4%;'>Ciudad</th>";
                                    echo "<th style='width: 5%;'>ISSN/e-ISSN</th>";
                                    echo "<th style='width: 8%;'>No. de páginas</th>";
                                    echo "<th style='width: 5%;'>Página inicio</th>";
                                    echo "<th style='width: 5%;'>Página fin</th>";
                                    echo "<th style='width: 5%;'>Fascículo</th>";
                                    echo "<th style='width: 5%;'>Volumen</th>";
                                    echo "<th style='width: 5%;'>No. serie</th>";
                                    echo "<th style='width: 14%;'>Autor(es)</th>";
                                    echo '</tr>';
                                    foreach ($this->Articuloshv as $art) {
                                        if($art["id_gi_articulo"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $art["nombre_revista"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["nombre_articulo"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vflex as $vl) {
                                                if ($vl["id_valor_flexible"] == $art["categoria"]) {
                                                    echo $vl["descripcion_valor"];
                                                }
                                            }
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["ano"];
                                            echo '</td>';
                                            echo '<td>';
                                            switch ($art["mes"]) {
                                                    case 1:
                                                        echo "Enero";
                                                        break;
                                                    case 2:
                                                        echo "Febrero";
                                                        break;
                                                    case 3:
                                                        echo "Marzo";
                                                        break;
                                                    case 4:
                                                        echo "Abril";
                                                        break;
                                                    case 5:
                                                        echo "Mayo";
                                                        break;
                                                    case 6:
                                                        echo "Junio";
                                                        break;
                                                    case 7:
                                                        echo "Julio";
                                                        break;
                                                    case 8:
                                                        echo "Agosto";
                                                        break;
                                                    case 9:
                                                        echo "Septiembre";
                                                        break;
                                                    case 10:
                                                        echo "Octubre";
                                                        break;
                                                    case 11:
                                                        echo "Noviembre";
                                                        break;
                                                    case 12:
                                                        echo "Diciembre";
                                                        break;
                                                }
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vflex as $vl) {
                                                if ($vl["id_valor_flexible"] == $art["id_pais"]) {
                                                    $art["id_pais"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $art["id_pais"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vflex as $vl) {
                                                if ($vl["id_valor_flexible"] == $art["id_ciudad"]) {
                                                    $art["id_pais"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $art["id_ciudad"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["issn"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["num_paginas"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["pagina_inicio"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["pagina_fin"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["fasciculo"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["volumen"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $art["serie"];
                                            echo '</td>';
                                            $autorAux="";
                                            foreach ($this->usuarios as $usa) {
                                                if ($usa["id_usuario"] == $art["id_autor"]) {
                                                    
                                                    $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                                }
                                            }
                                            foreach ($this->auto as $aut) {
                                                if ($art["id_gi_articulo"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Articuloshv') {
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                            $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                        }
                                                    }
                                                }
                                            }
                                            echo '<td>';
                                            echo $autorAux;
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                    
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break; //Break articulo
                                case "libro":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 10%;'>Título del libro</th>";
                                    echo "<th style='width: 4%;'>No. de Páginas</th>";
                                    echo "<th style='width: 4%;'>Año</th>";
                                    echo "<th style='width: 4%;'>Mes</th>";
                                    echo "<th style='width: 5%;'>País de publicación</th>";
                                    echo "<th style='width: 5%;'>Ciudad de publicación</th>";
                                    echo "<th style='width: 5%;'>Serie</th>";
                                    echo "<th style='width: 8%;'>Editorial</th>";
                                    echo "<th style='width: 6%;'>No. de Edición</th>";
                                    echo "<th style='width: 8%;'>ISBN ó e-ISBN</th>";
                                    echo "<th style='width: 8%;'>Medio de divulgación</th>";
                                    echo "<th style='width: 10%;'>Autor(es)</th>";
                                    echo '</tr>';
                                    foreach ($this->libros as $lib) {
                                        if($lib["id_gi_libro"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $lib["titulo_libro"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["num_paginas"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["ano"];
                                            echo '</td>';
                                            echo '<td>';
                                            switch ($lib["mes"]) {
                                                    case 1:
                                                        echo "Enero";
                                                        break;
                                                    case 2:
                                                        echo "Febrero";
                                                        break;
                                                    case 3:
                                                        echo "Marzo";
                                                        break;
                                                    case 4:
                                                        echo "Abril";
                                                        break;
                                                    case 5:
                                                        echo "Mayo";
                                                        break;
                                                    case 6:
                                                        echo "Junio";
                                                        break;
                                                    case 7:
                                                        echo "Julio";
                                                        break;
                                                    case 8:
                                                        echo "Agosto";
                                                        break;
                                                    case 9:
                                                        echo "Septiembre";
                                                        break;
                                                    case 10:
                                                        echo "Octubre";
                                                        break;
                                                    case 11:
                                                        echo "Noviembre";
                                                        break;
                                                    case 12:
                                                        echo "Diciembre";
                                                        break;
                                                }
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["pais"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["ciudad"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["serie"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["editorial"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["edicion"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["isbn"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $lib["medio_divulgacion"];
                                            echo '</td>';
                                            $autorAux="";
                                            foreach ($this->usuarios as $usa) {
                                                if ($usa["id_usuario"] == $lib["id_autor"]) {    
                                                    $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                                }
                                            }
                                            foreach ($this->auto as $aut) {
                                                if ($lib["id_gi_libro"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'Libroshv') {
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                            $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                        }
                                                    }
                                                }
                                            }
                                            echo '<td>';
                                            echo $autorAux;
                                            echo '</td>';    
                                            echo '</tr>';
                                        }
                                    }
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break; //break libro
                                case "capitulo":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 5%;'>Título del libro</th>";
                                    echo "<th style='width: 4%;'>Año</th>";
                                    echo "<th style='width: 3%;'>Mes</th>";
                                    echo "<th style='width: 4%;'>País de publicación</th>";
                                    echo "<th style='width: 4%;'>Ciudad de publicación</th>";
                                    echo "<th style='width: 4%;'>Serie</th>";
                                    echo "<th style='width: 5%;'>Editorial</th>";
                                    echo "<th style='width: 5%;'>No. de Edición</th>";
                                    echo "<th style='width: 7%;'>ISBN ó e-ISBN</th>";
                                    echo "<th style='width: 7%;'>Medio de divulgación</th>";
                                    echo "<th style='width: 6%;'>Título del capítulo</th>";
                                    echo "<th style='width: 3%;'>No. de capítulo</th>";
                                    echo "<th style='width: 4%;'>Páginas del capítulo</th>";
                                    echo "<th style='width: 3%;'>Página inicio</th>";
                                    echo "<th style='width: 3%;'>Página fin</th>";
                                    echo "<th style='width: 7%;'>Autor</th>";
                                    echo '<tr>';
                                    foreach ($this->capitulos as $int) {
                                        if($int["id"] == $documento["id_documento"]){
                                            echo '<tr>';
                                                echo '<td>';
                                                echo $int["titulo"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["ano"];
                                                echo '</td>';
                                            
                                                echo '<td>';
                                                switch ($int["mes"]) {
                                                    case 1:
                                                        echo "Enero";
                                                        break;
                                                    case 2:
                                                        echo "Febrero";
                                                        break;
                                                    case 3:
                                                        echo "Marzo";
                                                        break;
                                                    case 4:
                                                        echo "Abril";
                                                        break;
                                                    case 5:
                                                        echo "Mayo";
                                                        break;
                                                    case 6:
                                                        echo "Junio";
                                                        break;
                                                    case 7:
                                                        echo "Julio";
                                                        break;
                                                    case 8:
                                                        echo "Agosto";
                                                        break;
                                                    case 9:
                                                        echo "Septiembre";
                                                        break;
                                                    case 10:
                                                        echo "Octubre";
                                                        break;
                                                    case 11:
                                                        echo "Noviembre";
                                                        break;
                                                    case 12:
                                                        echo "Diciembre";
                                                        break;
                                                }
                                                echo '</td>';
                                            
                                                echo '<td>';
                                                echo $int["pais"];
                                                echo '</td>';
                                            
                                                echo '<td>';
                                                echo $int["ciudad"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["serie"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["editorial"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["edicion"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["isbn"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["medio_divulgacion"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["titulo_capitulo"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["numero_capitulo"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["paginas_capitulo"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["pagina_inicio"];
                                                echo '</td>';

                                                echo '<td>';
                                                echo $int["pagina_fin"];
                                                echo '</td>';

                                                echo '<td>';
                                                $autores="";
                                                foreach ($this->usuarios as $usa) {
                                                    if ($usa["id_usuario"] == $int["id_autor"]) {
                                                        $autores .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                                    }
                                                }
                                                foreach ($this->autoresusuario as $autor) {
                                                    if($autor["seccion"]=="3" && $autor["id_objeto"]==$int["id"]){
                                                        foreach ($this->usuarios as $usuario) {
                                                            if($usuario["id_usuario"]==$autor["id_usuario"]){
                                                                $autores .= $usuario["primer_nombre"]." ".$usuario["segundo_nombre"]." ".$usuario["primer_apellido"]." ".$usuario["segundo_apellido"]." - ";    
                                                            }    
                                                        }
                                                    }
                                                }
                                                echo $autores;
                                                echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break; //break capitulo de libro
                                case "producciones":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 10%;'>Nombre producto</th>";
                                    echo "<th style='width: 10%;'>Descripción producto</th>";
                                    echo "<th style='width: 10%;'>Tipo producto</th>";
                                    echo "<th style='width: 3%;'>Año</th>";
                                    echo "<th style='width: 3%;'>Mes</th>";
                                    echo "<th style='width: 4%;'>Pais</th>";
                                    echo "<th style='width: 5%;'>Ciudad</th>";
                                    echo "<th style='width: 10%;'>Instituciones participantes</th>";
                                    echo "<th style='width: 10%;'>Registro</th>";
                                    echo "<th style='width: 10%;'>Otra información</th>";
                                    echo "<th style='width: 10%;'>Autor(es)</th>";
                                    echo '</tr>';
                                    foreach ($this->Otrasproduccioneshv as $ot) {
                                        if($ot["id_otra_prod"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $ot["nombre_producto"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["descripcion_producto"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["tipo_producto"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["ano"];
                                            echo '</td>';
                                            echo '<td>';
                                            switch ($ot["mes"]) {
                                                case 1:
                                                    echo "Enero";
                                                    break;
                                                case 2:
                                                    echo "Febrero";
                                                    break;
                                                case 3:
                                                    echo "Marzo";
                                                    break;
                                                case 4:
                                                    echo "Abril";
                                                    break;
                                                case 5:
                                                    echo "Mayo";
                                                    break;
                                                case 6:
                                                    echo "Junio";
                                                    break;
                                                case 7:
                                                    echo "Julio";
                                                    break;
                                                case 8:
                                                    echo "Agosto";
                                                    break;
                                                case 9:
                                                    echo "Septiembre";
                                                    break;
                                                case 10:
                                                    echo "Octubre";
                                                    break;
                                                case 11:
                                                    echo "Noviembre";
                                                    break;
                                                case 12:
                                                    echo "Diciembre";
                                                    break;
                                            }
                                            echo '</td>';
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vflex as $vl) {
                                                if ($vl["id_valor_flexible"] == $ot["id_pais"]) {
                                                    $ot["id_pais"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $ot["id_pais"];
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($this->vflex as $vl) {
                                                if ($vl["id_valor_flexible"] == $ot["id_ciudad"]) {
                                                    $ot["id_pais"] = $vl["descripcion_valor"];
                                                }
                                            }
                                            echo $ot["id_ciudad"];
                                            echo '</td>';
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["instituciones"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["registro"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $ot["otra_info"];
                                            echo '</td>';
                                            $autorAux="";
                                            foreach ($this->usuarios as $usa) {
                                                if ($usa["id_usuario"] == $ot["id_autor"]) {    
                                                    $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                                }
                                            }
                                            foreach ($this->auto as $aut) {
                                                if ($ot["id_otra_prod"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'otra_prodhv') {
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                            $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                        }
                                                    }
                                                }
                                            }
                                            echo '<td>';
                                            echo $autorAux;
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }  
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break; //break otra producción de investigación
                                case "documentos":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 6%;'>Nombre</th>";
                                    echo "<th style='width: 3%;'>No. Páginas</th>";
                                    echo "<th style='width: 3%;'>Año</th>";
                                    echo "<th style='width: 3%;'>Mes</th>";
                                    echo "<th style='width: 4%;'>Pais</th>";
                                    echo "<th style='width: 4%;'>Ciudad</th>";
                                    echo "<th style='width: 10%;'>Indexación</th>";
                                    echo "<th style='width: 15%;'>Instituciones participantes</th>";
                                    echo "<th style='width: 5%;'>URL</th>";
                                    echo "<th style='width: 14%;'>Descripción</th>";
                                    echo "<th style='width: 12%;'>Medio de divulgación</th>";
                                    echo "<th style='width: 6%;'>Autor(es)</th>";
                                    echo '</tr>';
                                    foreach ($this->Bibliograficoshv as $bli) {
                                        if($bli["id_bibliografico"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $bli["nombre_documento"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["numero_paginas"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["ano"];
                                            echo '</td>';
                                            echo '<td>';
                                            switch ($bli["mes"]) {
                                                case 1:
                                                    echo "Enero";
                                                    break;
                                                case 2:
                                                    echo "Febrero";
                                                    break;
                                                case 3:
                                                    echo "Marzo";
                                                    break;
                                                case 4:
                                                    echo "Abril";
                                                    break;
                                                case 5:
                                                    echo "Mayo";
                                                    break;
                                                case 6:
                                                    echo "Junio";
                                                    break;
                                                case 7:
                                                    echo "Julio";
                                                    break;
                                                case 8:
                                                    echo "Agosto";
                                                    break;
                                                case 9:
                                                    echo "Septiembre";
                                                    break;
                                                case 10:
                                                    echo "Octubre";
                                                    break;
                                                case 11:
                                                    echo "Noviembre";
                                                    break;
                                                case 12:
                                                    echo "Diciembre";
                                                    break;
                                            }
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["pais"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["ciudad"];
                                            echo '</td>';        
                                            echo '<td>';
                                            echo $bli["num_indexacion"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["instituciones"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["url"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["descripcion"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $bli["medio_divulgacion"];
                                            echo '</td>';
                                            $autorAux="";
                                            foreach ($this->usuarios as $usa) {
                                                if ($usa["id_usuario"] == $bli["id_autor"]) {    
                                                    $autorAux .= trim($usa["primer_nombre"]).' '.trim($usa["segundo_nombre"]).' '.trim($usa["primer_apellido"]).' '.trim($usa["segundo_apellido"])." - ";
                                                }
                                            }
                                            foreach ($this->auto as $aut) {
                                                if ($bli["id_bibliografico"] == $aut["id_padre"] && trim($aut["nombre_padre"]) == 'bibliograficohv') {
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $aut["id_usuario"]) {
                                                            $autorAux .= trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"])." - ";
                                                        }
                                                    }
                                                }
                                            }
                                            echo '<td>';
                                            echo $autorAux;
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break;//Break otros documentos bibliograficos
                                case "externos":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 5%;'>Código del proyecto</th>";
                                    echo "<th style='width: 4%;'>Nombre del proyecto</th>";
                                    echo "<th style='width: 5%;'>Fecha inicio</th>";
                                    echo "<th style='width: 5%;'>Fecha fin</th>";
                                    echo "<th style='width: 9%;'>Resumen ejecutivo</th>";
                                    echo "<th style='width: 9%;'>Objetivo general</th>";
                                    echo "<th style='width: 9%;'>Equipo de trabajo</th>";
                                    echo "<th style='width: 9%;'>Productos derivados</th>";
                                    echo '</tr>';
                                    foreach ($this->Proyectosexthv as $proyext) {
                                        if($proyext["id_proyecto_ext"] == $documento["id_documento"]){
                                            echo '<tr>';
                                            echo '<td>';
                                            echo $proyext["codigo_proyecto"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyext["nombre_proyecto"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyext["fecha_inicio"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyext["fecha_fin"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyext["resumen_ejecutivo"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo $proyext["objetivo_general"];
                                            echo '</td>';
                                            echo '<td>';
                                            echo '<table style="border-style: hidden;">';
                                            foreach ($this->auto as $auts) {
                                                if ($proyext["id_proyecto_ext"] == $auts["id_padre"] && trim($auts["nombre_padre"]) == 'proy_exthv') {
                                                    foreach ($this->vflex as $v) {
                                                        if ($v["id_valor_flexible"] == $auts["id_rol"]) {
                                                            $rol = $v["descripcion_valor"];
                                                        }
                                                    }
                                                    foreach ($this->usuarios as $ua) {
                                                        if ($ua["id_usuario"] == $auts["id_usuario"]) {
                                                            echo '<tr><td>'.trim($ua["primer_nombre"]).' '.trim($ua["segundo_nombre"]).' '.trim($ua["primer_apellido"]).' '.trim($ua["segundo_apellido"]).'</td><td>'.$rol.'</td>';
                                                            echo '</tr>';
                                                        }
                                                    }
                                                }
                                            }
                                            echo '</table></td>';
                                            echo '<td>';
                                            echo $proyext["productos_derivados"];
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break;//Break proyecto de investigación externo
                                 case "internos":
                                    echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
                                    echo '<table class="table" style="width: 100%; max-width: 100%;">';
                                    echo '<thead>';
                                    echo "<th style='width: 5%;'>Código del proyecto</th>";
                                    echo "<th style='width: 5%;'>Nombre del proyecto</th>";
                                    echo "<th style='width: 5%;'>Investigador principal</th>";
                                    echo "<th style='width: 5%;'>Duración</th>";
                                    echo "<th style='width: 5%;'>Unidad académica</th>";
                                    echo "<th style='width: 15%;'>Dependencia académica</th>";
                                    echo "<th style='width: 15%;'>Resumen ejecutivo</th>";
                                    echo "<th style='width: 20%;'>Objetivo general</th>";
                                    echo "<th style='width: 10%;'>Equipo de trabajo</th>";
                                    echo '</tr>';
                                    foreach ($this->Proyectosintusua as $proyint) {
                                        if($proyint["id"] == $documento["id_documento"]){
                                            foreach ($this->proyectos as $proyectosT) {
                                                if($proyint["id_proyecto"]==$proyectosT["id_proyecto"]){
                                                       echo '<tr>';
                                                        echo '<td>';
                                                        echo $proyectosT["codigo_proy"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        echo $proyectosT["nombre_proy"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        foreach ($this->usuarios as $ua) {
                                                            if ($ua["id_usuario"] == $proyectosT["id_investigador"]) {
                                                                echo trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]);
                                                            }
                                                        }
                                                        echo '</td>';
                                                        echo '<td>';
                                                        echo $proyectosT["duracion"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        foreach ($this->vflex as $vl) {
                                                            if ($vl["id_valor_flexible"] == $proyectosT["id_unidad_academica"]) {
                                                                $proyectosT["id_unidad_academica"] = $vl["descripcion_valor"];
                                                            }
                                                        }
                                                        echo $proyectosT["id_unidad_academica"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        foreach ($this->vflex as $vl) {
                                                            if ($vl["id_valor_flexible"] == $proyectosT["id_dependencia_academica"]) {
                                                                $proyectosT["id_dependencia_academica"] = $vl["descripcion_valor"];
                                                            }
                                                        }
                                                        echo $proyectosT["id_dependencia_academica"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        echo $proyectosT["resumen_ejecutivo"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        echo $proyectosT["objetivo_general"];
                                                        echo '</td>';
                                                        echo '<td>';
                                                        echo '<table style="border-style: hidden;">';
                                                        $rol="";
                                                        foreach ($this->Tablaequipop as $auts) {
                                                            if ($proyectosT["id_proyecto"] == $auts["id_proyecto"]) {
                                                                foreach ($this->vflex as $v) {
                                                                    if ($v["id_valor_flexible"] == $auts["id_rol"]) {
                                                                        $rol = $v["descripcion_valor"];
                                                                    }
                                                                }
                                                                foreach ($this->usuarios as $ua) {
                                                                    if ($ua["id_usuario"] == $auts["id_integrante"]) {
                                                                        echo '<tr><td>'.trim($ua["primer_nombre"]) . ' ' . trim($ua["segundo_nombre"]). ' ' . trim($ua["primer_apellido"]). ' ' . trim($ua["segundo_apellido"]). '</td><td>'.$rol.'</td>';
                                                                        echo '</tr>';
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        echo '</table></td>';
                                                        echo '</td>';
                                                }
                                            }
                                        }
                                    }
                                    echo '</tr>';
                                    echo '</table>';
                                    echo '</div>';
                                    break;//Break proyecto de investigación interno
                            }
                            echo "</fieldset>";
                            echo "</br>";
                            echo "</br>";
                        }
                    ?>		
                </div>
			</div>
		</div>
    </div>
</div>