		<?php
			include("public/menu.php"); 
		?>
		<div id="wrapper_1">
			<div id="container_1">
				<div class="row2">
					<div class="nine3 columns">
						<div id="centersectiontitle">
							<div class="twelve columns">
								<div class="sidebartitle">
									<h3>
	                					<?php echo $this->titulo; ?>
									</h3>
								</div>
							</div>
						</div>
						<!-- FILTROS -->
						<div class="twelve columns">
							<a href="<?php echo $this->basePath() ?>/application/reportes/index"><i class="icon-arrow-left"></i> Regresar</a><br> <br>
				<?php
			    $form = $this->form;
			    $form->prepare();
			    echo '<a class="btn" href="'.$this->basePath().'/application/pdfredes/index">Reporte en PDF</a>';
				echo '</br>';
				echo '</br>';
				echo '<a class="btn" href="'.$this->basePath().'/application/excelredes/index">Reporte en Excel</a>';
				echo '</br>';
				echo '</br>';
			    ?>
				<br>
				</div>
			</div>
		</div>
	</div>
</div>