<style>
	.filter-group input[type="text"],select{
		width: 100%;
	}
	.filter-group {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-group-left {float: left;}
	.filter-group-right {float:right;}
	.filter-group .btn {width: 275px;}
	.filter-group .dropdown {display: inline;}
	.filter-group .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
	.dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-group">
		<div class="filter-group-left">
			<h4>
				<?php
					if($this->nombre_padre=="Libros"|| $this->nombre_padre=="Libroshv" || $this->nombre_padre=="Articuloshv"|| $this->nombre_padre=="Articulos" || $this->nombre_padre=="otra_prodhv" || $this->nombre_padre=="otra_prod"){
					echo $this->titulo2;					
					}elseif($this->nombre_padre=="proy_ext" | $this->nombre_padre=="proy_exthv"){
					echo $this->titulo3;
					}
					else{
					echo $this->titulo;
					}
				?>
			</h4>
		</div>
		<div class="filter-group-right">
			<?php
			if($this->nombre_padre=="Articuloshv" || $this->nombre_padre=="Libroshv" || $this->nombre_padre=="bibliograficohv" || $this->nombre_padre=="otra_prodhv" || $this->nombre_padre=="proy_exthv"){
			?>
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id_grupo; ?>"><i class="icon-arrow-left"></i>Regresar</a>
			<?php
			}else{
			?>
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/editargrupoinv/index/<?php echo $this->id_grupo; ?>"><i class="icon-arrow-left"></i>Regresar</a>
			<?php } ?>
			<a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/agregarcoautor/index/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
			<div class="dropdown">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="dropdown-menu-inner">
						<?php								
						$form = $this->form;
						$form->prepare ();
						echo $this->form ()->openTag ( $form );
						echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
						echo $this->formlabel($form->get('documento'));
						echo $this->formelement($form->get('documento'));
						echo $this->formlabel($form->get('nombre'));
						echo $this->formelement($form->get('nombre'));
						echo $this->formlabel($form->get('apellido'));
						echo $this->formelement($form->get('apellido'));
						echo $this->formlabel($form->get('usuario'));
						echo $this->formelement($form->get('usuario'));
						echo $this->formelement ( $form->get ( 'submit' ) );
 						echo $this->form ()->closeTag ( $form );
 						?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col col100 noshadow">
	<?php
 echo "<div style='overflow-y:auto; max-height:410px; width: 100%;'>";
 echo '<table class="table" style="width: 100%; max-width: 100%;">';
echo '<thead>';
				echo '<th style="width: 80%;">Autor</th>';
				echo '<th style="width: 10%;">Asignar autor</th>';
				echo '<th style="width: 10%;">Quitar autor</th>';
echo '</thead>';
echo '<tbody>';
				foreach ($this->datos as $dato){
				echo '<tr>';
				echo '<td>';
					echo $dato["primer_nombre"]." ".$dato["segundo_nombre"]." ".$dato["primer_apellido"]." ".$dato["segundo_apellido"];
				echo'</td>';
				echo '<td style="text-align:center;">';
if($this->nombre_padre=="Libros" || $this->nombre_padre=="libroshv" || $this->nombre_padre=="otra_prodhv" || $this->nombre_padre=="otra_prod" || $this->nombre_padre=="Articuloshv" || $this->nombre_padre=="Articulos" ){
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/asignar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-plus"></i></a>
				<?php
}elseif($this->nombre_padre=="proy_ext" || $this->nombre_padre=="proy_exthv"){
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/asignar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-plus"></i></a>
				<?php
}else{
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/asignar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-plus"></i></a>
				<?php
}
				echo'</td>';
				echo '<td style="text-align:center;">';
if($this->nombre_padre=="Libros" || $this->nombre_padre=="libroshv" || $this->nombre_padre=="Articuloshv" || $this->nombre_padre=="Articulos" || $this->nombre_padre=="otra_prodhv" || $this->nombre_padre=="otra_prod"){
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/eliminar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-pencil"></i></a>
				<?php
}elseif($this->nombre_padre=="proy_ext"  || $this->nombre_padre=="proy_exthv"){
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/eliminar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-pencil"></i></a>
				<?php
}else{
				?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/agregarcoautor/eliminar/<?php echo $dato["id_usuario"];?>/<?php echo $id_grupo ?>/<?php echo $this->id_padre ?>/<?php echo $this->nombre_padre ?>"><i class="fa fa-pencil"></i></a>
				<?php
}
				echo'</td>';
				echo '</tr>';
				}
				
				echo '</tr>';
				echo '</table>';
				echo '</div>';
				?>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/public/js/viejo/bootstrap.min.js"></script>
