<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
<center>
<h6>¿Eliminar la producción de investigación?</h6>
<a class="btn" href="<?php echo $this->basePath() ?>/application/produccionesinvsemillero/eliminar/<?php echo $this->id;?>/<?php echo $this->id2;?>">Eliminar</a>

<a class="btn" href="<?php echo $this->basePath() ?>/application/editarsemilleroinv/index/<?php echo $this->id2;?>">Cancelar</a>

		<br><br>	</div>
		</div>
	</div>
			</div>
	


