<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;
    }

    .alineadoDerecha {
        float: right;
    }
</style>
<script type="text/javascript">
	function showHint(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#id_autor>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>
<script type="text/javascript">
	function showHintInvestigador(str) {
		var valthis = str.toLowerCase();
	    var num = 0;

	    $('select#id_investigador>option').each(function () {
	          var text = $(this).text().toLowerCase();
	          if(text.indexOf(valthis) !== -1)  
	              {$(this).show(); $(this).prop('selected',true);}
	          else{$(this).hide();}
	           });
	}
</script>
<script type="text/javascript">
    function myFunction2() {
        var dependenciasAca = document.getElementById("id_dependencia");
        for (i = 0; i < dependenciasAca.length; i++) {
            if (dependenciasAca.options[i].value != '') {
                var option = dependenciasAca.options[i]; // item
                var id = dependenciasAca.options[i].value.split(/-/); // extrae el id del padre    
                var idPadreValorFlexible = id[1];
                //valida que el item de la iteracion es del padre seleccionado
                if (idPadreValorFlexible == document.getElementById("id_unidad").value.split(/-/)[0]) {
                    option.style.display = "block";
                } else {
                    option.style.display = "none";
                }
                // Selecciona el placeholder por defecto en linea
                if (option.text == "") {
                    option.selected = true;
                }
            }
        }
        document.getElementById("id_dependencia").value = "";
        document.getElementById("id_programa").value = "";
    }

    function myFunction3() {
        var programaAca = document.getElementById("id_programa");
        for (i = 0; i < programaAca.length; i++) {
            if (programaAca.options[i].value != '') {
                var option = programaAca.options[i]; // item
                var id = programaAca.options[i].value.split(/-/); // extrae el id del padre    
                var idPadreValorFlexible = id[1];
                //valida que el item de la iteracion es del padre seleccionado
                if (idPadreValorFlexible == document.getElementById("id_dependencia").value.split(/-/)[0]) {
                    option.style.display = "block";
                } else {
                    option.style.display = "none";
                }
                // Selecciona el placeholder por defecto en linea
                if (option.text == "") {
                    option.selected = true;
                }
            }
        }
        document.getElementById("id_programa").value = "";
    }
</script>

<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editarusuario/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>
				<div class="twelve columns">
					<h3>
						Trabajo de grado
					</h3>
				</div>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('nombre_trabajo'));
echo $this->formelement($form->get('nombre_trabajo'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_tipotrabajo'));
echo $this->formelement($form->get('id_tipotrabajo'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_estadotipotrabajo'));
echo $this->formelement($form->get('id_estadotipotrabajo'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_tipoparticipacion'));
echo $this->formelement($form->get('id_tipoparticipacion'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_autor'));
echo $this->formelement($form->get('filtro_autor'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formelement($form->get('id_autor'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_institucion'));
echo $this->formelement($form->get('id_institucion'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('ciudad_trabajo'));
echo $this->formelement($form->get('ciudad_trabajo'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_unidad'));
echo $this->formelement($form->get('id_unidad'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_dependencia'));
echo $this->formelement($form->get('id_dependencia'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_programa'));
echo $this->formelement($form->get('id_programa'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_inicio'));
echo $this->formelement($form->get('fecha_inicio'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_fin'));
echo $this->formelement($form->get('fecha_fin'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('descripcion'));
echo $this->formelement($form->get('descripcion'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('otra_informacion'));
echo $this->formelement($form->get('otra_informacion'));
echo '</div>';
echo '</br>';
?>	
<div class="twelve columns">
	<h3>
		Proyectos de investigación con formación
	</h3>
</div>
<br />
<?php
echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_formacioninvestigador'));
echo $this->formelement($form->get('id_formacioninvestigador'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('codigo_proyecto'));
echo $this->formelement($form->get('codigo_proyecto'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('nombre_proyecto'));
echo $this->formelement($form->get('nombre_proyecto'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_investigador'));
echo $this->formelement($form->get('filtro_investigador'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formelement($form->get('id_investigador'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('id_institucion_proyecto'));
echo $this->formelement($form->get('id_institucion_proyecto'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('ciudad_proyecto'));
echo $this->formelement($form->get('ciudad_proyecto'));
echo '</div>';

echo '<div class="four columns">';
echo '<p>';
echo $this->formlabel($form->get('personas_formadas'));
echo $this->formelement($form->get('personas_formadas'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_inicio_proyecto'));
echo $this->formelement($form->get('fecha_inicio_proyecto'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_fin_proyecto'));
echo $this->formelement($form->get('fecha_fin_proyecto'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('descripcion_proyecto'));
echo $this->formelement($form->get('descripcion_proyecto'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('descripcion_formacion'));
echo $this->formelement($form->get('descripcion_formacion'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('otra_informacion_proyecto'));
echo $this->formelement($form->get('otra_informacion_proyecto'));
echo '</div>';
?>	
<div class="twelve columns">
	<h3>
		Semillero de investigación
	</h3>
</div>
<br />
<?php
echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('id_semillero'));
echo $this->formelement($form->get('id_semillero'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_institucion_semillero'));
echo $this->formelement($form->get('id_institucion_semillero'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('id_rolparticipacion'));
echo $this->formelement($form->get('id_rolparticipacion'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_inicio_semillero'));
echo $this->formelement($form->get('fecha_inicio_semillero'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('fecha_fin_semillero'));
echo $this->formelement($form->get('fecha_fin_semillero'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('tematica'));
echo $this->formelement($form->get('tematica'));
echo '</div>';

echo '<div class="twelve columns">';
echo '<p>';
echo $this->formlabel($form->get('descripcion_semillero'));
echo $this->formelement($form->get('descripcion_semillero'));
echo '</div>';

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));
echo '<p>';
echo '<div>';
echo $this->formelement($form->get('submit'));
echo '</div>';
echo '</div>';

echo '</br>';
echo '</br>';

echo $this->form()->closeTag($form);
?>			
</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>