<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
								<?php
							    	echo $this->titulo;
							    ?>
							</h3>
						</div>
					</div>
				</div>
				<div class="six columns">
					<a href="<?php echo $this->basePath() ?>/application/editarsemilleroinv/index/<?php echo $this->id; ?>">
						<i class="icon-arrow-left"></i> Regresar
					</a>
				</div>
				</br>
				</br>
				</br>
				</br>
				</br>

<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array('action'=> $this->url.'/application/participacioneventos/index/'.$this->id.'/'.$this->id2,'method'=>'post'));
echo $this->form()->openTag($form);

echo '<div class="six columns">';
echo '<p>';
echo $this->formlabel($form->get('nombre'));
echo $this->formelement($form->get('nombre'));

echo '<p>';
echo $this->formlabel($form->get('tipo_participacion'));
echo $this->formelement($form->get('tipo_participacion'));


echo '<p>';
echo $this->formlabel($form->get('image-file'));
echo $this->formelement($form->get('image-file'));
echo '</div>';

echo '<div class="six columns">';

echo '<p>';
echo $this->formlabel($form->get('lugar'));
echo $this->formelement($form->get('lugar'));

echo '<p>';
echo $this->formlabel($form->get('fecha'));
echo $this->formelement($form->get('fecha'));

echo '<p>';
echo $this->formelement($form->get('submit'));
echo '</div>';

echo $this->form()->closeTag($form);
?>				


</div><!-- Cierre div six columns --> 
			</div>
		</div>
	</div>
</div>