<style>
	.filter-submod {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
	.filter-submod-left {float: left;}
	.filter-submod-right {float: right;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
	<div class="filter-submod">
		<div class="filter-submod-left"><h4><?php echo $this->titulo; ?></h4></div>
		<div class="filter-submod-right"><a class="btn" href="<?php echo $this->basePath() ?>/application/gestionpantallas/index"><i class="fa fa-arrow-left"></i> Regresar</a></div>
	</div>
</div>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
		<table class="table" style="width: 100%; max-width: 100%;">
			<thead>
				<tr>
					<th style="width:5%">Nombre del módulo</th>
					<th style="width:5%">Nombre del submódulo</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->submodulos as $submodulo) {	?>
				<tr>
					<?php foreach ($this->modulos as $modulo){
						if($modulo["id"]==$submodulo["id_modulo"]){
					?>
							<td><?php echo $modulo ["nombre"]; ?></td>
					<?php
						}
					}
					?>
					<td><?php echo $submodulo ["nombre"]; ?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
</div>
