<style>
    .filter-cons input[type="text"],select{
        width: 100%;
    }
    .filter-cons {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .filter-cons-left {float: left;}
    .filter-cons-right {float:right;}
    .filter-cons .btn {width: 275px;}
    .filter-cons .dropdown {display: inline;}
    .filter-cons .dropdown-menu {width: 300px;top: 32px;padding: 10px;}
    .dropdown-menu-inner {background: #E5E9F2;padding: 10px;display: inline-block; width: 100%;}
    .dropdown-menu-right {left:-140px !important;}
</style>
<?php include("public/menu.php"); ?>
<div class="col col100">
    <div class="filter-cons">
        <div class="filter-cons-left"><h4><?php echo $this->titulo; ?></h4></div>
        <div class="filter-cons-right">
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/editarproyecto/index/<?php echo $this->grupo; ?>"><i class="icon-arrow-left"></i> Regresar</a>
            <a class="btn" style="margin-right: 8px;" href="<?php echo $this->basePath() ?>/application/tablaequipop/index/<?php echo $this->grupo; ?>/0/0/<?php echo $this->id4; ?>/1"><i class="fa fa-close" style="margin-right: 5px;"></i>Borrar filtro</a>
            <div class="dropdown">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-right: 8px;"><i class="fa fa-filter" style="margin-right: 5px;"></i>Filtro</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-menu-inner">
                        <?php                               
                        $form = $this->form;
                        $form->prepare ();
                        echo $this->form ()->openTag ( $form );
                        echo '<h6>'.$this->flashMessenger ()->render ().'</h6>';
                        echo $this->formlabel($form->get('documento'));
						echo $this->formelement($form->get('documento'));
						echo $this->formlabel($form->get('primer_nombre'));
						echo $this->formelement($form->get('primer_nombre'));
						echo $this->formlabel($form->get('segundo_nombre'));
						echo $this->formelement($form->get('segundo_nombre'));
						echo $this->formlabel($form->get('primer_apellido'));
						echo $this->formelement($form->get('primer_apellido'));
						echo $this->formlabel($form->get('segundo_apellido'));
						echo $this->formelement($form->get('segundo_apellido'));
						echo $this->formlabel($form->get('usuario'));
						echo $this->formelement($form->get('usuario'));
                        echo $this->formelement($form->get('submit'));
                        echo $this->form ()->closeTag ( $form );
                        ?>
                    </div>                      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col col100 noshadow">
	<div style='overflow-y:auto; max-height:4000px; width: 100%;'>
<?php
    echo '<table class="table" style="width: 100%; max-width: 100%;">';
    echo '<thead>';
    echo '<th>Usuarios</th>';
    echo '<th>Asignar integrante</th>';
    echo '</tr>';
    foreach ($this->datos as $dato) {
        echo '</thead>';
        echo '<tbody>';
        echo '<td>';
        echo $dato["primer_nombre"] ." ". $dato["segundo_nombre"]." ". $dato["primer_apellido"]." ". $dato["segundo_apellido"];
        echo '</td>';
        echo '<td>';
        
        if ($this->id5 == 1) {
            ?>
<a class="btn"
						href="<?php echo $this->basePath() ?>/application/tablaequipop/asignar/<?php echo $dato["id_usuario"];?>/<?php echo $this->grupo ?>/<?php echo $this->id2 ?>/<?php echo $this->id3 ?>/<?php echo $this->id4 ?>/<?php echo $this->id5 ?>">Asignar
						Integrante</a>
<?php
        } else {
            ?>
<a class="btn"
						href="<?php echo $this->basePath() ?>/application/tablaequipop/asignar/<?php echo $dato["id_usuario"];?>/<?php echo $this->grupo ?>/<?php echo $this->id2 ?>/<?php echo $this->id3 ?>/<?php echo $this->id4 ?>">Asignar
						Integrante</a>

				<?php
        }
        echo '</td>';
        echo '</tr>';
    }
    
    echo '</tr>';
    echo '</table>';
    ?>		
	</div>
</div>

