<div class="row">
	<div class="nine columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<center>
					<h6>¿Seleccionar monitor?</h6>
					<?php
						if($this->id2!="0"){
							?>
								<a style="background: yellow; color: black;" class="btn" href="<?php echo $this->basePath() ?>/application/entrevistam/seleccionarmAct/<?php echo $this->id;?>/1/<?php echo $this->id2;?>/<?php echo $this->id3;?>/<?php echo $this->id4;?>"><strong>Seleccionar</strong></a>
							<?php
						}else{
							?>
								<h5>Este estudiante no se puede seleccionar ya que el proyecto no cuenta con plazas disponibles.</h5>
							<?php
						}

					?>
					
					<a style="background: red; color: white;" class="btn" href="<?php echo $this->basePath() ?>/application/entrevistam/seleccionarmAct/<?php echo $this->id;?>/0/<?php echo $this->id2;?>/<?php echo $this->id3;?>/<?php echo $this->id4;?>">No seleccionar</a>
					<a class="btn" href="<?php echo $this->basePath() ?>/application/consultaprocesom/index"><strong>Cancelar</strong></a>
				<br><br>
				</center>	
			</div>
		</div>
	</div>
</div>
	


