<style>
    textarea {
        height: 100px;
        width: 100%;
        max-width: 100%;

    }
</style> 
<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
		<div class="row2">
			<div class="nine3 columns">
				<div id="centersectiontitle">
					<div class="twelve columns">
						<div class="sidebartitle">
							<h3>
				<?php
    echo $this->titulo;
    ?>
				</h3>
						</div>
					</div>
				</div>
				<div class="twelve columns">
				<a
					href="<?php echo $this->basePath() ?>/application/entrevistam/index/<?php echo $this->id ?>" >
					<i class="icon-arrow-left"></i> Regresar
				</a>
				</br>
				</br>
				<?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttributes(array(
        'action' => $this->url . '/application/evaluarcriterio/index/' .$this->id."/".$this->id2,
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    echo '<p>';
    echo $this->formlabel($form->get('criterio'));
    echo $this->formelement($form->get('criterio'));
	echo '<p>';
    echo $this->formlabel($form->get('evaluacion_cualitativa'));
    echo $this->formelement($form->get('evaluacion_cualitativa'));
    echo '<p>';
    echo $this->formlabel($form->get('evaluacion_cuantitativa'));
    echo $this->formelement($form->get('evaluacion_cuantitativa'));
    echo '</br>';
    echo "* Por favor ingresar un valor entre 0 y 5, con dos decimales. Ejemplo: 3.45";
    echo '<p>';
    echo '<br>';
    echo '<br>';
    echo $this->formelement($form->get('submit'));
    echo '<br>';
    
    echo $this->form()->closeTag($form);
    ?>
				<br>
				</div>
			</div>
		</div>
	</div>
</div>