<?php include("public/menu.php"); ?>
<div id="wrapper_1">
	<div id="container_1">
<div class="row2">
	<div class="nine3 columns">
		<div id="centersectiontitle">
			<div class="twelve columns">
				<div class="sidebartitle"><h3>
				<?php
					echo $this->titulo;
				?>
				</h3>
			</div>
		</div>
	</div>
<div class="four columns">
<?php
echo '<h6>';
echo $this->flashMessenger()->render();
echo '</h6>';
?>
<a href="<?php echo $this->basePath() ?>/application/tipovalores/index">
	<i class="icon-arrow-left"></i>
	 Regresar</a>

	<?php
echo '<br>';echo '<br>';
				$form = $this->form;
				$form->prepare();

				$form->setAttributes(array('action'=> $this->url.'/application/editartipovalores/index/'.$datos["id_tipo_valor"],
										'method'=>'post'));
				echo $this->form()->openTag($form);
				echo '<p>';
				echo $this->formlabel($form->get('descripcion'));
				echo $this->formelement($form->get('descripcion'));
				echo '<p>';
				
				echo $this->formlabel($form->get('estado'));
				echo $this->formelement($form->get('estado'));
				echo $this->formelement($form->get('activo'));
				echo '<p>';
				echo $this->formlabel($form->get('valor_padre'));
				echo $this->formelement($form->get('valor_padre'));
				echo $this->formelement($form->get('id_tipo_valor_padre'));
				echo '<br>';
				echo '<p>';
				
				echo $this->formelement($form->get('submit'));
?>
<a class="btn" href="<?php echo $this->basePath() ?>/application/index/index">Cancelar</a>
<?php
				
				echo $this->form()->closeTag($form);
				?>
				<br>
				

</div></div></div>